### ISSUE TITLE
In a node component's willUnmount hook there is no access to this.props.node.getDocument() anymore

### ISSUE THREAD

**Issue by michael** [substance/substance#1]
We have this problem here: https://github.com/substance/substance/blob/master/ui/nodes/link_component.js#L25

It seems that the node is detached before the hook is called.

https://github.com/substance/substance/blob/master/document/node.js#L17

Reproduce: Delete a link in HTML Editor.

**Comment by obuchtala** [comment]
Of course, because the view is not called first, but always after model changes.
willUnmount is only called before the UI component is disposed.

What do you try to solve?

**Comment by michael** [comment]
Yeah i understand but no idea how to solve it properly. A guard in the willUnmount seems not a sane way?

**Comment by obuchtala** [comment]
but what are you trying to do with document in willUnmount?

**Comment by michael** [comment]
Unregister the event proxies... 

https://github.com/substance/substance/blob/master/ui/nodes/link_component.js#L26-L27

**Comment by obuchtala** [comment]
Store doc in this.doc during didMount. That's ok to do.

**Comment by michael** [comment]
ok

**Comment by michael** [comment]
Fixed.
