### ISSUE TITLE
Deal with edge case where there is no focused Surface

### ISSUE THREAD

**Issue by michael** [substance/substance#100]
In controller there's the API `ctrl.getSurface()` which returns the currently active surface. However, we don't have an invariant that says that there is always one surface that has the focus. For instance, after the initial load of the editor no surface is selected. So getSurface would return null. This could be a source of errors for users. It would be nice to be able to rely on a value for getSurface. If there is only one surface registered we could just return that... if there are more.. maybe return the first registered one. Or is that too magic.. Ahh just want to have a clear API for interacting.. and working with a surface is fundamental i think.

**Comment by michael** [comment]
We could require the controller to take a surface instance already in the constructor, that being the defaultSurface. So controller always manages 1..n surfaces. but not 0. Like that we would introduce the concept "primary surface".

**Comment by obuchtala** [comment]
I agree, that there should be an initial surface for sake of consistency.
I don't see that a 'primary surface' concept would add much beyond solving the initial problem, as after that the current surface is determined by user interaction.

**Comment by michael** [comment]
We took care of this.
