### ISSUE TITLE
Optimisation: Allow equality checking of commandStates object

### ISSUE THREAD

**Issue by michael** [substance/substance#1005]
We needed to disable deep-equality checking of command states because we sometimes have complex objects in the command state (e.g. see EditInlineCommand).

I removed the checks in  `CommandManager.updateCommandStates` and `Toolbox.shouldRerender`.

A better approach may be to only allow plain objects for command states, that we can easily check for equality. However then some tools (like LinkTool or EditHTMLInputTool in Stencila) would need to register on node updates themselves and don't get 'updated' through the command state.

**Comment by obuchtala** [comment]
Obsolete.
