### ISSUE TITLE
 Exports for packages

### ISSUE THREAD

**Issue by michael** [substance/substance#1024]
We need to find a consistent way for exporting classes of a package. Since https://github.com/substance/substance/pull/1020 we don't export them flat anymore.

For instance previously I was able to `import { ProseEditor } from 'substance'`. But I agree this leaks into core-space and is not ideal. So what I can do now is including those classes in the object exported by the package. Not exactly beautiful from a usage point of view:

```js
import { ProseEditorPackage } from 'substance'
const { ProseEditor } = ProseEditorPackage
```

I think ideally, packages would be separate completely, not even part of the substance.js bundle. A pretty ugly deep require is needed then but I'd find it more consistent.

```js
import { ProseEditor } from 'substance/packages/prose-editor/ProseEditorPackage'
```

In an ideal modular world usage would be:

```js
import { ProseEditor } from 'substance-prose-editor'
import ProseEditorPackage from 'substance-prose-editor'
```

However we really don't want to have each package in a separate repo with separate versions etc.

What can we do here?

**Comment by michael** [comment]
Can we tell rollup somehow to resolve `import { ProseEditor } from 'substance-prose-editor'` to substance/packages/prose-editor/ProseEditorPackage.js?

We could also create individual single builds in dist for each package. So we have externals:

```
dist/substance.js
dist/substance-prose-editor.js
dist/substance-paragraph.js
dist/substance-heading.js
```

Then in a browser integration:

```html
<script type="text/javascript" src="./lib/stencila/lib/substance.js"></script>
<script type="text/javascript" src="./lib/stencila/lib/substance-paragraph.js"></script>
<script type="text/javascript" src="./lib/stencila/lib/substance-heading.js"></script>
```

hmm.. really not sure....

**Comment by obuchtala** [comment]
I think I prefer the way it is now:
```
import { ProseEditorPackage } from 'substance'
const { ProseEditor } = ProseEditorPackage
```

IMO, the typical usecase is to use a package as it is.
In the comparably rare cases where you need to derive the package, it is ok to have this extra unpacking.

**Comment by obuchtala** [comment]
Obsolete.
