### ISSUE TITLE
Add i18n to Component API?

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#104]
ATM we rely on a global instance of polyglot, which is not nice: 1. it is a global, 2. making polyglot a hard dependency.

Instead I would like to introduce an i18n abstraction API which would be configured and injected on app level and used in components via `this.getLabel()` being a convenience method for `this.context.i18n.getLabel()` plus some fail-safe checking.
This should be convenient enough, and still provide all flexibility, i.e. we could just use a simple hash for looking up labels for now.

**Comment by obuchtala** [comment]
@michael thoughts?

**Comment by michael** [comment]
this.getLabel() :+1: but maybe in a writer-specific basecomponent class than in component.js directly.

**Comment by Integral** [comment]
Oh yes! That would be great, even outside of writer...

**Comment by obuchtala** [comment]
Done.
