### ISSUE TITLE
Running tests in browser currently not working

### ISSUE THREAD

**Issue by michael** [substance/substance#1042]
Currently we can't run the tests in the browser. There seems to be a misconfiguration in the make file:

```
node make test:browser -w -s
```

Opening `http://localhost:4000/test/index.html` should be possible.

**Comment by michael** [comment]
@oliver---- Daniel and I have troubles with running the test suite. For some reason resolving index.js files does not work anymore.

```
Rollup failed with UNRESOLVED_IMPORT { Error: Could not resolve '../../model' from packages/find-and-replace/FindAndReplaceManager.js
    at error (/private/tmp/substance/node_modules/substance-bundler/dist/vendor.js:110627:12)
    at /private/tmp/substance/node_modules/substance-bundler/dist/vendor.js:120048:7 code: 'UNRESOLVED_IMPORT' }

Error during execution of Command  js
Error: Could not resolve '../../model' from packages/find-and-replace/FindAndReplaceManager.js
```

Any idea?

**Comment by obuchtala** [comment]
Seems to be a regression in bundler. Probably since our NZL session.

**Comment by obuchtala** [comment]
@michael, @Integral could u try plz

Also make sure you understand this: https://github.com/substance/substance/pull/1046/commits/6c86946bb4cf1910d7f5ffcd61f1ddca73ef3b43

**Comment by michael** [comment]
Thanks! And regarding that import.. that was my bad.

**Comment by michael** [comment]
Just checked and it's working for me now. Maybe when there's a chance to bring back the browser tests that would make it easier to debug them.

**Comment by obuchtala** [comment]
I think it should be working now.

```
> node make test:browser
> open tests/index.html
```

**Comment by Integral** [comment]
Thanks a lot!

**Comment by michael** [comment]
Should we bring back the dev server setup as documented in the README...?

>Run the dev server.
> ```
> npm start
> ```
>
>Navigate to `http://localhost:5550/docs` for the docs and `http://localhost:5550/test` for the test suite. Test suite and docs are rebuilt as you make changes to the source files.

Or rather change the README and suggest to open the tests via the FS?

**Comment by obuchtala** [comment]
The only thing I really care, is to have the test-suite built like it is done now. Running a server is ok with me.
