### ISSUE TITLE
Implement find&replace operations

### ISSUE THREAD

**Issue by michael** [substance/substance#1043]
Implement search and replace operations according to tests:

https://github.com/substance/substance/blob/search-replace/test/FindAndReplaceManager.test.js

**Goals (high priority):**

- [x] Enter search string, press enter should select first match
- [x]  Press CMD+G (or find next button) should select next match (cycle to first match after last match has reached), use `editorSession.setSelection(...)` for selecting the current match
- [x]  Press CMD+SHIFT+G should select previous match
- [x]  Press CMD+ALT+E (or replace next button) should replace next match
- [x]  Press "Replace All" button should replace all matches
- [x]  Improve styles to look like in mockup (see https://github.com/substance/texture/issues/127)
- [x]  all found matches should be highlighted using markers manager
- [x] Introduce natural way to "close" find-and-replace panel (press ESC key)
- [x] CMD+G or ESC or CMD+ALT+E should also work when cursor is in searchString input field (global key handling?)

**Use browser test environment for developing the algorithms:**

```
node make test:browser -w -s
```

Update: brower test env is currently broken (https://github.com/substance/substance/issues/1042), use `npm test` meanwhile 

**Development environment for UI:**

- Use substance/examples#search-replace together with substance/substance#search-replace
- Use npm link substance for development
- Start watcher for substance lib
  ```
  substance $ node make lib:browser:dev -w
  ```

- Run the examples use dev mode:

  ```
  examples $ node make dev -w -s
  ```
- Open http://localhost:5556/image/index.html (this should show find-and-replace UI dialog)

**Comment by michael** [comment]
Some more issues now that we have markers activated:

- [x] When search+replace is active we should always recompute matches + update markers when changes to the document are made (currently matches get out of sync)
- [x] Alwasys follow (scroll to) the selectedMatch (this only works with native selection atm when the cursor is in the text and CMG+G is used to find the next match)

**Comment by obuchtala** [comment]
> When search+replace is active we should always recompute matches + update markers when changes to the document are made (currently matches get out of sync)

Markers are kept up2date by MarkersManager. In which way this does not work ATM?

**Comment by michael** [comment]
@oliver---- I'm still investigating.. I think the main issue is that matches are not recomputed on document change. Trying that right now... if i find a problem with the markers update i will add a detailed issue.

**Comment by obuchtala** [comment]
I just wanted to point out, that there is already some updating going on. E.g. if you type before a marker, the marker is moved. Thus, your assumption that you need to recompute all the time is not correct in all cases.

**Comment by obuchtala** [comment]
You probably need to find a way to update incrementally, because re-evaluating the search on keystroke will result in bad performance on big documents.

**Comment by michael** [comment]
Let's assume you have searched for "xxx" and you find one match. Now if you type inside like "xxax", the marker disappears.. but next i press backspace and have "xxx" again, but there is no marker anymore. How should I detect this case other than recomputing on all document changes?

**Comment by obuchtala** [comment]
then you have a problem ;)

**Comment by obuchtala** [comment]
SpellCheckManager evaluates in a debounced way. Probably you want to do this too.

**Comment by michael** [comment]
Yeah that's one way to improve performance. Will look into that. However I also think that *some* performance decrease is acceptable but only while you are in search+replace mode, since the user wants that immediate feedback.

**Comment by obuchtala** [comment]
Ok. Then go with the brute-force way for now.

**Comment by obuchtala** [comment]
One idea for optimisation: invalidate on per text-node basis. Then you only need to run the search on changed text.

**Comment by michael** [comment]
Anfühlen tut sichs jedenfalls mal sehr fein jetzt. ;)

**Comment by michael** [comment]
First iteration done.
