### ISSUE TITLE
Buttons are off in LinkTool

### ISSUE THREAD

**Issue by michael** [substance/substance#1074]
Find out why this is, and provide proper solution, no padding/margin hacking.

![image](https://user-images.githubusercontent.com/2931/27908685-63c28ed0-624d-11e7-9019-48943d0e35c1.png)

@Integral you could take this over if you have time.

**Comment by rquast** [comment]
My dirty patch for this was..

```
.sc-edit-link-tool {
  align-items: center;
}
```

**Comment by michael** [comment]
Not too dirty actually. Can you submit a PR, so you are  credited for the patch. ;)

**Comment by rquast** [comment]
Will do. :)
