### ISSUE TITLE
Drag of selection currently broken in develop

### ISSUE THREAD

**Issue by rquast** [substance/substance#1107]
I know it's the develop branch, and you may already know this, but drag is currently broken. Screenshot below (using develop branch of examples).

Error at https://github.com/substance/substance/blob/develop/model/operationHelpers.js#L74

![develop_drag_broken](https://user-images.githubusercontent.com/1103891/29202279-0384e21a-7eaa-11e7-9872-662dd1c56c9e.png)

**Comment by obuchtala** [comment]
Thx for reporting!

**Comment by obuchtala** [comment]
Obsolete.
