### ISSUE TITLE
Problems in Firefox

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#1108]
We have found a number of problems/regressions related to ContentEditable handling in Firefox recently, which appeared without any related changes in our implementation.
For now, we recommend using Chrome primarily.
On the long run we want to bring back Firefox support.

**Comment by obuchtala** [comment]
See https://github.com/substance/texture/issues/241

**Comment by Integral** [comment]
Could you please describe what's going wrong?

**Comment by obuchtala** [comment]
Firefox's behavior seems to have changed slightly: e.g. selection is not up2date after moving cursor with keyboard. I tried already increasing the delay - which helps.
Additionally, the dead-keys seem to work differently now. That's just two things I have noticed so far.
Wanted to have this issue here, so that others are aware that FF support is currently not optimal.

**Comment by obuchtala** [comment]
Obsolete.
