### ISSUE TITLE
Pasting few paragraphs in multiline editor

### ISSUE THREAD

**Issue by Integral** [substance/substance#1111]
We are not covering a case now when someone paste few paragraphs into multiline editor ([e.g. pasteDoc, but without Container](https://github.com/substance/substance/blob/develop/model/paste.js#L29)).
This turning into error later when we are trying to [get position of node inside non-existing container](https://github.com/substance/substance/blob/develop/model/paste.js#L120).

My proposal is to have a few options:
1) Have an option for TextPropertyEditor to always paste plain text 
2) Merge nodes with new lines between them (could be quiet difficult actually)

@oliver---- what do you think?

**Comment by Integral** [comment]
While we have no time to tackle this seriously we could merge #1119. It will paste plain text and not throw errors at least.

**Comment by obuchtala** [comment]
I like your solution, because it improves the situation in any regard.
The other complex solution sounds a bit too much hassle for the rather low benefit.

**Comment by obuchtala** [comment]
Fixe via #1119
