### ISSUE TITLE
Make an extensible Clipboard (or let it bubble up)

### ISSUE THREAD

**Issue by rquast** [substance/substance#1114]
I have a situation where I'd like to handle paste events from pasting images (screenshots in the copy buffer mostly) into the editor. Primarily, I'd like to handle this in my own code, rather than in substance. However, the problem is that Clipboard.onPaste() stops the event from bubbling up so the parent element that my paste listener is on is never fired.

Is there a way to either make Clipboard extensible, or to set a flag to let it bubble up?

https://github.com/substance/substance/blob/develop/ui/Clipboard.js#L119

**Comment by rquast** [comment]
No hurry on this.. I'll just hack it for now by commenting out event.stopPropagation(). Is that line really necessary?

**Comment by obuchtala** [comment]
Obsolete.
