### ISSUE TITLE
Basic support of internet explorer

### ISSUE THREAD

**Issue by Integral** [substance/substance#1121]
By "basic support" I mean lack of errors during script loading.
Currently any file with substance.js will produce blank page in IE11. While es5 bundler is broken (you have to change condition [here](https://github.com/substance/substance/blob/develop/make.js#L96) to `target === 'browser:legacy'`), the real problem is that es5 bundle will have at least `Object.assign()` method which isn't supported by IE at all.

**Comment by Integral** [comment]
Looks like buble is very much sensible... Currently it produced very strange code. Don't know what to do with it...

**Comment by obuchtala** [comment]
Obsolete.
