### ISSUE TITLE
Ability to use ElementSchema.findFirstValidPos while in invalid state

### ISSUE THREAD

**Issue by michael** [substance/substance#1126]
I got the following situation. I want to write a transformer to convert to a fully expanded fig in Texture JATS. Schema:

```
object-id, title, caption, graphic
```

However as an input I have the following state: el = `<fig><graphic/></fig>`, which is valid in JATS4R but not TextureJATS. 

Now I want to add (expand) the missing pieces (object-id,title,caption), and would like to ask for the correct insert position using schema inspection. However `schema.findFirstValidPos()` always returns -1 if `el` is in an invalid state.

```js 
let schema = TextureJATS.getElementSchema('fig')
let pos = schema.findFirstValidPos(el, 'object-id')
...
```

Is it possible / achievable to make that work still, so we can insert elements until the schema is finally correct. I'd expect pos to be 0 in the example before.

@oliver---- thoughts?

**Comment by obuchtala** [comment]
Obsolete.
