### ISSUE TITLE
ToolPanel and app states

### ISSUE THREAD

**Issue by michael** [substance/substance#1130]
just a dump of thoughts...

Current situation:

- ToolPanel definition via configurator
- Interpreted by different consumers (e.g. Toolbar, Overlay)
- We can define multiple overlays, e.g. AnnotationTools, InsertTools
- All overlays are in the dom all the time, only after rendering they get `sm-hidden` class attached

Desired new features:

- Exclusivity for overlays (only one popup can be active at a time)
  - Consider app state (activePopupId)
  - E.g. ToolDropdown in Menu and AnnotationOverlay are competing (opening one, closes the other)
- Ability to add tools for content nodes (e.g. cell options in stencila, or figure options in texture)
  - Option 1: content nodes takes care of rendering
    - pro: positioning can be done relative to parent node (e.g. anchor below ellipsis icon)
    - con: many instances of the same Menu
  - Option 2: global overlay (commandstate derived from app state + selection state)
    - pro: only one overlay instance (independent from content node)
    - pro: we can just enable contextual overlays (based on node selection or explicit click) via configurator (means we can turn it on/off on any isolated node type)
    - con: needs more advanced positioning strategy
- consider a toolpanel states reducer, that inspects command states and determines which toolpanel should be active and which not.
  - if we managed to model exclusivity with the reduction, we would always know which toolpanel is active
  - in most cases we could derive activePopupId (e.g. when depending on the selection)
  - then we could have simple renderer implementations for toolpanels, instead of letting them reason about the command state

**Comment by obuchtala** [comment]
Obsolete.
