### ISSUE TITLE
API for saving data from editor to data?

### ISSUE THREAD

**Issue by kidqn** [substance/substance#1141]
Hi all, 
I didn't find any documents about api for saving data.
I want to make online docs editor with real time databases.

Thanks for any helps.
Dinh

**Comment by kilburn** [comment]
Check out the [image example source](https://github.com/substance/examples/blob/v1.0.0-beta.6/image/app.js), it has stub code for save handling.

The hard part (for me) is the whole exporter stuff. Because I didn't need any images/files, I ended up simply saving the internal JSON representation:

```javascript
class SaveHandler {
    saveDocument(params) {
        return new Promise((resolve) => {
            const doc = params.editorSession.getDocument();
            const value = JSON.stringify(doc.toJSON());
            // send "value" to the server, store it in localStorage or whatever.
            resolve();
        });
    }
}
```

You can then load that state by doing:

```javascript
// fixture is your "default" document definition, each example has one
let doc = cfg.createDocument(fixture);
try {
    console.info('Importing document');
    const json = JSON.parse(/* recovered value */);
    const converter = new JSONConverter();
    converter.importDocument(doc, json);
} catch(err) {
    console.warn('Cannot import document from the given input');
}

let editorSession = new EditorSession(doc, {
        configurator: cfg,
        // other options...
});
```

**Comment by obuchtala** [comment]
Thanks @kilburn.
We are working on documentation for the 1.0 release. This topic will be covered.

**Comment by rodoch** [comment]
I'm interested to know if this ever got documented anywhere? I'm interested in the same question.

**Comment by obuchtala** [comment]
Obsolete.
