### ISSUE TITLE
DragManager messes up with events that don't pertain to the editor

### ISSUE THREAD

**Issue by kilburn** [substance/substance#1150]
I'm integrating substance into a larger site. The editor itself is not full text (more like the editor here in github), and other components need to handle their own drag/drop stuff.

Unfortunately, the current `DragManager` implementation attaches its handlers to the entire browser document:
```javascript
this.el = DefaultDOMElement.wrapNativeElement(document)
```

After that it messes up with the events (stopping propagations and stuff) so all my other components' drag-n-drop gets broken.

I have side-stepped the issue by overriding that class with my own implementation, which does exactly the same thing but with that single line changed to:
```javascript
this.el = DefaultDOMElement.wrapNativeElement(context.rootDOMElement || document)
```
And then I pass the editor's root DOM element in the context when creating the editor session:
```javascript
let editorSession = new EditorSession(doc, {
    // ...
    context: {
        rootDOMElement: document.getElementById('editor')
    }
});
```

I'm not submitting a pull request because it is a single-line change, and I don't know whether you'll like the approach, or want to change the name or whatever. Anyway, I would suggest for you to provide a similar option because as it stands substance is unusable as just a component on a larger app that needs to handle drag-n-drop for other stuff.

**Comment by obuchtala** [comment]
I agree. It should not mess with the global DOM, or only if asked so.
I will take a look at the code and your proposal.

**Comment by obuchtala** [comment]
I suppose, DragManager should not be instantiated inside of EditorSession in first-place.
-- EditorSession is in a messy state and we are about to refactor it.
After that, DragManager would be created on a higher-level, and allow to control the scope via constructor param.

**Comment by obuchtala** [comment]
Obsolete.
