### ISSUE TITLE
Is localization tested?

### ISSUE THREAD

**Issue by kilburn** [substance/substance#1151]
I need to use substance in another language (ca for catalan).

I've been able to provide translations for the different components using the `config.addLabel(...)` api. That part works fine.

The problem comes when I try to change the active language. I've tried several things:

1. Passing the `lang` option when creating the editor session (`let editorSession = new EditorSession(doc, {lang: 'ca'})`
2. Changing the language after the editor session is created (`editorSession.setLanguage('ca')`)
3. Changing the default language in the configuration object, before creating the `editorSession` (`cfg.setDefaultLanguage('ca')`)

None of that works because the [Configurator's `getLabelProvider()` function](https://github.com/substance/substance/blob/2e5320993f62e51b44f82bf97c2ce29e854b991d/ui/Configurator.js#L543) always returns a [`DefaultLabelProvider`](https://github.com/substance/substance/blob/2e5320993f62e51b44f82bf97c2ce29e854b991d/ui/DefaultLabelProvider.js#L5) with no language specified. As a result, the language is effectively fixed to `en` (the default value for the unspecified `lang` parameter).

I have side-stepped the issue by overriding the `getLabelProvider` method of my `cfg` object and returning a `DefaultLabelProvider` with my desired language:
```javascript
cfg.getLabelProvider = function () {
    return new DefaultLabelProvider(this.config.labels, 'ca');
};
```

This is an obviously hacky solution. Most probably, the default label provider should:

1. Be initialized using the `Configurator`'s default language
2. Somehow listen to the `EditorSession`'s language changes and update its active language.

I'm still not confident enough with the codebase to attempt a proper solution, sorry.

**Comment by obuchtala** [comment]
We had an example, I need to look it up.
Will come back to you with it.

**Comment by obuchtala** [comment]
This was indeed in a strange state.
I have fixed it, tidied up and added a test case.
See #1155.

**Comment by obuchtala** [comment]
Now it is tested. Thx for reporting this.
