### ISSUE TITLE
Invalid CSS comment in _surface.css and _codeblock.css

### ISSUE THREAD

**Issue by de-code** [substance/substance#1165]
This doesn't look quite valid CSS (should use `/* ... */`):

https://github.com/substance/substance/blob/2e62cc48516529a6195b002ecc6f3fe3a712c975/packages/surface/_surface.css#L7
`// We want Firefox to have a transparent native selection`

and:
https://github.com/substance/substance/blob/2e62cc48516529a6195b002ecc6f3fe3a712c975/packages/codeblock/_codeblock.css#L6
`// Toolbar styles`

(This ends up in the bundle)

**Comment by michael** [comment]
Fixed, thank you!
