### ISSUE TITLE
Properties of type array of objects are not exposed correctly

### ISSUE THREAD

**Issue by michael** [substance/substance#1169]
Input:

```js
Book.schema = {
  type: 'book',
  authors: { type: ['object'], default: [] },
  ...
}
```

Later it resolves to `['array', 'id']` when it should be `['array', 'object']`

![image](https://user-images.githubusercontent.com/2931/38163973-33fde4aa-34fd-11e8-9938-49241d822f7c.png)

**Comment by obuchtala** [comment]
@michael I have fixed this. Maybe you have some workarounds that you can remove now.
