### ISSUE TITLE
Selection flaw: Double click on paragraph should make a property selection of the double clicked paragraph

### ISSUE THREAD

**Issue by michael** [substance/substance#119]
We get a container selection currently. So when you start typing the text goes into the next paragraph, deleting the selected one.

Not high priority, but we should take care of this sooner or later.

**Comment by obuchtala** [comment]
After some thinking, I come to the finding, that there are two cases for `deleteSelection`. One when the user explicitly deletes a selection. Then the behavior should be like it is now.
But when typing, this is more like **replacing** the selection. Thus we need to treat these cases differently.

**Comment by obuchtala** [comment]
Shifting this to Beta 3, as it needs some more planning.

**Comment by obuchtala** [comment]
The selection issue is fixed.
I will open another issue for the 'typing over' behavior I mentioned.
