### ISSUE TITLE
Edit inline node is not working for nodes which goes one after another

### ISSUE THREAD

**Issue by Integral** [substance/substance#1190]
Discovered in substance/texture#514. This is also related to other inline node types.
The reason behind is [here](https://github.com/substance/substance/blob/develop/ui/EditInlineNodeCommand.js#L18). E.g. when you set cursor between nodes, `getAnnotationsForSelection` will return two nodes which will not work for condition `annos.length === 1`. Can we use just `annos[0].getSelection().equals(sel)`?

**Comment by michael** [comment]
For inline nodes shouldn't we show the edit dialog only when the inline node is selected, but not when the cursor is between? But definitely we need to change the active condition.

**Comment by Integral** [comment]
Sorry, you're right, but I mean the other thing. When you select the node
your selection also on the edge of other node, so it will not pass through
this condition. I can change it, but I don't why you introduced this
condition and don't want to break anything here.

**Comment by obuchtala** [comment]
I can't remember why we have added the first check. Just make it `annos.length > 0` so that the second one is safe.

**Comment by obuchtala** [comment]
Fixed.
