### ISSUE TITLE
[Feature Request] Allow substance components to return components as their root?

### ISSUE THREAD

**Issue by e-e-e** [substance/substance#1195]
For example, the current behaviour requires component X returns a 'div' as its root element.
```js
import { Component } from 'substance'
import Y from '../ComponentY'

export default class X extends Component {
  render ($$) {
    var el = $$('div')
    const y = $$(Y).append('some content...')
    el.append(y)
    return el
  }
}
```

But I would like to return the root element as component Y.

For example:
```js
import { Component } from 'substance'
import Y from '../ComponentY'

export default class X extends Component {
  render ($$) {
    var el = $$(Y).append('some content...')
    return el
  }
}
```

At the moment the latter is throwing some wild and unexpected errors for me. From `Uncaught TypeError: Cannot read property '_comp' of null` to even call stack exceeded errors depending on the context.

I am using version 1.0.0-preview.37.

**Comment by obuchtala** [comment]
ATM, this must be a regular element. But please feel free to turn this issue into a feature request. This was definitely something we were also wanting several times.

**Comment by e-e-e** [comment]
Ah cool - good to know its a know constraint! Thank you @oliver----. I will modify the title of the issue to make it into a feature request.

In the mean time - it could be beneficial to catch this and warn the user. Might save some folk some time in debugging. I definitely just spent way too long diagnosing this.

**Comment by obuchtala** [comment]
Yeah. Sorry about the debugging experience.
Will do what you suggested!

**Comment by e-e-e** [comment]
You don't need to apologise - I am really enjoying using substance and am happy to help contribute by finding any issues.
Thanks so much for making such a great open source library.

**Comment by obuchtala** [comment]
At least I found that we have a check in the code already ;) 
So you saw an exception `"Component.render must return VirtualHTMLElement"`, didn't you?
Should improve the error message. And documentation-wise we are not at all in a good place.

**Comment by e-e-e** [comment]
Actually no - I did not see that error at all. But perhaps that is a version issue - and I should update to the latest.

Its tough - without docs - I have just been reading your code. I should probably be helping also by contributing back documentation as I go.

**Comment by obuchtala** [comment]
That would be a wonderful contribution!

**Comment by obuchtala** [comment]
Re: exception. I can confirm that the test I have for that is not sufficient. So this slipped through.

**Comment by obuchtala** [comment]
merged #1196 with a fix for detecting invalid `render()` implementation.

**Comment by obuchtala** [comment]
Returning `$$(Component)` is on the way...
https://github.com/substance/substance/commit/15375f3e85e1058b2e07c4a99fc79a4258fa6fab

**Comment by michael** [comment]
Working now with preview.75.

**Comment by e-e-e** [comment]
Amazing - thanks guys.
