### ISSUE TITLE
ES5 support?

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#1199]
I find myself using more and more ES6 features. Some of them are not supported by `bublé`.
This means that we either switch to `babel` for transpilation, or we decide not to bundle for ES5 at some point.

@michael @Integral what is your take?

**Comment by obuchtala** [comment]
I have tried our testsuite on current versions of other browsers: Edge, Firefox, Opera. All of them are working. With node already good with es6 syntax, I don't see strong reasons to support es5 in the future.

**Comment by obuchtala** [comment]
I have disabled the es5 build for now, because it is blocking me.

**Comment by Integral** [comment]
I would say that I also can't see strong reasons.
One thing I see from our work is the concept of "Readers". E.g. Texture generates some html with highlighting api. But in this cases we could add babel on higher level. So, i'm agree with you ;)

**Comment by obuchtala** [comment]
Ok Thanks! :) Then I will leave it disabled.
If someone else seeing having a convincing reason then we can still use babel.
