### ISSUE TITLE
Selection flaw: Double clicking next to a paragraph creates a weird container selection

### ISSUE THREAD

**Issue by michael** [substance/substance#120]
In chrome:

![selection-bug](https://cloud.githubusercontent.com/assets/2931/10334985/5ecd24d6-6cee-11e5-9e7e-2809c03d3de4.gif)

**Comment by obuchtala** [comment]
Unfortunately I can't work on this as the current content is different.

I.e. doesn't have authors anymore.

**Comment by obuchtala** [comment]
I think this is working now as expected.
