### ISSUE TITLE
Remove DocumentNode attach/detach API

### ISSUE THREAD

**Issue by michael** [substance/substance#123]
Analog to Component we should get rid of some of the lifecycle methods namely `attach` and `detach`. We favor the way via construction instead of attaching a node at a later time. So the new DocumentNode constructor would take `document`, `props` as constructor arguments.

Analog to the Component we introduce a `dispose` method that is called when a node is deleted from the document.

**Comment by michael** [comment]
Is this fulfilled now with the new Node API?

**Comment by obuchtala** [comment]
I has been removed.
