### ISSUE TITLE
Importing references without doi

### ISSUE THREAD

**Issue by yoruyenturk** [substance/substance#1232]
Hello,

I'm using Texture 1.0 on windows 10. I exported the references from Zotero as CSL-JSON and i'm trying to import them to Texture 1.0. Although it works for the records containing DOI number,  The software gives the following error for the records that do not have a DOI. Do you have any suggestion for solving this issue?

Conversion error
- Error: Citation must have DOI.

**Comment by obuchtala** [comment]
Obsolete.
