### ISSUE TITLE
CDATA Text elements makes schema invalid

### ISSUE THREAD

**Issue by Integral** [substance/substance#1233]
A good example of this is `tex-math` element in JATS. `tex-math` defined as an element which contains `text`. However if your `tex-math` contains only CDATA our XMLSchema validator will tell us that `<tex-math> is incomplete. Schema: TEXT`.
As far as I can tell we should do something special about CDATA during [children check](https://github.com/substance/substance/blob/develop/xml/XMLSchema.js#L179).

**Comment by obuchtala** [comment]
I agree, that this is related to child validation.
