### ISSUE TITLE
Good bye JSON as a first-class format?

### ISSUE THREAD

**Issue by michael** [substance/substance#124]
We should move away from JSON as a first-class format. There is a problem with order, when dependencies between nodes exist. For instance, a table cell can not exist before it's parent (table row). So we should be able to express order in our serialisation format. However this order needs to be determined by the specific use-case. Then we can remove all magic related to it:
- loadSeed (lazy attach of nodes, when they annotations etc. to address the problem above)

Needs a bit of thinking but we could get rid of some complexity here.

**Comment by obuchtala** [comment]
Yep. No more.
