### ISSUE TITLE
Find way to avoid rerender cursor flickering

### ISSUE THREAD

**Issue by michael** [substance/substance#13]
We should somehow solve this in the next release. We could really maybe set the selection to null in the in between state.

**Comment by obuchtala** [comment]
Alternatively, we could try to be brave and use keys in text_property_component, i.e., enable preservative rendering.

**Comment by obuchtala** [comment]
But still, we would see some flickering, as DOM TextNodes would always be rerendered.

**Comment by obuchtala** [comment]
Maybe deleting the DOM selection, is the most clever aproach...

**Comment by obuchtala** [comment]
@michael can you try how this works now. I enabled preservative rendering here: https://github.com/substance/substance/commit/431c0a82888155cb963f40af7625f7120d3953ad
However, I figure that this doesn't solve the problem, as TextNodes still get replaced... but let's try.

**Comment by obuchtala** [comment]
I think I got it: 4862424ec50c78a0330e59c3257f29eceec94c97 updates text nodes using `node.textContent = ''`, which seems to preserve the DOM selection.
What you might see now, is that the selection is one char behind, as the text is updated before the DOM selection.

**Comment by michael** [comment]
When i do fast typing in FF i still see the cursor jumping to first char. Now it's not possible anymore to reach the position before the checkbox... as we discussed before. However, it flickers when it corrects the position.

There's also a flickering when we toggle annotations. It's not very obtrusive but still you can see there's some rerendering/resetting going on. when you toggle a strong anno for instance.

**Comment by obuchtala** [comment]
Hmm.. yes in FF I see it too... But Chrome is ok?

**Comment by obuchtala** [comment]
Microsoft Edge is fine.

**Comment by michael** [comment]
Chrome is fine during rapid typing now yes.

**Comment by obuchtala** [comment]
The flickering with the TODO checkbox, can not be solved. If we would remove the DOM selection, we could not use CE for cursor navigation anymore.

**Comment by obuchtala** [comment]
Resetting the selection in the checkbox case also doesn't seem to be a good idea here, because it jumps back. Probably we need to implement a custom navigation here (~goto last character of previous property)...

**Comment by obuchtala** [comment]
I will roll back this change.

**Comment by michael** [comment]
Yeah that's not a big problem, it behaves correct now which is the most important. I just wonder if changes in the markup or styles could have some positive effect. like wrapping it in another div or putting a fake div in front, that we set opacity to 0. But anyway that wouldn't be very satisfiying.. just to learn what options are out there.

**Comment by obuchtala** [comment]
I thought about this a lot... but unfortunately, you can not avoid this totally... there will always be a level where the parent is CE but one child is not.

**Comment by obuchtala** [comment]
The problem right now is, that you can not navigate to the previous property using 'left' key.

**Comment by michael** [comment]
Yeah i see.

**Comment by obuchtala** [comment]
I tried the DOM selection removal trick, it works. However to solve it for all cases, I need a document:willchange event... by then, we will still have the flickering during undo/redo.

Committed a change doing this trick before starting a surface transaction.

**Comment by obuchtala** [comment]
@michael can you try this?

**Comment by michael** [comment]
No cursor flickering anymore anywhere. 

Should this change affect also annotation toggling? It seems it is also less flickery.. but sometimes it does flicker a lil bit..  not sure that's a really subjective observation.

**Comment by obuchtala** [comment]
In FF only or also Chrome? How does setting a second anno feel?
Am 25.08.2015 20:10 schrieb "Michael Aufreiter" notifications@github.com:

**Comment by michael** [comment]
Both. Somehow better.. but not perfect. Check prosemirror demo for comparison.. there's no flickering over there.

**Comment by michael** [comment]
Major flickering when you do this in Chrome: Make two bold annotations close to each other.. then make a selection that intersects with both.. and make it italic.

**Comment by michael** [comment]
ad prev. coment: the first time it's the worst.. when i repeat this by just toggling/untoggling that same selection it goes faster.. but still the regular annotation flicker. I have to run, will check back a bit later.

**Comment by obuchtala** [comment]
Yeah, I think removing the Dom sel increases the flicker impression as it
is just a wider area...
Am 25.08.2015 20:18 schrieb "Michael Aufreiter" notifications@github.com:

**Comment by obuchtala** [comment]
I watched the DOM during ProseMirrors update. It also has massive DOM updates, which can't ever be preservative regarding selection. So I suppose, it is just faster with re-setting the selection.
Also, sometimes I could see flickering there, but only the first time.

**Comment by obuchtala** [comment]
I have the feeling now, that it is a matter of optimization. in avg, we need 4-8ms for applying a transaction and 8-12ms for rerendering the selection. If got both together under 8ms, then maybe we would not see the flickering anymore.

**Comment by michael** [comment]
It seems when i set the checkbox wrapper (that has contenteditable: false) to  position: absolute it doesn't mess with the cursor anymore.

**Comment by michael** [comment]
I will try to apply this fix.. it will look more professional. maybe we can use this as a trick in other places just to tell an element it's not considered in flow for editing.

**Comment by obuchtala** [comment]
interesting!

**Comment by michael** [comment]
pushed. it works!

**Comment by obuchtala** [comment]
Until we optimize selection the best approach is to do total rerendering + wiping DOM selection before typing.
For me there are many times now where you do not see the flicker anymore. With a future optimization we should be able to handle it.

**Comment by michael** [comment]
let's call it a beta-1 ha? :)

**Comment by obuchtala** [comment]
Oh.. Just FYI: our `<br>` in text property causes a bit of a layout lag...

**Comment by obuchtala** [comment]
I am gonna implement simple rerender using DocumentFragment

**Comment by michael** [comment]
how do i observe this 'lag'?

**Comment by obuchtala** [comment]
remove the br in text-property component's render and try...

**Comment by obuchtala** [comment]
the br is there to support a better behavior with soft-breaks.

**Comment by obuchtala** [comment]
Do you see the same?

**Comment by obuchtala** [comment]
Maybe it is nothing... I have the feeling, that flickering is less often without the br... but maybe just random...

**Comment by obuchtala** [comment]
rubbish...

**Comment by michael** [comment]
you mean the annotation toggle flickering now? i will check.

**Comment by obuchtala** [comment]
Nah... it is just random... I just had it in there.. and observed maybe like 10+ toggles without flicker...
I think the key is to get render+setSelection < 5ms

**Comment by michael** [comment]
I confirm. Seems random.

**Comment by michael** [comment]
am I safe to tag it v1.0.0-beta1?

**Comment by obuchtala** [comment]
Sure.
There is still a long way to 1.0 ;)

**Comment by michael** [comment]
will we see beta20 ? ;)

**Comment by obuchtala** [comment]
Nah, it isn't that bad either ;)

**Comment by obuchtala** [comment]
Wait.

**Comment by obuchtala** [comment]
I just tried to remove the setTimeout in surface.rerenderDomSelection(). Which seems pretty good to me.
I think it is a relict of async rendering with react... Let's check if that has no side-effects

**Comment by michael** [comment]
I will do some packing and you push fix and i check. ;)

**Comment by obuchtala** [comment]
pushed

**Comment by michael** [comment]
Zero flickering mister! :+1:

**Comment by michael** [comment]
wow! :open_mouth:

**Comment by obuchtala** [comment]
Probably we could even get rid of the DOM selection clear... but as it is working, let us just leave it for now.

**Comment by obuchtala** [comment]
AND: one more time I am happy to have got rid of react ;)

**Comment by michael** [comment]
Fantastic!

**Comment by obuchtala** [comment]
Amazing how far you can get with a less smart implementation. :)

**Comment by obuchtala** [comment]
Can u explain why the absolute position thing with ce=false is working?
Do you need to add margins for the other stuff?

**Comment by obuchtala** [comment]
or... to refine my question... how is it done, that the text property still seems to respect the flow?

**Comment by michael** [comment]
it's just working by setting position: absolute. it seems that the contenteditable cursor movement ignores those out-of flow elements. which makes sense because that would be really hard to reason about e.g. when you have a lot of overlapping layers.
