### ISSUE TITLE
Getting rid of nested modules (e.g. Basics/Helpers)

### ISSUE THREAD

**Issue by michael** [substance/substance#135]
I figure that we have very few static modules (oo+helpers), most things we are documenting are classes actually. I had the following ideas:
## Option 1

To avoid nesting we could maybe push some of our sub modules into one static function collection that we call basics. This would include helpers, and OO functions.

``` js
var _ = require('basics');
_.inherit(Cat, Animal);
```

Then the docs could exist on top level of the basics module.

Pro: Less entry points to learn the 'Substance standard lib'
Con: mixing lodash stuff with OO stuff
## Option 2

Using `basics` really just for organisational purposes on the file/dir level but calling Helpers and OO first class modules. Then we could Call it Substance Helpers instead of Substance Basics.Helpers.

Pro: Docs get more lightweight
Con: There is no 1:1 mapping between module names and the file layout anymore.
## Option 3

Moving some things to the top level, imo the file noise would be acceptable. We'd then have:

```
/oo.js (module)
/helpers.js (module)
/jquery.js (module)
/event_emitter.js (class)
/path_adapter.js (path adapter)
/factory.js (class)
```

Pro: Most accessible / user-friendly for the library user. E.g. requiring the Helpers module `require('substance/helpers')` Requiring the OO module: `require('substance/oo')`
Con: Potentially noisy on top level as we add more things.

---

As for myself I guess I would would prefer 3) to have a consistent nomenclature where each substance concept that is general-purpose gets it's own slot on top level (e.g. `Substance.EventEmitter` `Substance.Helpers`). While `Document` is a real module, that encapsulates various functionalities that can only exist together, `Basics` is merely a pseudo module, just to group core things together. I think it would help people when they can map concept names (EventEmitter) to require statements (require('substance/event_emitter').

**Comment by Integral** [comment]
I was also confused with this. Let's keep it logically together...

**Comment by obuchtala** [comment]
We have folders now, using deep requires. Files have the same name as the class/function/module they provide. We will try to use lodash directly, without helpers in future.
