### ISSUE TITLE
Code restructuring before beta 2 launch

### ISSUE THREAD

**Issue by michael** [substance/substance#137]
There is some potential and we should do this in a dedicated iteration, so we break require paths only once:
- better/clearer organisation of basics module
- use - instead of _ for filenames, so they map better to require statements: `require('basics/event-emitter')`
- how to organise ui module (nodes, tools, commands, should there be sub folders for surface-commands, controller-commands etc.
- how to follow common.js idioms but allowing deep require as much as possible, maybe give up on common.js module way and use module names just to group classes
- discussion keeping structure flat (easy require access) vs. having different types of classes in the same folder. challenge is to find a good balance. e.g. we could move all classes that extend component into a ui/components folder. just then we have mixture of tools, nodes, general purpose stuff such as scrollbar. maybe that's fine.. but maybe we want more structure. just i don't like current approach, where scrollbar is scoped into writer.. default_tools is scoped into editor etc. we should have this stuff more general purpose.

**Comment by obuchtala** [comment]
Considering this as done.
