### ISSUE TITLE
Expanding selection using double click does not work under Microsoft Edge

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#14]

**Comment by michael** [comment]
Let's run the latest Substance on Edge and see if there are issues now.

**Comment by obuchtala** [comment]
Still the same.

**Comment by obuchtala** [comment]
Is it so that double click should select a word and triple click the whole node?

**Comment by michael** [comment]
yep that would be ideal i think.

**Comment by obuchtala** [comment]
Turned out to be regression of the persisted selection impl on blur.
