### ISSUE TITLE
Implement WebResource node type

### ISSUE THREAD

**Issue by michael** [substance/substance#147]
I'm planning to implement a simple WebResource node type, that just refers to an url to a content piece somewhere stored on the web. We could literally support anything but I think we should start wit a useful set of supported embeds.

How about the following types:
- Image (allow just a regular image url)
- _Tweet_ (possible using oEmbed API see: https://api.twitter.com/1/statuses/oembed.json?
  url=https://twitter.com/Interior/status/463440424141459456)
- Youtube (http://www.youtube.com/oembed?url=http%3A//youtube.com/watch%3Fv%3DM3r2XDceM6A&format=json)
- Vimeo (also supports oEmbed see https://vimeo.com/api/oembed.json?url=https%3A//vimeo.com/76979871, https://developer.vimeo.com/apis/oembed)

Implementation idea:
- When user presses the insert resource button they get prompted with an url input field
- We do some analysis of the url (if it contains youtube/vimeo/twitter and query the corresponding oembed API's to get the corresponding embed codes, which we store on an html property of the node

Concerns:
- Security? We need to make sure the html content is safe when we render it
- We may get a jumpy interface, because embeds are dynamically fetching content such as images etc. we need to make sure the scrollbar stays up to date etc.

**Comment by michael** [comment]
Consider: http://iframe.ly

**Comment by Integral** [comment]
And this: https://github.com/itteco/iframely

**Comment by michael** [comment]
Thanks @Integral. This is now implemented. And we use iframe.ly but can configure a different embed Resolver.

**Comment by Integral** [comment]
Is it good that we have this kind of service dependency?

**Comment by michael** [comment]
We don't have it as a dependency. It's a configuration option.

See: https://github.com/substance/lens/blob/master/LensController.js#L59-L67
