### ISSUE TITLE
Inserting nodes with no components breaks

### ISSUE THREAD

**Issue by michael** [substance/substance#149]
Reproduce:

``` js
      var img = tx.create({
        id: Substance.uuid("image"),
        type: "image",
        src: 'path/to/image.png',
        previewSrc: 'path/to/image.png'
      });

      return surface.insertNode(tx, { selection: args.selection, node: img });
```

Image does not have any editable areas (=components) but this is assumed in Container._handleInsert.

It fails here because `_getNodeComponents` returns an empty array and causes `_insertComponentsAt` to crash.

![image](https://cloud.githubusercontent.com/assets/2931/10560079/266bbc3c-7500-11e5-9e7b-e0858f5c1cf4.png)

**Comment by michael** [comment]
I think we should not require a DocumentNode to have components. Seeing this assumption in various places. E.g. node.js. 

``` js
  getComponents: function() {
    var componentNames = this.constructor.static.components || [];
    if (componentNames.length === 0) {
      console.warn('Contract: a node must define its editable properties.', this.constructor.static.name);
    }
    return componentNames;
  },
```

Let's support non-editable nodes which have no `Node.static.components` value set.

**Comment by michael** [comment]
Node.statc.components -> Node.statc.fields   (editableFields)

**Comment by michael** [comment]
Maybe we can get rid of explicit component listing by deriving that info again from the view component. Since we no longer depend on React, we can analyze our component's VirtualDOM.

**Comment by michael** [comment]
I assume this is no longer an issue... will check.

**Comment by michael** [comment]
This is still not addressed in the current implementation. It fails here:

![image](https://cloud.githubusercontent.com/assets/2931/11918138/226e4f6c-a725-11e5-8e72-5cb271def3f1.png)

getAddressablePropertyNames returns an empty array here. And of course you can not determine a path for a non-existent property.

What semantics should getPathForAddress have for nodes that have no text properties? Should it just return null? How we make code that depends on getPathForAddress robust?

**Comment by michael** [comment]
I tested this but I still see the same error. Can we investigate that together?

**Comment by obuchtala** [comment]
I am working on this. Needs to be solved in Container.

**Comment by obuchtala** [comment]
Now this should be working basically. Not perfect yet, but ok to continue.

**Comment by michael** [comment]
That's been fixed.
