### ISSUE TITLE
Better css modularization

### ISSUE THREAD

**Issue by michael** [substance/substance#155]
Learning...

This solution looks good:

http://hugogiraudel.com/2015/06/18/styling-react-components-in-sass/

We should follow this
http://sass-guidelin.es/#the-7-1-pattern

Also has some wisdom....
http://bensmithett.com/smarter-css-builds-with-webpack/

**Comment by michael** [comment]
I'm in the middle of a transition to modular css. However it will not be done in a single iteration...  Here's some more good read for reference: http://www.smashingmagazine.com/2014/07/bem-methodology-for-small-projects/

**Comment by Integral** [comment]
russians everywhere

**Comment by obuchtala** [comment]
To me it looks like this is done. Reopen it if you think it is not.
