### ISSUE TITLE
Handle triple clicks.

### ISSUE THREAD

**Issue by michael** [substance/substance#157]
When we use contenteditable=false islands, tripple clicking on a paragraph only selects to the bounds of that island, which is not desired. Instead we should implement our own behavior when a triple click happens. See Visual Editor.

Additionally we want to avoid that triple clicking leads to a container annotation. So if we had this handler we can also do that here.

**Comment by michael** [comment]
Will try to land this one in Beta3....

**Comment by michael** [comment]
See first attempt: #349 works quite well as long as you don't click between the lines, where no mousedown event is triggered. Why is that? :/

**Comment by obuchtala** [comment]
Thx. Doing this on Surface works perfectly.
