### ISSUE TITLE
Make scroll follow the cursor

### ISSUE THREAD

**Issue by michael** [substance/substance#16]
This is really needed for a serious editing experience. I will work on a scrollToCursor/Selection implementation and then we connect it with the Surface.

**Comment by michael** [comment]
If only this would work for contenteditable too: http://jsfiddle.net/2r2fpekx/12/

**Comment by obuchtala** [comment]
One problem is that a collapsed selection does not have a bounding rect.
This describes a hack to get such a rect by injecting a span temporarily: http://ask-wenda.appspot.com/r/5707702298738688/5648640/know-when-caret-goes-outside-of-contenteditable-scrollable-div

**Comment by obuchtala** [comment]
When we start to render the selection ourselves we will have everything to get this done.

**Comment by obuchtala** [comment]
We can't do that yet, as we need to render selections always for that.

Shifting to Beta 3

**Comment by obuchtala** [comment]
While we have the methods now, we still need to integrate it. Shifting to beta 5.

**Comment by michael** [comment]
Fixed via #882
