### ISSUE TITLE
Implement generic citation concept in core and write tests

### ISSUE THREAD

**Issue by michael** [substance/substance#174]
We want to make citations a core concept, so that you can cite any object in the document. We need to decide wether users must define a concrete Subtype: BibItemCitation < Citation or if we just use a generic citation property and introduce a citationType property. We need to implement special indexes for that then.

**Comment by michael** [comment]
We may want to support citations with multiple targets or single targets. It may get a bit crazy if we want to allow deep citations in combination with multiple targets but let's see how things develop there.

**Comment by obuchtala** [comment]
Don't think it is a core concept. Will be done in scientist.
