### ISSUE TITLE
Pasting HTML for external sources breaks

### ISSUE THREAD

**Issue by michael** [substance/substance#176]

**Comment by michael** [comment]
Wait not really true. It actually happens when I paste from a Substance document (that is open in a different editor window).

However I also get an error when I want to paste some complex content from outside. E.g. selected a bunch of elements in this Github issue and then saw this:

`node` is expected to be a rich object that has an hasChildren method. But it seems to be a plain object.

<img width="597" alt="screen shot 2015-10-28 at 18 21 41" src="https://cloud.githubusercontent.com/assets/2931/10796977/c7bc1034-7da0-11e5-8508-4da858314716.png">

**Comment by obuchtala** [comment]
Fixed.
