### ISSUE TITLE
Introduce NodeSelection

### ISSUE THREAD

**Issue by michael** [substance/substance#184]
We want to be able to select block elements (e.g. complex structures like a figure) provide a custom selection highlighting for those nodes and also cut+paste them.

**Comment by obuchtala** [comment]
This is now there, however we need to make consistent use of it.
I.e., whenever you work with a selection be aware you should check
- `sel || sel.isNull()`: for null selections
- `sel.isPropertySelection()`
- `sel.isContainerSelection()`,
- `sel.isNodeSelection()`,
- `sel.isCustomSelection()`

**Comment by obuchtala** [comment]
Done.
