### ISSUE TITLE
Make insert transformation preserve annotations

### ISSUE THREAD

**Issue by michael** [substance/substance#19]
Current behavior for inserting 'a' in different selection scenarios:

First char of annotation touched:
![image](https://cloud.githubusercontent.com/assets/2931/9590609/fe57781a-5035-11e5-9e1d-924448061534.png) 

![image](https://cloud.githubusercontent.com/assets/2931/9590634/3de3aecc-5036-11e5-8544-424f82ddd573.png)

Strict overlap:
![image](https://cloud.githubusercontent.com/assets/2931/9590755/f6f38d4c-5036-11e5-8188-2ff233198c2b.png)

![image](https://cloud.githubusercontent.com/assets/2931/9590762/005329ec-5037-11e5-92a7-e424c1e8cde0.png)

Desired behaviour: the inserted character should preserve all annotations.

**Comment by obuchtala** [comment]
@Integral The second case is implemented already which should suffice for the search and replace scenario in the archivist. Is that ok with you? see https://github.com/substance/substance/tree/fix-replace-text
The rest I will address in the coming weeks.

**Comment by Integral** [comment]
@oliver---- in 70% cases we need this for replacing initials of respondents, so this is the case with beginnings of annotation, maybe we could reduce it to strict overlap... what do you mean by second case?
Also we use old substance for archivist-core...

**Comment by michael** [comment]
Tested. Works.

**Comment by Integral** [comment]
@michael is it working now in both cases? Could I use it somehow with old version?

**Comment by michael** [comment]
Oh sorry, second case still does not work when you have a bold annotation and select only the first part of it. When you type then the annotation is lost. For search+replace this is essential. Then we can back port. @oliver---- could you look into supporting the use case "first chars touched by selection". The "strict overlap" use case works. In order to back port, we just grab the insert transformation and and move it to the legacy substance or is there more to do?

**Comment by michael** [comment]
@oliver---- can you look into this, it's almost done.. just not working when there is only a part select (touching the first char). I could then port it back to the legacy Substance. Daniel would need this to activate search+replace feature in the archivist.

**Comment by obuchtala** [comment]
Sorry. Won't make it into beta 2.

**Comment by obuchtala** [comment]
Not yet. Shifting to beta5.

**Comment by obuchtala** [comment]
Done.
