### ISSUE TITLE
Doc: Bring in support for Events

### ISSUE THREAD

**Issue by michael** [substance/substance#198]

**Comment by obuchtala** [comment]
Are events like regular members? (static class member, module member)
Or are there more options?

**Comment by obuchtala** [comment]
After some thinking, it seems that events are typically something bound to a class. I.e., an instance is emitting an event, and others  bind to this instance to listen.
Thus, it does not bring much to support events as module members.

**Comment by michael** [comment]
True. They always have a source. That's also how jsDoc handles it. http://substance.io/docs/module-ui.Controller.html#event:command:executed

**Comment by michael** [comment]
Let's stick them only on classes.

**Comment by obuchtala** [comment]
I am just thinking how to derive the context for events, as there is no source code to derive it from.
context = the class associated to.

Doing it explicitely using

```
@event ui/Controller.command:executed
```

Or implicitely attaching it to the current class

```
@event command:executed
```

Also we might want to use another symbol as `ui/Controller.command:executed` looks stange.

**Comment by obuchtala** [comment]
I decided not to use global ids here, such as `ui/Controller@command:executed`, as this would is not robust against file. Better to use local ids, such as `Controller@command:executed`.

**Comment by obuchtala** [comment]
Done.

**Comment by michael** [comment]
You were too fast. Was just looking at the syntax options. I like how it's done now.

**Comment by obuchtala** [comment]
I allow both local and global id for the owning class. Actually, it is confusing when the ids are not consistent.

Thus, after seeing the result, I prefer always using the global ones.
