### ISSUE TITLE
Shipping modular Substance distributions (or not)

### ISSUE THREAD

**Issue by michael** [substance/substance#2]
I was thinking of what would be the best way to deliver a dist for the HTMLEditor component. It would be nice to just have a single minified js file that one can include in a client-side app. However keeping customisability alive we would also need to expose Substance.Component, so it would be more a SubstanceWithHtmlEditor dist. Usage:

``` js
// window.Substance is available.
var Component = Substance.Component;
var $$ = Component.$$;

var Toolbar = Component.extend(...);
var htmlEditor = $$(Substance.HtmlEditor, {
  toolbar: Toolbar,
  content: "<p>some text</p>"
});
Component.mount(htmlEditor, $('#editor_container'));
```

I'm not sure if this is a good way to be honest. For instance if you want to use some other Substance components (e.g. writer) then you would need to 2 dists.. duplicating a lot of code.

Maybe we should use the following strategy, shipping one preconfigured HtmlEditor with standard toolbar to be used by the kids that just want to embed a widget, and for all others we require a browserify workflow.

Usage of the simplest Substance Editor widget would then look like:

``` js
Substance.HtmlEditor.init('#editor_container');
```

Thoughts?

**Comment by obuchtala** [comment]
I think in future, and particularly for a project like substance, people will rather use libraries as we do it now, i.e., creating custom builds using browserify or such.
So while I understand that you want a bundle for the HtmlEditor as standalone widget, I don't believe that this will be so important for the whole library.

**Comment by michael** [comment]
Think so too. Also that's a good compromise to say whenever you want to customise something, you have to `require('substance')`.

**Comment by michael** [comment]
I think we will do components only for the start. It's so minimal and useful. Also maintaining distributions can get time-consuming, since we will have npm releases anyway.
