### ISSUE TITLE
Deep linking for docs

### ISSUE THREAD

**Issue by michael** [substance/substance#200]
We need to enable deep linking to classes or methods so we can share links to the docs.

**Comment by obuchtala** [comment]
Do you mean URL derived app states?
This would indeed be helpful, as we could use the browser history, and as a side result get navigation to previous app states, too.

**Comment by michael** [comment]
Exactly.

**Comment by michael** [comment]
https://github.com/substance/ui/blob/master/document_controller_mixin.js#L494-L532

**Comment by obuchtala** [comment]
Done via d7b7d4821e5025cabd294718baaba413bf05a595
