### ISSUE TITLE
Return statement gets parsed together with subsequent comments

### ISSUE THREAD

**Issue by michael** [substance/substance#201]
Input:

![image](https://cloud.githubusercontent.com/assets/2931/11029789/a0e1eb3c-86c9-11e5-9c68-8203d4f593ae.png)

Result:

![image](https://cloud.githubusercontent.com/assets/2931/11029359/ba52f712-86c6-11e5-877a-675d56319794.png)

Would the correct syntax be?

@return {Array} an array of container annotations

**Comment by michael** [comment]
When I fix the return statement it gets parsed correctly. The ATTENTION block gets hidden which is also quite fine. Will all text that is below the @ statements be ignored?

**Comment by obuchtala** [comment]
Regarding syntax: http://usejsdoc.org/tags-returns.html

Regarding parsing: We should not have comments below tags. Tags can have longer content, so it it important to eat more than just a line. Beyond that I don't want to mess with it, as this is implemented in dox.

So: we need to fix our docs.

**Comment by michael** [comment]
Make sense. We may want to have comments internally that we don't want to expose.. E.g. TODO:   HACK: etc. How should we approach that?

**Comment by obuchtala** [comment]
Either, not putting it into the parsed block.

Or using a custom tag @todo?

**Comment by michael** [comment]
Not sure about @hack though ;) Opening a second block with /\* */ would work i think...

**Comment by obuchtala** [comment]
Second block is not a good idea, as then you loose the context of the first. i.e. the code statement attached to a comment block is the first one after a block.
Depends on what you want to achieve... a custom tag would mean you wanted to show it in the docs potentially.
If you want to just have it in the code, I would rather add a `//` comment to the implementation body.

**Comment by michael** [comment]
No i think we really want to keep that stuff internally and in the code and don't confuse the API user with it. So // in the implementation body it is I would say.. thanks for clearing this up.
