### ISSUE TITLE
Doc: Inherits

### ISSUE THREAD

**Issue by michael** [substance/substance#204]
Can we bring that in again, and put it underneath the Class Heading?

![image](https://cloud.githubusercontent.com/assets/2931/11031745/f08ca764-86d6-11e5-909d-c11163131199.png)

Maybe we want inherits from first and then the defined in.. not sure. Just wanted to save some space so i put things into one line.

**Comment by michael** [comment]
I'd also say that we don't show inherited props/methods for now.. that would produce too much redundancy. I have some ideas on how we can make the cross-reference experience better.

**Comment by obuchtala** [comment]
Yes, this should be simple then.
Not showing the inherited members is fine with me for now, only I need to disable hiding abstract classes. On the long run we should add a means to show inherited properties...

Regarding cross-references, could u open an issue, and give a short statement of your idea?

**Comment by obuchtala** [comment]
Done.

**Comment by michael** [comment]
I don't see it. Shouldn't this show up for ContainerEditor? That it inherits from Surface. Or maybe i missed putting a tag?

**Comment by obuchtala** [comment]
Have u used @extends?

**Comment by michael** [comment]
Jeh that works.
