### ISSUE TITLE
Idea: Smart anchoring

### ISSUE THREAD

**Issue by michael** [substance/substance#205]
This could be useful for navigating the Substance documentation.

The problem:
- When you click on a cross reference, you loose your reading place

Idea:
- We remember the last 5 anchors and display a highlight in the scrollbar to answer the question: 'Where was I before?'

Limitations: This only works well when positions are explicitly anchored... Remembering anchors based on scroll positions could get a bit too weird.

**Comment by obuchtala** [comment]
Maybe I didn't get this right.
ATM, I don't use native anchors for cross-links, but do the same as in the TOC, i.e., triggering a scrollTo from within the app.
With #200 we would have the regular browser history. Do we need more?

**Comment by michael** [comment]
We would just need to conform to the native anchoring concept, and we need to provide small '#' links next to class headings and method signatures where an anchor can be set explicitly.

Not sure if we should use html-ids since we need to convert our ids. E.g. docs#model/Document goes into data-id and for scrolling we can use the Panel.scrollToNode method.

Anyway.. I think the browser history thing is important, the highlighting stuff is more playful and i will implement when there is time.

**Comment by michael** [comment]
We should discuss this in the office.

**Comment by obuchtala** [comment]
With a router and browser history this is much better.

**Comment by michael** [comment]
Anchoring is good enough.
