### ISSUE TITLE
Better ui concept for functions

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#206]
Looking at the transforms, the ui concept is not appropriate, i.e., having redundancy.
@mql Could you consider this in your mockup and maybe also put the mockup somewhere for reference?

**Comment by michael** [comment]
Hm.. indeed a bit tricky. I see two options
- combining function heading with the signature    *\* model / transform / breakNode (tx, args) **
- dropping the function heading only leaving the signature (then people would need to derive the require location from the  source string "defined in model/transform/breakNode.js#16"

**Comment by michael** [comment]
I think with signature only + an example that includes the require statement, things would be good enough.

**Comment by obuchtala** [comment]
Hmmm... If there was a class before, u could not see easily that it is a different file, and not just another member function.

**Comment by michael** [comment]
It would also say "Function defined in" instead of "Method defined in".

**Comment by obuchtala** [comment]
Still... that is like giving a heading2 a heading3.
I would opt for the first option, adding the sig to the heading..

**Comment by michael** [comment]
Should work as long as names don't get too long. Will sketch it.

**Comment by michael** [comment]
Like this:

![image](https://cloud.githubusercontent.com/assets/2931/11033214/b4d8538e-86e1-11e5-9fac-3b7c57457536.png)

**Comment by michael** [comment]
Or arguments first and then description?

**Comment by michael** [comment]
Will implement this when you are happy.

**Comment by obuchtala** [comment]
I think this is fine.

**Comment by michael** [comment]
Done.
