### ISSUE TITLE
Consider @components

### ISSUE THREAD

**Issue by michael** [substance/substance#208]
This is important I think, so we can provide a different signature.

Instead of

``` js
new ContainerEditor()
```

We can do:

``` js
$$(ContainerEditor, {...})
```

**Comment by obuchtala** [comment]
Just thinking about reusibility: atm our 'parser' is quite general supporting a jsdoc dialect.
Would love to keep it that way.

I will do this as a post-processing after parsing.

**Comment by michael** [comment]
i mean this is still a @class i would say.. it just adds @component to be a 'special' class.

**Comment by obuchtala** [comment]
Maybe we want to be able to pass custom tags into the model?

**Comment by obuchtala** [comment]
Then I could leave the parsing jsdoc 'compliant'.

**Comment by michael** [comment]
That's fine i think. It would just be useful to have separate ComponentComponent so we customize the rendering without messing up ClassComponent.

**Comment by obuchtala** [comment]
Done.
