### ISSUE TITLE
Render type of documented properties.

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#209]
@michael  could u sketch the ui for properties

Only thing here is how to integrate the type...

**Comment by michael** [comment]
![image](https://cloud.githubusercontent.com/assets/2931/11034468/22460af6-86ec-11e5-8da0-1527e985319a.png)

**Comment by obuchtala** [comment]
:+1:

**Comment by obuchtala** [comment]
Let's do this .)

**Comment by michael** [comment]
Done
