### ISSUE TITLE
Auto-generate docs

### ISSUE THREAD

**Issue by michael** [substance/substance#210]
We should activate publishing to http://substance.io/docs again.

**Comment by michael** [comment]
Also probably we are ready soon to merge this with master.

**Comment by obuchtala** [comment]
First we need a site-generator.

**Comment by michael** [comment]
gulpfile business for the documentation app bundling and then we need to run the generator and put the file as documentation.json in the doc dist folder as well.

**Comment by obuchtala** [comment]
gulp business is done. I think for beta 2 it is fine to push it manually.
Let's reactivate that webhook in beta3

**Comment by michael** [comment]
@Integral takes that over.

**Comment by Integral** [comment]
@michael could we try to commit something to master? Or just make --allow-empty?

**Comment by michael** [comment]
Sorry one sec - i will commit a changelog file to master + an API update so we see if the docs get updated.

**Comment by michael** [comment]
Commited to master some Toolbar docs. Don't see a commit to `substance/docs` yet though.

**Comment by Integral** [comment]
Yes, there are some problems, I will investigate

**Comment by michael** [comment]
I get another commit ready in the meanwhile. ;) Let me know when I should push the button.

**Comment by Integral** [comment]
@michael should work now, please try!

**Comment by michael** [comment]
I made an edit directly on Github.

**Comment by michael** [comment]
how much time is it supposed to take until the update happens. Should I also try a 'real' push?

**Comment by Integral** [comment]
it's there, it takes maybe 2 minutes...

**Comment by Integral** [comment]
just like installation and bundling...

**Comment by michael** [comment]
Nice! :) well done!

A new era, with always up2date docs.

**Comment by Integral** [comment]
yes, awesome! give me another ;)
