### ISSUE TITLE
We need some kind of method index

### ISSUE THREAD

**Issue by michael** [substance/substance#211]
It's very hard to find a particular method without ctrl+f, by clicking and scrolling only. Thinking how where we could add a method index. Maybe inline would be just fine:

![image](https://cloud.githubusercontent.com/assets/2931/11037361/ab10e868-86fd-11e5-8443-21c4ecbe89a2.png)

Maybe we evantually want to make the full API of a class foldable... that would make it easier to get an overview. However it complicates actions like clicking on a toc item, and general crossrefs.

**Comment by Integral** [comment]
+1 for this
it's very important to see just a list of methods related to class (as well as other things like events)

**Comment by obuchtala** [comment]
Seeing our docs growing, I agree that it is important.
It should be fairly simple introducing a MemberSummary component.
This would be the preferred place to show inherited stuff, too.
~~@michael could u update the mock regarding inherited members?~~ aahh i think it is clear enough

**Comment by michael** [comment]
Will take care of this.

**Comment by obuchtala** [comment]
I introduced a model/MemberIndex which should make this technically a no-brainer.

**Comment by michael** [comment]
Looks like this now. We don't yet display inherited stuff. Let's do this in a separate iteration and first test if it's good enough to have users navigate to the parent class.

![image](https://cloud.githubusercontent.com/assets/2931/11151908/ecd384c4-8a2f-11e5-88b1-e4183665bb96.png)

**Comment by obuchtala** [comment]
Do you consider properties and events too?

**Comment by michael** [comment]
properties yes.. events.. forgot. They'll show up in `instance.event` scope ?

**Comment by obuchtala** [comment]
I suppose which doesn't make sense though... let me check (node needs to have isStatic)

**Comment by obuchtala** [comment]
Events are actually like innerclasses 'per se'... maybe I should treat them specially in indexer?
Or are u ok with having them in instance?

**Comment by michael** [comment]
instance is good yes! I add my parts.

**Comment by michael** [comment]
Pushed. 

How will we deal with constructors? That would be wrong in the instance.method bin. So I either we put it into class.method  or handle it special somehow.

**Comment by obuchtala** [comment]
Hmmm. That is true. In Ecmascript the constructor is class member: MyClass.constructor

**Comment by obuchtala** [comment]
Events are there.

**Comment by obuchtala** [comment]
Should I sort members on server side?

**Comment by michael** [comment]
Maybe it's always the first class method in the list. So you'd get 

Class methods: constructor anotherMethod

Problem I see: We want to display the constructor always as the first member. Followed by instance methods and then class methods. So from a UI perspective it would live in a separate bin.

How about `constructor.method`.

**Comment by michael** [comment]
Just to be pragmatic on the modelling side.

:+1: for member sorting on the server side.

**Comment by obuchtala** [comment]
I could add ctors into an extra bin

```
index['ui/Component'].constructor.Component
```

**Comment by michael** [comment]
Just worried my code is not robust against different categorization scopes. That's why I suggested:

``` js
index['ui/Component'].constructor.method -> {Component: Component}
```

**Comment by obuchtala** [comment]
But it's not consistent. As all other types are indexed via name.

**Comment by obuchtala** [comment]
Ah you mean an extra bin inbetween?

**Comment by michael** [comment]
It would be via name:

```
index['ui/Component'].constructor.method -> {'Component': ComponentClass}
index['ui/Component'].class.class -> {'VirtualNode': VirtualNodeClass, 'VIrtualElement': VirtualElementClass}
```

**Comment by obuchtala** [comment]
Hmmm.. why again not just

```
index['ui/Component'].class.constructor -> {'Component': ComponentClass}
index['ui/Component'].class.class -> {'VirtualNode': VirtualNodeClass, 'VIrtualElement': VirutalElement}
```

```
```

**Comment by obuchtala** [comment]
This would make most sense.

**Comment by michael** [comment]
Lol... yes. :)

**Comment by obuchtala** [comment]
Can you sort in your MemberIndexComponent? unfortunately order gets lost by indexing...
The global order I can take care of.

**Comment by michael** [comment]
Really? 

I mean yeah, if we do loose order i will sort in the memberindex component...

**Comment by obuchtala** [comment]
No.. it seems that they are not yet ordered... would have been surprised, too.

**Comment by obuchtala** [comment]
Sorted out ;)

**Comment by obuchtala** [comment]
Done.
