### ISSUE TITLE
Htmleditor: dom should be loaded

### ISSUE THREAD

**Issue by Integral** [substance/substance#22]
Looks like dom should be loaded when you are attaching html-editor, otherwise toolbar will be not activated. It's not a bug I think... But you should wright about this.

**Comment by michael** [comment]
Yeah of course you have to wait for the initial DOM load before you attach the editor. Did you do it as described here?

https://github.com/substance/demos/tree/master/prose-editor

**Comment by Integral** [comment]
yes, but in my case it's worked only with timeout, you should leave note
there

**Comment by michael** [comment]
Can you point me to the integration code once you have it, so I can check?
