### ISSUE TITLE
Comment block parsing

### ISSUE THREAD

**Issue by michael** [substance/substance#222]
I'm currently changing the comment block syntax to be easier editable:

Old:

```
  /**
   * Render the component.
   *
   * ATTENTION: this does not create a DOM presentation but
   * a virtual representation which is compiled into a DOM element later.
   *
   * Every Component should override this method.
   *
   * @return {VirtualNode} VirtualNode created using Component.$$
   */
```

New:

```
  /**
    Render the component.

    ATTENTION: this does not create a DOM presentation but
    a virtual representation which is compiled into a DOM element later.

    Every Component should override this method.

    @return {VirtualNode} VirtualNode created using Component.$$
  */
```

However.. this leads to a different result, as 2nd and 3rd text block gets parsed as a codeblock.

![image](https://cloud.githubusercontent.com/assets/2931/11117127/751accb0-8937-11e5-8326-69fb0274f46c.png)

Is there something we can do about it? Generally I wanted to ask if you agree with the less \* syntax.

**Comment by michael** [comment]
I mean i see why it is parsed as a code block (4space indent). Mhh... maybe that's exactly why the stars are there in each line.

**Comment by obuchtala** [comment]
Need to take a look at this. dox is trying to remove the indent of the 
first line from all other lines. But maybe there is some problem there...
Can you provide me with a setup where this change is there (maybe on a 
tmp branch)

**Comment by michael** [comment]
Let me push this to the component-docs branch. 

Generally: Is working with the \* only for me such a hassle or is there a secret trick. it's especially annoying if I want to break some content into a new line.

**Comment by michael** [comment]
*pushed

**Comment by obuchtala** [comment]
It is annoying yes. The editor would need to allow all the tab-ing sugar while having a \* in the beginning.
Maybe there is an extension for Sublime to do this...

On the other side... it is pretty clear how it should work from the parser side. If this is not working then there is a problem in dox, which we should fix.

**Comment by obuchtala** [comment]
Gimme some time for that.

**Comment by obuchtala** [comment]
Should work now.

**Comment by michael** [comment]
Just a thought before I forget it: We could do `//` prefixed doc blocks if we converted them to /*\* _/ before we feed it to dox. However with all the problems we discussed (empty lines could break a block accidentally, etc.) also everything then would be considered a comment block. now we can use // for internal and /_\* for official doc-comments. 

It's just that // is the most convenient way to edit (comment a block + uncomment preserving indentation etc.). On the eye it looks better too...

Sorry for bringing up this over and over again.. just to find the best approach as we will have to live with the syntax we choose now for longer ;)

**Comment by obuchtala** [comment]
I am actually against it as it is not a ECMAScript block comment.

**Comment by obuchtala** [comment]
http://www.ecma-international.org/ecma-262/5.1/#sec-7.4

**Comment by michael** [comment]
ok. that argument is strong enough :)

**Comment by obuchtala** [comment]
:)

**Comment by obuchtala** [comment]
Fixed.
