### ISSUE TITLE
Doc: support for nested classes

### ISSUE THREAD

**Issue by michael** [substance/substance#223]
Sometimes we want to expose multiple classes per file using a scoped name. I couldn't get this to work for Component.VirtualNode. See: https://github.com/substance/substance/blob/c36471cec82d4e0e9820dfa0fdc70b335f2c4457/ui/Component.js#L1155-L1171

Need a working example for this, then I will add to other places, like Toolbar (Toolbar.Group, Toolbar.Dropdown).

**Comment by obuchtala** [comment]
Should be done the same way as static properties.
However we will need a concept how to address it UI wise. ATM, they would be (static) members of a class.

**Comment by michael** [comment]
Can you give an example for a proper doc annotation?

**Comment by obuchtala** [comment]
ATM, the way it is done there, it isn't detected as a member.
Let me try to fix it there.

**Comment by obuchtala** [comment]
Or maybe we support that what you tried, using an explicit identifier.

**Comment by obuchtala** [comment]
Will give the parser some treatment

**Comment by michael** [comment]
If this makes addressing easier let’s go for it.. It can be considered a separate class semantically I think. Yes it's also a static member of the upper level class implementation wise but not semantically.

**Comment by obuchtala** [comment]
If its not a nested class (i.e. static class) then your file should come as a module, not as a class.

**Comment by obuchtala** [comment]
So particularly it is _sementically_ a static member. Implementation wise it could be independent if you want.

**Comment by michael** [comment]
I see. Mhh.. the module option is also good to have. However, for Component or Toolbar I like this nesting. Otherwise we would need to:

require('ui/component').Component

**Comment by obuchtala** [comment]
Yep... So my suggestion: treat it as static members internally, and represent it as 'independent' classes.
In the summary you could have a 'Nested Classes' block, however.

**Comment by michael** [comment]
:+1:   I will output the memberIndex without categorizing at first. We will need some helper methods to split them up. 

Should I implement such a thing on ClassNode and ModuleNode ?

**Comment by obuchtala** [comment]
I would use a MemberSummary component and use it for both.

**Comment by obuchtala** [comment]
And yes, only modules and classes have such members atm.

**Comment by michael** [comment]
Working on exactly that. Called it MemberIndex though.

**Comment by obuchtala** [comment]
ok

**Comment by obuchtala** [comment]
Done.
