### ISSUE TITLE
Doc: external links should open a new tab

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#224]
One way to do that would be to add a commonmark post-processor.

**Comment by michael** [comment]
Shouldn't we just have all external inks target="_blank"? If we have a handler in place for crosslinks the default behavior would be intercepted anyway...?

**Comment by obuchtala** [comment]
Is it so?

**Comment by michael** [comment]
I mean as long as we do e.preventDefault() on handled links.

**Comment by obuchtala** [comment]
Hmm.. Don't know if I get you right.
I am talking about external links in md. The cross-link handler listens using a specific selector.
What I mean are the a's generated by the markdown parser.
