### ISSUE TITLE
Doc: separate class from constructor

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#225]
ATM it is not possible to hide the constructor but show the class. Our Component is a good example of having a private constructor. Nodes another one.

@michael what is ur opinion?

**Comment by obuchtala** [comment]
Alternatively, we could do somthing like:

```
/**
MyClass is my class.

@class
@abstract

@constructor

This constructor is used internally only. You should use {@link ui/MyClass.create} instead.

@private
@param
**/
```

I.e., treating the constructor part like a separated comment block.

**Comment by obuchtala** [comment]
Having two blocks would be cleaner:

```
/**
MyClass is my class.

@class MyClass
@abstract
*/

/**
This constructor is used internally only. You should use {@link ui/MyClass.create} instead.

@constructor
@private
@param {String} a
**/
function MyClass(a) {}
```

In future i.e. with ES6, we will have two blocks...

```
/**
MyClass is my class.

@abstract
*/
class MyClass {

  /**
  This constructor is used internally only. You should use {@link ui/MyClass.create} instead.

  @private
  @param {String} a
  **/
  constructor() {a}
```

**Comment by obuchtala** [comment]
We could have it the way it is currenty, but supporting the case with explicit constructor,
i.e. injecting a constructor node, when no explicit constructor is present.

**Comment by michael** [comment]
Sounds good to me - external constructor node...

**Comment by michael** [comment]
We have that now. Closing.
