### ISSUE TITLE
Critical: Pressing cmd + b or cmd + i breaks the editing

### ISSUE THREAD

**Issue by michael** [substance/substance#23]
What happens is that contenteditable kicks in and adds b and i tags. However this breaks the editor. What we should probably do short-term is intercepting all those default keyboard events and delegate to our own actions. Actually i wonder if this should be connected with the tools somehow. Because we would need the same logic canTruncate canExpand etc.

Long-term we should enable this DOM MutationObserver thing.

**Comment by obuchtala** [comment]
Yeah. Just to increase your experience, you could try to fix it, adding an adequate handler here: https://github.com/substance/substance/blob/master/surface/surface.js#L291
On the long run we want to have the ability to register such handlers using extensions. But this is not there yet, so we hard code it here. Maybe it is the correct place in future too, as it is default CE behavior which we have to suppress.

**Comment by netsgnut** [comment]
I am not sure if this is a related issue, but pressing Shift+Enter seems to result in a wrong cursor position too. Ctrl+Enter/Cmd+Enter works fine most of the cases.

**Comment by obuchtala** [comment]
@netsgnut thx for the info

**Comment by michael** [comment]
Fixed via #43. Could not reproduce problems with shift+enter? Oli could you?

**Comment by obuchtala** [comment]
Nope.

**Comment by michael** [comment]
Closing this. @netsgnut please file new issue if you run into the problem again.
