### ISSUE TITLE
Doc: Let's do the switch towards a constructor node

### ISSUE THREAD

**Issue by michael** [substance/substance#232]
I'd like to tailor the comments so that the class info is in a separate block and constructor documentation comes in another.

I'd drop the constructor rendering as we have it now.. which will be replaced as soon as we have constructors in the members array. This will also make the constructor show up in the members index. And we will be able to deep link to it.

**Comment by obuchtala** [comment]
Agreed.

**Comment by michael** [comment]
Ok I dropped it. Next would be supporting the parsing of the second block. I did a comment block for Component.VirtualElement here:

https://github.com/substance/substance/blob/component-docs/ui/Component.js#L1357-L1369

**Comment by obuchtala** [comment]
Done.

**Comment by obuchtala** [comment]
Now we just need to add more documentation.
