### ISSUE TITLE
Unified Element API

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#235]
From #226 evolved another element API, which is now a bit confusing.

We decided introducing an abstract DOM Element API which is used to abstract jquery/cheerio away and which we would use for Component's VirualElements, and Component, too.

**Comment by michael** [comment]
Yeh. Best thing about that abstraction is that we can define and document one interface for Element manipulation, used in Component's render methods as well as in converters. 

Regarding the name: Calling it just Element would be too generic mh?

**Comment by obuchtala** [comment]
Maybe too generic, yep... Maybe you want to sleep over it...

**Comment by obuchtala** [comment]
I think it is a DOMNode actually (could also be text or comment)

**Comment by michael** [comment]
Ya i mean somehow the relation to the DOM is there.. For Substance.Components it would be just the DOMElement facet of it...  while there is more comonent-specific.. like setProps setState etc.

**Comment by obuchtala** [comment]
Yes... would you add setProps to the generic interface? don't know... it seems wrong to me.

**Comment by obuchtala** [comment]
Hmmm.. it could also be in a dom namespace... and then it could be dom.Node / dom.Element ?

**Comment by michael** [comment]
hmm what else would go into dom then? It's clearly also ui.. so maybe ui/dom/Element but I guess ui/DOMElement would not look worse.

**Comment by obuchtala** [comment]
ok. ui/DOMElement is fine with me.

**Comment by obuchtala** [comment]
@michael can u help me with naming?
When I have `ui/DOMElement` being the abstract interface, how should I call the implementation which is using jQuery/native DOM?

**Comment by obuchtala** [comment]
In the other cases it is clear: `ui/VirtualDOMElement`, and Component itself.

**Comment by obuchtala** [comment]
~~`BrowserDOMElement`?~~ nah, it is working for cheerio elements as well

Edit: so for clarification... this implementation works in the browser but also server-side. It uses jQuery/cheerio for many things, and some things are implemented using the respective native implementation.

**Comment by obuchtala** [comment]
An alternative from the Java world: calling the interface `ui/IDOMElement` and the implementation `ui/DOMElement`

**Comment by obuchtala** [comment]
We also could hide the implementation from the programmer, in the way that they would never require the implementation.
E.g., in an importer or an exporter, they would use `el.$$` or `el.createElement()`
In Component renderers it is ok to have it the way it is currently, i.e. using `Component.$$`.

Edit: this would mean I could name the DOMElement implementation in any way, e.g. also `ui/DOMElementImpl` would be possible. Ugly though, but if never `required` that could be acceptable. It would be a private class.

**Comment by obuchtala** [comment]
`ui/DefaultDOMElement`?

**Comment by michael** [comment]
Sorry we are in the wilderness atm. Maybe we have just one abstract
DOMInterface for the documentation. Will be back in evening...

**Comment by obuchtala** [comment]
Done. Interface is clear. Implementation will be improved in future.
