### ISSUE TITLE
Custom rendering of selections

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#24]
- [ ] Surface DDAU: TextProperties shouldn't pull annotations from surface, but instead get them via props from above. Surface is just the better place to know about highlights and selections.
- [ ] Live rendering of selections and cursor: maybe primitive rerender is quick enough for a good enough (flickering?)
- [ ] Scroll to current selection: when we render the selection ourselves, we should be able to scroll to it.

**Comment by obuchtala** [comment]
As a last resort for rendering selections:
We could derive custom selections from the DOM selection client rects, and render them as overlays.
This would avoid needing to rerender TextProperties when dragging selections.

**Comment by michael** [comment]
Where are we here. Live-rendering is not a priority for beta2 but maybe scroll to current selection could be?

**Comment by obuchtala** [comment]
Not yet there. We are able to render selections in general, but we need to experiment how live-rendering behaves.

**Comment by obuchtala** [comment]
I think we are ok with the current state.
SelectionState is a central concept now (more in the flux way of thinking). Live selections is not yet a topic.
Closing.
