### ISSUE TITLE
Implement DOMElement#find for Components

### ISSUE THREAD

**Issue by michael** [substance/substance#249]
Would be useful regarding getting the jQuery dependencies out if you could search inside component instances.

E.g. this code:

``` js
var $panelContent = this.refs.panelContent.$el;
var tocNodeEl = $panelContent.find('[data-id='+tocNodeId+']');
```

Could change into:

``` js
// this = ContentPanel component
var tocNodeEl = this.find('[data-id='+tocNodeId+']');
```

We would then not get a jQuery element but our own DOMElement. The question is should we continue implementing the jQuery API here e.g. i would need the position() method. So instead of `tocNodeEl.$el.position().top` I could do just `tocNodeEl.position().top`.

**Comment by obuchtala** [comment]
Unless you want to implement CSS selectors this is not easily possible.
One could do a find on the DOM side and try to map to components.
Or we could do it like VisualEditor: they store a reference to the view nodes in the DOM via $.data. Then they can navigate back from an element into the view tree.

**Comment by obuchtala** [comment]
Regarding `position`, I have the feeling that I want to keep the $el for a while. So that we are not blocked by lack of DOMElement API.

**Comment by michael** [comment]
Will think about it a bit. I also think we should not reimplement that functionality. Just trying to get rid of the places where we use jQuery directly. 

I'm open for storing component references on the DOM nodes, however they should not be encoded as an attribute.. because it gets really noisy then in the markup.

**Comment by obuchtala** [comment]
What do you think about $.data()? https://api.jquery.com/jquery.data/

**Comment by michael** [comment]
Seems to be a good way to store that kind of stuff yes. Don't want us to get distracted by this things.. though they would be interesting to evaluate for the future.

**Comment by michael** [comment]
We could get a really powerful DOM navigation API at some point, that works on server as well. :)

**Comment by obuchtala** [comment]
Shifting this into Beta 3

**Comment by obuchtala** [comment]
We have this now.
Components are bound to their DOMElement which is bound to its native element with back-link, which would allow us to even query in native DOM and then retrieve the associated components very efficiently.
