### ISSUE TITLE
Component: Supply HTML string

### ISSUE THREAD

**Issue by michael** [substance/substance#25]
There's currently no way to append HTML directly in a component's render method. We should have a .html() method, like in jQuery:

``` js
var el = $$('div').addClass('html-container').html('<b>foo</b>');
```

Not sure if this should work only for HTML constructors or also for custom components. This could potentially conflict with a component's render method. E.g. when you do

``` js
var el = $$(MyComponent).html('<b>foo</b>');
```

Will MyComponent.render be called then? And then overridden? It seems like a bad idea to allow that, but on the other hand the Component API should be consistent.

**Comment by obuchtala** [comment]
Yeah. Consistency first.. if the user does this, it would overwrite anything appended before. That is also what $().html() does, isn't it?

**Comment by obuchtala** [comment]
@michael do you know a cool way to make this safe against script injection?

**Comment by obuchtala** [comment]
This looks reasonable: https://github.com/cure53/DOMPurify

**Comment by obuchtala** [comment]
But actually, this should be done by the app.

```
$$('div').html(dompurify(unsafeHtmlString))
```

I'd rather want to avoid introducing a dependency.

**Comment by obuchtala** [comment]
First iteration done. fc3f46149b32d4aca0e6a0d89094adb3de0621d3

**Comment by michael** [comment]
Works for me. Will write tests tomorrow.
