### ISSUE TITLE
TOCPanel: scroll into view of active item

### ISSUE THREAD

**Issue by michael** [substance/substance#250]
I'm fixing the auto-highlighting of the active tocitem right now.. what i have no solution for yet is when the active item is out of the view... maybe we want the toc to automatically follow the active item.

I would use the same scrollToNode API as we have in other panels, however i'm afraid this will get a bit jumpy.. especially when you scroll back up after the view has switched.

You think i should try out what i described? Or have better idea...?

**Comment by obuchtala** [comment]
I share the concerns.
Don't know.. maybe an icon that show up when active item out-of-view and click scrolls to?

**Comment by michael** [comment]
If it requires extra user interaction I would rather do nothing and let people scroll themselves. But i will play a bit.. i mean.. also maybe now the wrong time to make it perfect. :)

There will be another TOC iteration for Lens because i want to bring thumbs of figures.
