### ISSUE TITLE
TocPanel generalization

### ISSUE THREAD

**Issue by michael** [substance/substance#253]
ui/TocPanel currently depends on the `content` and `level` property of heading. I'd like to generalize that a bit so we just need to implement `schema.getTocTypes()` and `Article#getTocNodes()`. 

I want to keep this operating on regular Substance nodes, so the TOC can react to document changes (e.g. heading gets edited). How about the following contract:
- Each node that wants to show up in the TOC needs to implement `getTocName()` and `getTocLevel()`

**Comment by michael** [comment]
Oli i have a problem with making assumptions on the ordering of members. We have some logic here in the components, and duplicated in the DocumentationTOCPanel, which i would like to get rid of. I'd favor an approach where we implement this logic on the model side. 

E.g. for the NamespaceNode i would implement a getMembers method that considers categorization etc.

``` js
var MEMBER_CATEGORIES = [
  {name: 'modules', path: ['module']},
  {name: 'classes', path: ['class']},
  {name: 'functions', path: ['function']},
];
```

This could go into a mixin for container nodes as well:

``` js
MemberContainerComponent.getCategoryMembers = function(config, node, cat) {
  var doc = node.getDocument();
  var memberIndex = doc.getIndex('members');
  var members = memberIndex.get([node.id].concat(cat.path));
  members = filter(members, function(memberNode) {
    // skip nodes according to configuration
    if ((memberNode.type === "method" && memberNode.isPrivate && config.skipPrivateMethods) ||
      (memberNode.type === "class" && memberNode.isAbstract && config.skipAbstractClasses)) {
      return false;
    }
    return true;
  });
  return members;
};
```

What do you think?

**Comment by michael** [comment]
Do we actually have markup for member categories? Or is it fine if that is flattened?

``` js
  this._renderMemberCategory = function(cat, catMembers) {
    var catEl = $$('div').addClass('se-member-category');
    var membersEl = $$('div').addClass('se-members');
    catMembers.forEach(function(memberNode) {
      membersEl.append(this._renderMember(memberNode));
    }.bind(this));
    catEl.append(membersEl);
    return catEl;
  };
```

**Comment by michael** [comment]
Implemented via #254.

**Comment by obuchtala** [comment]
The categories are used in the MemberIndexComponent.

**Comment by obuchtala** [comment]
I think `Documentation` is a good example of having dynamic content. So IMO the concept for getting the `tocNodes` from the document is general enough now. 
Having the level API on nodes is fine in this case. However I am pretty sure that this is not a general concept. E.g, think about our general Headings. In some special document, there might be a higher-level structure (such as chapters or so), which would lead to different levels than in plain simple documents.

**Comment by michael** [comment]
What would be a better place for level? You have a suggestion?

**Comment by obuchtala** [comment]
I think there is no such place in general :(
In Documentation this is working fine. In our general implementations not. 
In general, only a document knows about the overall structure.

**Comment by michael** [comment]
For now we are good here.
