### ISSUE TITLE
TOC enhancments

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#255]
- highlight of active item could be stronger: when not moving, the difference is too subtle to guide the eye

![image](https://cloud.githubusercontent.com/assets/284099/11188642/393e85c6-8c8c-11e5-9079-007b99ff9f91.png)
- Detection of active item / scroll position mapping could be tweaked. In docs, e.g., for second level items when clicking on toc entry, it scrolls alright, but highlights the previous entry.

![image](https://cloud.githubusercontent.com/assets/284099/11188672/51ac322a-8c8c-11e5-8c5d-640a86c2b491.png)

**Comment by michael** [comment]
Looks like this now.

![image](https://cloud.githubusercontent.com/assets/2931/11257931/647174fe-8e55-11e5-814e-9c21e0981b60.png)
