### ISSUE TITLE
More generic DomImporter API in preparation for LensXmlImporter

### ISSUE THREAD

**Issue by michael** [substance/substance#257]
I'm digging deeper into the new DomImporter implementation. In order to import XML documents of different structures we would possibly need a slightly more generic API. The current implementation assumes that there's one container (configured via config.containerId). It's possible that we will also deal with multiple containers for one XML document. We only have state.container = [] reserved for that atm.

I'd suggest that we work a bit towards a low-level API for DOMConverter that can be orchestrated in a specific converter. Maybe we should move away from a config-based approach to a more explicit approach where each converter has to implement it's own importDocument method, utilising the DOMConverter API.

While this works only for single-container html documents:

``` js
function NoteImporter() {
  NoteImporter.super.call(this, {
    schema: noteSchema,
    converters: converters,
    DocumentClass: Note,
    containerId: 'body'
  });
}
```

For the Lens Converter we need something like this:

``` js
this.importDocument = function(xml) {
  // initialization
  this.reset();
  // converting to JSON first
  var articleElement = DefaultDOMElement.parseXml(xml);

  this.convertDocument(articleElement);
  var doc = this.generateDocument();
  return doc;
};

// XML import
// <article>
//   <meta>...</meta>
//   <resources>...</resources>
//   <body>...</body>
// </article>
this.convertDocument = function(articleElement) {
  // Import meta node
  var metaElement = articleElement.find('meta');
  this.convertElement(metaElement);

  // Import resources
  var resources = articleElement.find('resources');
  resources.children.forEach(function(child) {
    this.convertElement(child);
  }.bind(this));

  // Import main container
  var bodyNodes = articleElement.find('body').children;
  this.convertContainer(bodyNodes, 'main');
};
```

Do you agree with that? What challenges / problems do you see?

Since we would always import one container at a time we could just reset `state.container` per call.. and same probably with `state.stack`? I'm possibly overlooking something so maybe you can give me some pointers before I start.

**Comment by obuchtala** [comment]
Yeah I know, the basic importers are too primitive for real documents.
The way you addressed it was exactly what I had in mind. Providing a simple low-level API, but anything beyond that is hard to generalize.
Resetting the state per 'global' entry is fine. This does not need to support parallel execution. In such a situation I would rather create independent instances.
So 100% agreement.

**Comment by michael** [comment]
Thanks!

I will give it a try tomorrow.

I see some problem with the generateDocument method.. That code would not work with multiple containers.

``` js
  this.generateDocument = function() {
    // creating all nodes
    var doc = this.createDocument();
    each(this.state.nodes, function(node) {
      doc.create(node);
    });
    // creating annotations afterwards so that the targeted nodes exist for sure
    each(this.state.inlineNodes, function(inlineNode) {
      doc.create(inlineNode);
    });
    // filling the container
    doc.set([this.state.containerId, 'nodes'], this.state.container);
    return doc;
  };
```

Shouldn't we just dynamically create bins in `state.containers` when converterContainer is called? We'd then have a structure like this:

``` js
containers: {
   'main': ['p1',...],
   'figures': ['fig1',...]
}
```

`generateDocument` could then work with this collected information. 

We didn't have a concrete usecase yet for multiple containers on a doc but i'm sure we need that soon, so i'd rather implement this now than wait..  E.g. self-contained comments: If we wanted to support for rich comments that are itself containers, we would already have a lot of convertContainer calls. Don't want to store comments as html blobs as we did in an earlier comment implementation.

**Comment by obuchtala** [comment]
`state.stack` is for converting annotated text. So this should be fine, as you would be converting one property at a time.

Multiple bins sounds good. You need a state.currentContainer pointing to the container set by the last convertContainer call.

**Comment by michael** [comment]
It's a plan!

**Comment by michael** [comment]
I want parseXML to return the article element rather than a list of nodes. Is this valid?

``` js
DefaultDOMElement.parseXML = function(xml) {
  if (inBrowser) {
    var parser = new window.DOMParser();
    var xmlDoc = parser.parseFromString(html, 'text/xml');
    if (xmlDoc) {
      var root = xmlDoc.querySelector('body');
      return new DefaultDOMElement(root);
    }
  }

 // will this work?
 return new DefaultDOMElement($(html)[0]);
};
```

**Comment by obuchtala** [comment]
Hmm. Hard to tellm because I don't know exactly.
For parseHtml I went for array because of jQueries parsing delivers an XML.
I fear $(xml) will also give you an array. So I expect this not to work.
BTW, plz look at $.parseXML, this we would use here. Have never used it so don't know how it works.

**Comment by michael** [comment]
I will do it for the browser first and then add tests for the cheerio scenario. 

Here's one more thing I'm not sure about:

`parser.parseFromString(html, 'text/xml');` gives me a document object (as the root) while cheerio uses a different kind of root element (available via $.root(). So maybe it's smart to always return the first child of root by parseXML / parseHTML instead of the root itself. That wold be '<article'> in the LensXML case and '<html>' in the html document case (if a full document is passed). However passing an HTML string like `<p>a</p><p>b</p>` is a bit different.. there is no 'root' element. So i'm not sure how to deal with that.

What i want is simple one parseXML / parseHTML strategy that works for all usecases.. i want to leave the traversal of the top level structures to the implementer.

So some kind of root element that supports the find api would be the most generic option (with the problem of DOMParser and cheerio/jquery handling this differently). just not really sure what to do? you have opinions on this?

**Comment by obuchtala** [comment]
DOMParser and $ are just completely different.
If you want you can wrap the content or deliver the 'root' element: in browser native 'body', in cheerio 'root' and in jQuery not possible without creating a custom wrapper.

**Comment by obuchtala** [comment]
Ignoring jQuery for a while I would expect to get a full document when providing a fully specified document, and maybe a root element for partial HTML/XML content.

**Comment by michael** [comment]
``` js
'use strict';

/*
  BibItem XML Converter
*/

function BibItemXMLConverter() {
  this.type = 'bib-item';
  this.tagName = 'bib';

  this.import = function(el, node) {
    node.id = el.attr('id') || node.id; // legacy ids
    node.format = 'citeproc';
    node.source = el.text();
  };

  this.export = function(node, el) {
    el.attr('format', 'citeproc')
      .attr('data-id', node.id)
      .text(JSON.stringify(node.data));    
  };
}

module.exports = BibItemXMLConverter;
```

If we do this we can not delegate implementations. E.g. ImageFigureConverter can just call FigureConverter.import and then enhance the object with additional stuff. Since this could be useful anywhere it would be bad to hide the import implementations within this.import. I mean I could create an instance and then use it but that's also not very tasty.

Actually I tend to stick with simple function collection we had before. It's has the least overhead and we can combine this functions easily.

``` js
import: function(el, node) {
  FigureXMLConverter.import(el, node);
  // do some more.
  node.src = el.find('img').attr('src');
}
```

I think it's okay to use UpperCase names for modules. What do you think?

**Comment by obuchtala** [comment]
I am fine with it :)

**Comment by obuchtala** [comment]
It's like inline defining a class with static props and functions ;)
To have a reason for upper-cases ;)

**Comment by michael** [comment]
incredible what objects can do ;)

**Comment by michael** [comment]
Done.
