### ISSUE TITLE
Component: didUpdate / willUpdate lifecycle hooks

### ISSUE THREAD

**Issue by michael** [substance/substance#26]
I wonder if we should introduce a generic lifecycle hook analog to React's `componentDidUpdate`. Currently we expose `willUpdateState` and `didUpdateState`. However, that way we need to listen explicitly to either `didUpdateState` and `didReceive` props. I like that it's more explicit, but in many cases you just want to do something whenever the component has updated, and you don't care whether a state update or props update was happening.

What I found convenient in React was that `componentWillUpdate` gives you both, nextProps and nextState. We could do the same.

@oliver---- thoughts?

**Comment by obuchtala** [comment]
IMO, it is important having the hook for props change, as setProps is the API called by parent, i.e. outside the component. setState is something that should used internally by a component.
Definitely we should think about consolidation, but at the same question if what React does is really good or necessary.

**Comment by michael** [comment]
Absolutely. I was bringing it up because I know situations where you for instance embed a 3rd party widget that you just just want to reinject each time time props or state changes. With the current API would need to cover three cases:

``` js
didMount: function() { this.updateWidget(); }
didReceiveProps: function() { this.updateWidget(); }
didUpdateState: function() { this.updateWidget(); }
```

this could be reduced to two calls. Or what could maybe also be useful is just a `didRender` hook, which is called in all 3 situations.

**Comment by michael** [comment]
It's definitely in category sugar, but I think it could simplify especially leaf-ish components which are implemented in a dumb, 'i don't care just rerender everything' way.

**Comment by obuchtala** [comment]
Yeah, maybe adding didRender as extra hook...

didMount is important to know when to do DOM relevant stuff (e.g., think of MathJax)
didReceiveProps is useful to derive custom data from the props.
Maybe we don't need didUpdateState...

**Comment by michael** [comment]
Yeh, MathJax is a great example. If I had this didRender API I would implement a MathComponent using it instead of didMount saying 'whenever you gor rendered/rerendered' i call `doTheMathThing()`. This would be a default usage pattern which would work for many cases. When i want to have full control and to preserve an instance, i use the didMount, didReceiveProps etc. stuff.

**Comment by obuchtala** [comment]
Not exactly what I meant. For certain MathJax things you need to know that you are in the DOM as opposed to be just rendered.

**Comment by michael** [comment]
Mhh.. that's essential yes. The virtual render is not of interest for the user I think, so when I proposed didRender I meant after it has rendered Into the DOM. Maybe didUpdateDOM or something is a better name.

I would not drop the didUpdateState hook because it let's you deal with exactly that case.

**Comment by michael** [comment]
What we should think about is if we should provide an API to break out of the rerender (virtual+inject changes) mechanism. E.g. Maybe i want to watch willUpdateState look into the new state, and if some conditions are fulfilled, just attach an active class to a child element instead of doing the full rerender thing. That's something we missed in React right?

We have this possibility of incrementally adding classes but that only works for the top level element of a Component not for sub elements? Is that correct?

**Comment by obuchtala** [comment]
You can call it sub-components too. You would need a ref to it.

**Comment by obuchtala** [comment]
I think we should collect some more use-cases. I have the feeling that calling didRender only when isMounted is a restriction. I rather would call didRender after each render be it in or out of DOM. And provide didMount for things that really need DOM to be there.
Still didMount and willUnmount is useful for regristration of listeners and de-registration.

**Comment by michael** [comment]
OK. But apart from that does that concept of intercepting the rendering flow make sense in your eyes? 

Like instead having a `shouldUpdate` hook (React) that cancels the rerendering, but instead you could do that in willUpdateState and do some manual incremental things and return false to indicate that no component rerender should happen.

**Comment by michael** [comment]
Yep didMount willUnmount is essential for handler registration/deregistration!

**Comment by obuchtala** [comment]
ATM this would be done by shouldRerender(). There you could look into the new state or props, update incrementally and suppress the usual rerender by returning false. Don't know if this is convenient enough? Just feels strange to have so many ways to intercept. Alternatively we could change Component.rerender() to Component.rerender(oldState, oldProps) which could be customized and call super if desired.
