### ISSUE TITLE
Inherited components and css styles.

### ISSUE THREAD

**Issue by michael** [substance/substance#261]
We need to agree on a convention on how we deal with inheritance in component styles. E.g. there's the abstract `ui/Panel` that has some styles in `styles/components/_panel.scss`. TocPanel derives from Panel and introduces some more styles.

I don't want to use SASS magic, because we end up with more complex styles and also the sourcemaps are making problems for this `%abstractstyle` definitions.

My suggestion would be that we provide two class names on the root element of the TocPanel:

`addClass('sc-panel sc-toc-panel')` and reuse the 'abstract' styles that way. What do you think?

**Comment by obuchtala** [comment]
I agree, if the other approach is causing troubles.

**Comment by michael** [comment]
ok i will try to make this consistent for the styles we have.

**Comment by michael** [comment]
Good here.
