### ISSUE TITLE
Use $variables in scss

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#263]
ATM there is almost no use of variables, instead there a lot of hard-coded constants, such as `padding: 20px`.

On the one hand, this is sub-optimal, as there is no consistent way to change this without touching many files. On the other hand, from my own experience, this move helps to better understand, and refine such variables, bringing a concept into it.

**Comment by michael** [comment]
Yeah there's a lot to do here. Just wanted to get the naming right as a first step. It needs some thinking of what variables to introduce.. I need to do some typography research. It's on for beta 3.

**Comment by obuchtala** [comment]
Much better already. Looks like an ongoing chore. Closing.
