### ISSUE TITLE
Use Class.extend instead of oo.inherit

### ISSUE THREAD

**Issue by michael** [substance/substance#265]
Just writing the new Subscript command and tool without extend. 

``` js
'use strict';

var AnnotationCommand = require('../../ui/AnnotationCommand');
var oo = require('../../util/oo');

function SubscriptCommand() {
  AnnotationCommand.apply(this, arguments);
}

SubscriptCommand.static = {
  name: 'subscript',
  annotationType: 'subscript' 
};

oo.inherit(SubscriptCommand, AnnotationCommand);

module.exports = SubscriptCommand;
```

It gets a bit of overhead... vs:

``` js
'use strict';

var AnnotationTool = require('../../ui/AnnotationTool');

var EmphasisTool = AnnotationTool.extend({
  static: {
    name: 'emphasis',
    command: 'emphasis'
  }
});

module.exports = EmphasisTool;
```

Still in for getting rid of extend but just wondering if there's any other option to write less in such cases.

**Comment by obuchtala** [comment]
If you want we can leave the extend API. But you also need to see its disadvantages.
Writing it shorter in functional way is not possible. The functional way is just closer to how it would be in ES6.

```
MyClass.static = {}
```

is dangerous. There you are killing inheritance.

**Comment by obuchtala** [comment]
In the above case I would rather advocate the following version:

``` js
'use strict';

var AnnotationTool = require('../../ui/AnnotationTool');

var EmphasisTool = AnnotationTool.extend();

EmphasisTool.static.name  = 'emphasis';

EmphasisTool.static.command = 'emphasis';

module.exports = EmphasisTool;
```

**Comment by obuchtala** [comment]
The correct class version would look like:

``` js
'use strict';

var AnnotationCommand = require('../../ui/AnnotationCommand');
var oo = require('../../util/oo');

function SubscriptCommand() {
  AnnotationCommand.apply(this, arguments);
}
oo.inherit(SubscriptCommand, AnnotationCommand);

SubscriptCommand.static.name = 'subscript';

SubscriptCommand.static.annotationType = 'subscript';

module.exports = SubscriptCommand;
```

**Comment by obuchtala** [comment]
And of course we can decide to keep the extend API. We just need make sure that this is also ES6 compatible.

**Comment by obuchtala** [comment]
As soon you have a prototype I would rather prefer the functional version.
And for core implementations, too, then we have a better situation in the debugger.

**Comment by jacwright** [comment]
Why use `MyClass.static.staticProperty = x` instead of `MyClass.staticProperty = x`?. Is it so you can use the `name` property?

The main downside to a generic `Class.extend(childProto)` method is you lose the class names. You can overcome this by changing the signature to `Class.extend(constructor, childProto)` and still get the benefits of static inheritance and readability without losing debug-ability.

``` js
var AnnotationCommand = require('../../ui/AnnotationCommand');

function SubscriptCommand() {
  AnnotationCommand.apply(this, arguments);
}

AnnotationCommand.extend(SubscriptCommand, {
  static: {
    commandName: 'subscript', // name can't be overwritten on Function
    annotationType: 'subscript'
  }
});
module.exports = SubscriptCommand;
```

I've put up some code you can see here: https://github.com/jacwright/class.extend

**Comment by obuchtala** [comment]
Thanks @jacwright,

I will take a closer look at your implementation. Will give feedback after some experimenting.

**Comment by obuchtala** [comment]
@jacwright your suggestion is actually an interesting replacement of 'util/oo.inherit'

However, with our current 'extend' implementation, we like how simple it is to use, e.g. something like:

``` js
var MyClass = ParentClass.extend({
 ...
};
```

without need to define a function.
Thus, I suppose your suggestion is not convenient enough for our tiny classes where boiler-plate is so annoying.

E.g.,

``` js
var PropertyAnnotation = require('model/PropertyAnnotation');

var Strong = PropertyAnnotation.extend();
Strong.static.name = 'strong';

module.exports = Strong;
```

In these cases we don't have a class name, unfortunately.

That said, your suggestion still brings me to the idea to make `oo.inherit` simpler.
And your approach can even be simplified, as `this` is bound to the constructor function in static functions.

``` js
'use strict';

function Parent() {
};
Parent.extend = function(ChildClass) {
  // do the class inherting stuff here
  console.log(ChildClass.name, 'extends', this.name);
};

function Child() {
  // would be nice to have
  // Child.super.apply(this, arguments);
};

Parent.extend(Child);
```

This way we could get rid of all our `oo.inherit` statements, plus using the same pattern everywhere `Parent.extend(Child, ...protos)`
@michael ^^

I will play around with this idea and post my findings here.

**Comment by obuchtala** [comment]
@jacwright Your approach treating statics is closer to what static props will be in ES6, syntactically. From a technical point it is different as they don't go into their own scope, and thus, e.g. 'name' is not allowed as a static variable, as it is a protected constructor property. In ES6 it would be valid to have

``` js
  static get name() {}
```

Also, if you don't consider them as final static, dynamic changes to static props would not be visible in the Child classes, if I understand right.

```
Parent.foo = "foo";
Parent.extend(Child);
Parent.foo = "bar"
Child.foo -> "foo"
```

**Comment by obuchtala** [comment]
That is the reason for why we are using MyClass.static as a scope for static properties, which get the parent's static scope hooked up as prototype.

**Comment by jacwright** [comment]
Ah, that makes sense. I've only used static inheritance for static functions like `Person.findById(123)` and so haven't run into some of these issues.

Here is an updated version of class.extend https://gist.github.com/jacwright/e9530821aa8c3e237646 that supports supplying a constructor or not and uses a `static` property. Something more along these lines could work for both `oo.inherit` and `extend`? We could add the mixins back if that is something needed.

**Comment by jacwright** [comment]
The version in the gist above would support

``` js
var PropertyAnnotation = require('model/PropertyAnnotation');

var Strong = PropertyAnnotation.extend();
Strong.static.name = 'strong';

module.exports = Strong;
```

or even

``` js
var Strong = PropertyAnnotation.extend({
  static: { name: 'strong' }
});
```

while still supporting

``` js
function Strong() {
  // do something in constructor
}
PropertyAnnotation.extend(Strong);
Strong.static.name = 'strong';
```

If you don't care for a named constructor it would be a simple matter to support:

``` js
var Strong = PropertyAnnotation.extend({
  static: { name: 'strong' },
  constructor: function() {
    // init vars and other constructory things
  }
});
```

**Comment by obuchtala** [comment]
Everything changed. Class.extend is now so nice that it can replace oo.inherit.
The easiest way to migrate:

```
oo.inherit(ParentClass, ChildClass)
```

->

```
ParentClass.extend(ChildClass)
```

There are some more ways to use Class.extend as you can read in:
https://github.com/substance/substance/blob/master/util/oo.js#L21

**Comment by obuchtala** [comment]
Let's do the transition after more discussion, and not in Beta 2.

**Comment by michael** [comment]
I like it!

**Comment by michael** [comment]
Daniel want to finish this? I'm half-way there: https://github.com/substance/substance/pull/285.

**Comment by michael** [comment]
@Integral let me finish this.. maybe you take over rather #286 if Oli gives green light.

**Comment by obuchtala** [comment]
:green_apple:

**Comment by michael** [comment]
:tea:

**Comment by obuchtala** [comment]
:green_heart:

**Comment by michael** [comment]
🐢

**Comment by michael** [comment]
Done.
