### ISSUE TITLE
Provide changelog

### ISSUE THREAD

**Issue by michael** [substance/substance#277]
Should we provide a CHANGELOG file to state what is new since beta1?

**Comment by obuchtala** [comment]
In general we should start this at some point. Don't know if we have enough time for this right now. We also could start it after beta 2.

**Comment by michael** [comment]
I will just kick it off without being too specific about the changes.

**Beta 2:**
- Simplified Node API: Props are now stored on the node directly
- New source directory and file layout optimized for deep-requiring individual classes
- New DOMElement API for interacting with DOM elements
- Improved Converter API: Now independent from the Article class
- Overhauled API for Tools: Logic now lives in Command implementations that are independent from the UI
- Editors are now Components implementing the Surface API
- CSS overhaul: improved modularity, prefixing to avoid collisions
- New predefined node types: Embed, Superscript, Subscript, Code.
- Removed FormEditor interface in favour of more fine-grained control using new TextPropertyEditor component
- API docs provided via new Substance DocumentationReader

You have anything to add?

**Comment by michael** [comment]
Lives in CHANGELOG.md now. Please feel free to add things I missed.
