### ISSUE TITLE
Doc: Describe Array of SomeType

### ISSUE THREAD

**Issue by michael** [substance/substance#280]
What should we use to describe Array of Commands for instance?

`@prop {Array.<ui/SurfaceComand>}` gets rendered like this and is not linked. This is the JSDoc syntax. 

![image](https://cloud.githubusercontent.com/assets/2931/11342736/1c9266ea-9209-11e5-891c-ded25941737d.png)

Should we follow this syntax and fix the linking at some point or should we work towards a more compact `@prop [ui/SurfaceCommand]` syntax?  (currently throws a parser error)

**Comment by michael** [comment]
This syntax is also understood:

``` js
/**
  @prop {Object[]} textTypes array of textType definition objects
  @prop {ui/SurfaceCommand[]} commands list of command classes to be available
*/
```

It's translated into Array.<ui/SurfaceCommand>.

**Comment by obuchtala** [comment]
I like `ui/SurfaceCommand[]` most. `[ui/SurfaceCommand]` is confusing, particularly when considering the semantics of `[param]`

**Comment by michael** [comment]
ui/SurfaceCommand[] is good :+1:

**Comment by obuchtala** [comment]
This doesn't get translated to `Array.<..>` anymore.
However CrossLinks not working yet.
