### ISSUE TITLE
Node version

### ISSUE THREAD

**Issue by Integral** [substance/substance#281]
Let's put `engines` directive and specify node version. It makes some sense, for example in context of #210 with old versions of node I ran into `no method 'execSync'`.

**Comment by michael** [comment]
Does >0.10 work?

**Comment by Integral** [comment]
`execSync` was added to node in v0.11

**Comment by michael** [comment]
I think 0.11 or 0.12 is fine.

**Comment by Integral** [comment]
yep, thanks!

**Comment by michael** [comment]
I covered this. it's just not merged yet. Closing.
