### ISSUE TITLE
Improved auto-generated docs

### ISSUE THREAD

**Issue by michael** [substance/substance#284]
We actually need a solution to make doc generation work with tags also. like that a subfolder is created for each tag.

http://substance.io/docs --> always has the latest master docs
http://substance.io/beta2 --> shows the beta2 docs (once released)

Is this easy to achieve you think?

**Comment by obuchtala** [comment]
What about pushing it manually to docs/`<tagname>`?

**Comment by Integral** [comment]
Well, it would be easer of course...

**Comment by obuchtala** [comment]
I think for now this would be the most pragmatic choice.

**Comment by michael** [comment]
Yeah let's do that manually...  you are right. Not worth the scripting.

**Comment by michael** [comment]
Just wondering if substance.io/docs should default to master.. or forward to the latest release instead. Maybe we make the auto generation available via substance.io/docs/latest ?

**Comment by obuchtala** [comment]
or `docs/master`?

**Comment by obuchtala** [comment]
ahh... you mean `latest` === latest tag?

**Comment by obuchtala** [comment]
That would mean we would manually edit `docs/index.html`. But this would be ok IMO.

**Comment by michael** [comment]
hmm true latest is confusing... docs/master is better! Let's have everything in folders and maintain the forward manually in index.html.

**Comment by obuchtala** [comment]
:+1:

**Comment by michael** [comment]
@Integral can you set it up so the auto-gen docs push to `master` folder inside the docs repo? And set up the forward.

**Comment by Integral** [comment]
what do you mean by forward? redirect from docs to docs/master?

**Comment by obuchtala** [comment]
yup, I think that's what @michael meant.

**Comment by Integral** [comment]
sorry for bumping commit history a bit... i did some mistakes and now it seems that autogeneration stuck somehow, we have something like async queue there... maybe i'm wrong, we'll see tomorrow with your commits

**Comment by obuchtala** [comment]
what about changing the script to listen to a test branch for a while?
Then we don't depend on commits to master....

**Comment by Integral** [comment]
good idea ;)

**Comment by obuchtala** [comment]
:green_heart:

**Comment by Integral** [comment]
Yes, the queue is not working, so when we have few tasks there it finished first, but not starting next.
@oliver---- why did you use queue.js? Any special reason or ...?

**Comment by obuchtala** [comment]
nope. just thought this would work... but ditch it then...

**Comment by obuchtala** [comment]
Somehow it worked for a while, so I thought it would be ok.

**Comment by Integral** [comment]
I just never use it... Will try other things, actually we need some queue there in case of few commits arrived with different less then 3 minutes.

**Comment by obuchtala** [comment]
:+1:

**Comment by obuchtala** [comment]
(fuck i am tired)

**Comment by Integral** [comment]
Callback didn't fired... Will investigate tomorrow. Good night!

**Comment by obuchtala** [comment]
Sleep well :)

**Comment by Integral** [comment]
U2!

**Comment by michael** [comment]
Guten morgen!

@Integral regarding the master subfolder... could this be done outside of the gulp script also. Like at the place where you push to substance/docs?

People that run npm run doc would not expect to have the docs generated into dist/master.. especially when they are generating docs for a different branch.

**Comment by Integral** [comment]
yes, you're right
I had some thoughts yesterday opposite to this, but today I can't see any problems :)

**Comment by michael** [comment]
OK. Take your time. I will focus on Lens today.

**Comment by Integral** [comment]
Done!

**Comment by michael** [comment]
Bravo! Thanks.

Please open a pull request for future additions. Just so we can have short review of the changes. It's also nice for documenting a pack of changes in one place (the PR).

**Comment by michael** [comment]
You can use a branch on substance directly. We will delete them after merge. E.g. you could have branch `upgrade-dependencies` and when ready for review you open PR.

**Comment by Integral** [comment]
Yes-yes, sorry, I just did this because of lack of important changes... Sorry :)

**Comment by michael** [comment]
No worries!

**Comment by Integral** [comment]
BTW, just FYI, usually when you run npm install it will install both production and dev dependencies. However if you want to install dev dependencies in heroku you need to run `heroku config:set NPM_CONFIG_PRODUCTION=false`
