### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by michael** [substance/substance#286]
Bump dependencies to latest versions. E.g. lodash, cheerio, jquery but also dev dependencies and check that everything runs smoothly still.

I think we should specify explicit versions in package json (no >= stuff) and bump manually from time to time.. just so users don't have bad surprises.

@oliver---- agree? @Integral want to take that one over?

**Comment by obuchtala** [comment]
:+1:

**Comment by Integral** [comment]
Thank you!

**Comment by Integral** [comment]
ok
@michael what should i do here in terms of verefication? run tests and check examples?

**Comment by michael** [comment]
Yep! tests, examples, and substance/lens#dev should still run. Most importantly we need to test fresh npm install if everything goes write. We will all try once you are ready.

**Comment by Integral** [comment]
Ok!

**Comment by Integral** [comment]
@michael give the next one while you are testing!
