### ISSUE TITLE
Text cursor movement by tap fails on iPad

### ISSUE THREAD

**Issue by solsson** [substance/substance#29]
As guessed in #28 Substance isn't quite ready for mobile yet.

Current Substance demos render on iPad and it is possible to type, but only at the original text cursor position. You can tap somewhere else in the text and the text cursor will move, but you still type at the original location.

On iPhone the demos have issues with the small screen and it is hard to get to typing.

On an Android 4.4 phone with 1020p screen, both portrait and landscape, it is only the credits footer that renders while the rest of the screen is grey.

**Comment by solsson** [comment]
I should add that I consider this issue to be about the text cursor only, while I described rendering behaviour only as background. The replacement of contenteditable with a custom technique benefits from early validation.

It is interesting that iPad shows a B/I/U styling button when text is selected, so it must have some understanding of the editable concept. It fails to change styling though.

**Comment by obuchtala** [comment]
Hey @solsson Thanks for this investigation! We will try to address this soon.

As you have seen, we do not handle touch events (as opposed to mouse events) correctly. Then you see the selection not changing internally, and continueing typing will show changes at the old position.
The other thing you detected are natively implemented ContentEditable features, such as those annotations, but also things like spell-checking etc. We pretty much know how to address this, but just haven't done it yet.

**Comment by solsson** [comment]
On Windows 8 touch it works nicely with all browsers, though with visual differences. Firefox just sets the cursor, IE 11 sets the cursor and displays a black circle underneath, Chrome sets the cursor and displays a blue drop shape and a small menu akin to iPad's that gives you the option to paste or expand a context menu. I guess this is by design for each browser and all good. With all of them you get your typing where the cursor is.
