### ISSUE TITLE
PropertySelection: difference between isInsideOf and contains methods

### ISSUE THREAD

**Issue by Integral** [substance/substance#290]
https://github.com/substance/substance/blob/5d4ba794f6af459f887e7df27e2f977f16e5c983/model/PropertySelection.js#L140
https://github.com/substance/substance/blob/5d4ba794f6af459f887e7df27e2f977f16e5c983/model/PropertySelection.js#L157
they looks like the same... that's strange...

**Comment by Integral** [comment]
or is it because of ContainerAnnotations methods?

**Comment by michael** [comment]
It's not the same.. there's like `<` vs `>`. however this could maybe be improved implementation wise for more code share. Maybe we post an issue for beta3. @oliver---- ?

**Comment by Integral** [comment]
The only difference is `return other.contains(this);` vs `return other.isInsideOf(this);`.
So they refer each other, but it only make sense in case of calling this method inside `ContainerSelection` which has different implementation...

**Comment by obuchtala** [comment]
obviously isInsideOf is the opposite of contains. We could implement one using the other that's true.

**Comment by Integral** [comment]
achhh, now i see, will improve docs, it's not very clear that contains and inside of means in context of current sel

**Comment by Integral** [comment]
no, i already wrote it in a good way ;)
