### ISSUE TITLE
Implement innerHTML / outerHTML with strings on DOMELement

### ISSUE THREAD

**Issue by michael** [substance/substance#293]
There are problematic cases where we don't get valid XML.

`document.createElement('img').outerHTML` => `<img>` but should be `<img></img>`

**Comment by obuchtala** [comment]
We found out that the browser based implementation works when we use `doc.createElement()` on a document which was created using XML parser.

We decided to get rid of static `DOMElement.createElement()` and use a contextualized version instead.
This should be necessary only in Exporter implementations where we can provide `converter.createElement` delegating to the target document instance.

**Comment by michael** [comment]
We also need the createElement in the ClipboardImporter. See #391

**Comment by obuchtala** [comment]
Now we use native DOMParsers properly and do not need a string based serializer anymore.
