### ISSUE TITLE
Better API for incremental updates

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#299]
Currently we use doc.update() which has an ugly signature.

Would be better to provide a type specific API

```
    var Arr = require('substance/model/Array')
    Arr.insert(tx, ['body', 'nodes'], 3, 'p1');
    Arr.delete(tx, ['body', 'nodes'], 3);

    var Str = require('substance/model/String')
    Str.insert(tx, ['a', 'b'], 3,  "ef");
    Str.delete(tx, ['a', 'b'], 3, 4);
```

**Comment by Integral** [comment]
Can I take this?

**Comment by obuchtala** [comment]
It's not high prio.. but if you like, why not :)

**Comment by Integral** [comment]
@oliver---- what we should do with indexing? Currently we are passing change object to queue... Probably we should also drop support off update type of index... right?

**Comment by obuchtala** [comment]
No, for now it's just about the Document API. Internally we need the incremental API somehow. The API in index is ok.

**Comment by Integral** [comment]
so we still need to call data's this.update?

**Comment by obuchtala** [comment]
internally we need it somehow, otherwise we don't have a way to do incremental updates.
So the pragmatic approach now would be, to create a more convenient API, which just uses the old implementation, making it 'private'.

**Comment by Integral** [comment]
ok, we would just translate Arr.insert(tx, path, offset, val) to old update(path, diff), right?

**Comment by obuchtala** [comment]
As a first step this would be the easiest way, yes.

**Comment by Integral** [comment]
Like this? https://github.com/substance/substance/blob/incremental-update/model/Array.js

**Comment by obuchtala** [comment]
Hmm. I think tx should take care of storing the op itself.

I think it would be enough to just do:

```
  this.insert = function(tx, path, offset, value) {
    if (isArray(oldValue)) {
      var diff = { insert: { offset: offset, value: value } }
      return tx.update(path, diff);
    } else {
      throw new Error('Value type is not supported:', JSON.stringify(value));
    }
  }
```

**Comment by Integral** [comment]
ok, thanks

**Comment by obuchtala** [comment]
ah ... my code is wrong actually. you don't have oldValue at first. You would need to get the value first...

**Comment by obuchtala** [comment]
After the first iteration we will deprecate `.update` and finally try to get rid of it.

**Comment by Integral** [comment]
Don't worry :)

**Comment by Integral** [comment]
@oliver---- it's done someway... (5bee867f5dd627215992d0201e2236ab41447c76)
But do we really need to make class here? I don't understand why...
