### ISSUE TITLE
Reorganise sass styles

### ISSUE THREAD

**Issue by michael** [substance/substance#3]
We need to remove site-specific layout bits from base.css and provide a separate module. The reason is that people may want to use the Substance HTML editor but within their own site style. So they just need styles for dropdown etc. but not our font etc. and base styles for paragraphs etc.

This may take a bit of time to get right, and it's not so relevant during the HTML Editor beta phases. But it will become very import when people start embedding Substances on their sites.

**Comment by Integral** [comment]
Maybe we should leave basics? You can always override defaults...

**Comment by michael** [comment]
Done.
