### ISSUE TITLE
Read-only components

### ISSUE THREAD

**Issue by mwtorkowski** [substance/substance#30]
Would it be feasible to create a substance component, e.g. string of text that is read-only, but still behaves like actual text (so it can be inserted in the middle of a paragraph, and act like any other string there - except it cannot be changed)?

**Comment by obuchtala** [comment]
This is actually easy by just rendering such a component with contenteditable=false.
FWIW, every node type can have or actually usually has its own view implementation.

**Comment by obuchtala** [comment]
Beyond that, editing behavior like when you press backspace at the beginning of the next paragraph which could be implemented to merge the content into the previous node, can be controlled for every node type, in order to prevent this for such a read-only node.

**Comment by michael** [comment]
You can also include buttons and interactive elements into your components, where some area is editable and another is for interacting with the component.

The todo component in our notepad is such a case:
http://substance.io/demos/notepad/

See implementation here: 
https://github.com/substance/demos/blob/master/notepad/todo_component.js

**Comment by michael** [comment]
@mwtorkowski Closing this. Please reopen if unhappy with the answers. :)
