### ISSUE TITLE
surface.el.focus() causes a surface scroll when the surface is currently blurred

### ISSUE THREAD

**Issue by michael** [substance/substance#301]
Reproduce in Lens:
- select some text
- click somewhere into the toolbar to natively blur the surface
- toggle an annotation

This triggers a Surface#setSelection which finally calls focus(), which triggers the unwanted surface scroll. 

https://github.com/substance/substance/blob/64a75988e207b03a6e2375d98ffbbac79a42d4c7/ui/Surface.js#L680-L687

Since this call to focus is only needed for FF maybe we should guard that so it doesn't get called for Chrome. I will now check if the scroll issue also exists for FF.

**Comment by michael** [comment]
FF does not do the ugly jump, so with a browser conditional we would be good here...

**Comment by obuchtala** [comment]
Will take a look.

**Comment by obuchtala** [comment]
Yep that solved it.

**Comment by michael** [comment]
Nice!

When I did the FF tested I messed around in FF a bit and managed to break the editing.. but i couldn't reproduce it.. it's like a rapid typing concurrency thing supposedly.
