### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by maacl** [substance/substance#316]
The tutorial at:

```
https://github.com/substance/examples/tree/master/notepad
```

appears incomplete. I would like to help create this, as it appears to be a cool way to learn substance. Is there a way I can help out? My goal with learning substance would be to make a substance based editor focused on legal documents. I know a little Javascript, but I am much more comfortable with Clojurre/ClojureScript so my goal would be to access substance from ClojureScript, but I am happy to do the tutorial in straight Javascript.

**Comment by michael** [comment]
Hey it would be great if you could help out here. :) I had a more comprehensive tutorial for the Nodepad example but it's not updated yet. It's still in the README.md file I just commented it out.

Maybe you can work on that file and send a pull request: https://raw.githubusercontent.com/substance/examples/master/notepad/README.md

For the official tutorial it should be straight Javascript, but if you want to write up something from the perspective of ClosureScript we're happy to link to it!

Thanks a lot!

**Comment by maacl** [comment]
Michael,

Great stuff. I will try to work a bit on this over the weekend.

**Comment by maacl** [comment]
Michael,

I have not forgotten the tutorial, just been unexpectedly busy.

How to look at it over Christmas.

Martin
