### ISSUE TITLE
Select All by Keyboard Shortcuts Results in Unexpected Behaviours

### ISSUE THREAD

**Issue by netsgnut** [substance/substance#319]
As far as I know Substance wraps selections in various browsers, however it seems the use of keyboard shortcuts for Select All (Ctrl-A/Cmd-A/Meta-A) results in various unexpected behaviours. For example in Firefox/Gecko, pressing Ctrl-A won't result in highlighting of any of the text. However in Chrome/Webkit, pressing Ctrl-A highlights all of the text, but any further keystrokes append text after one of the paragraphs, instead of removing all text nodes.

Edit: Highlighting using mouse is fine either case.

**Comment by netsgnut** [comment]
Also as a side note, it seems currently Firefox/Gecko has quite a number of strange behaviors too. May I ask if an official support on the latest version of Firefox is anticipated? Thanks.

**Comment by obuchtala** [comment]
Oh! Thanks for reporting.

Yes, Firefox is totally on our list. We are actually running our test-suites against Chrome and FF. However, we don't know yet how to test top-level native interactions, i.e. doing a real 'Select All', not just emulating it. 

So these are regressions. We will try to fix it ASAP.

**Comment by obuchtala** [comment]
It seems that we have a regression which prevents receiving any keyboard events in FF.
Investigating.

Edit: ... and then native ContentEditable takes over leading to very weird behavior.

**Comment by obuchtala** [comment]
Fixed this via e3d61738e223f3019d3d0347a36bd204ca526a66.

Still I want to investigate if we can improve the situation regarding test-suite.

**Comment by obuchtala** [comment]
@michael shall we roll this out for beta 2?

**Comment by netsgnut** [comment]
Yes I can totally understand that - testing browser default interactions is tricky. I personally am interested in knowing if there are existing solutions out there for that, too.

Although it still couldn't replace an automated test, I think we might want to dogfood more on the intended browsers - often it feels like being a second-class using Firefox ;)

**Comment by obuchtala** [comment]
@michael can u check this on OSX?
I check my Windows and linux browsers.

**Comment by obuchtala** [comment]
Working under Windows Chrome, FF, and Edge.

**Comment by michael** [comment]
Works on OSX Chrome/Safari/FF. Tested in Lens and pressed cmd+a in title editor / abstract editor and body editor.

**Comment by obuchtala** [comment]
Also under Ubuntu Chrome / FF no probs.

**Comment by netsgnut** [comment]
Tested substance/examples@4fd41f0ab27b57ae0f5efaaea764969a1b6d175e on [Elementary OS](http://elementary.io/)(an Ubuntu fork). Firefox and Chromium work well (thanks!). [Midori](midori-browser.org/) (the default browser that runs on Webkit and looks like Safari) doesn't, but I guess we can probably leave that one out, though?

Edit: The Midori browser identifies itself with `Mozilla/5.0 (X11; Linux) AppleWebKit/538.15 (KHTML, like Gecko) Chrome/18.0.1025.133 Safari/538.15 Midori/0.5`
