### ISSUE TITLE
Question: Is Component.prototype.mount in use?

### ISSUE THREAD

**Issue by michael** [substance/substance#32]
Is `Component.prototype.mount` in use? It seems not to be called anywhere.

``` js
  this.mount = function($el) {
    this._render(this.render());
    $el.append(this.$el);
    // trigger didMount automatically if the given element is already in the DOM
    if (_isInDocument($el[0])) {
      this.triggerDidMount();
    }
    return this;
  };
```

Also I don't understand why we check for for _isInDocument and then call triggerDidMount. Shouldn't it be the other way: if not yet mounted we call triggerDidMount (as it's the first time).

**Comment by michael** [comment]
Oh I had some basic misunderstanding. You check in various places if the comp has been mounted and if yes, you call triggerDidMount() explicitly. However that open the door for doubleDidMounts unless we bring into place that **mounted** state.

I'd rather get away with this **mounted state** and formalize it as a property. I would change the implementation so that I just call triggerDidMount in various places without the guard and do the checking in that method explicitly. So essentially whenever it has not been mounted before, if will call didMount.

I'm just not sure if then we cover cases where we render some subDOMS that are not attached to the document yet. What will happen then is that we call the didMount hook (though it's not really in the document) only in an unconnected subtree.

**Comment by obuchtala** [comment]
I wanted to have the notion of when a component is actually in the window document.
I think we should rethink this, as in the most cases we are more interested in didRender. Still we need to be able to communicate when a tree has been added to the window document.
I suggest to move away from the term 'mounting' as it is confusing. What should be the difference between rendering and mounting, when not window.document....

**Comment by obuchtala** [comment]
ATM, I can only think of 2 use-cases from our experience:
1. MathJax
2. window.document event handlers (we needed this sometimes)

**Comment by michael** [comment]
yep no i guess we can't give up on this.. but true we should avoid using it in all cases where the local context suffices.

**Comment by michael** [comment]
Anyway.. i get a feeling that we need this **mounted** variable.. which actually denotes that "didMount" has been called already for this component.

**Comment by michael** [comment]
So in the place where we call didMount two properties must hold: 
- comp.$el has document as a parent
- didMount has not been called already

**Comment by michael** [comment]
Some interesting details from React's [documentation](https://facebook.github.io/react/docs/component-specs.html#mounting-componentdidmount): 
- "The componentDidMount() method of child components is invoked before that of parent "components.

In our case parents get triggered first right? Any negative implications?

**Comment by obuchtala** [comment]
Don't think that it would have a strong impact. Everything should be rendered already. It would only have an impact on the order of global DOM event handlers.

**Comment by michael** [comment]
OK. I'll work on a bit cleaner solution, I push in a branch when ready.

**Comment by michael** [comment]
Again regarding Component.prototype.mount. You made an example where you use the mount instance method:

``` js
var frag = document.createDocumentFragment();
var component = new MyComponent();
component.mount(frag);
...
$('body').append(frag);
component.triggerDidMount();
```

You want to allow to do things low level, like instantiating components using new, right? What are use-cases where this is handy? Just for understanding... 

It would also be possible like this, when you mount it to an element that is not (yet) in the DOM.

``` js
var comp = Component.mount($$(MyComponent), frag);
$('body').append(frag);
component.triggerDidMount();
```

**Comment by oliver----** [comment]
Not so important... I started with the prototype version. Later the 
static version... now we have both.

Michael Aufreiter schrieb:
>
> Again regarding Component.prototype.mount. You made an example where 
> you use the mount instance method:
>
> var  frag=  document.createDocumentFragment();
> var  component=  new  MyComponent();
> component.mount(frag);
> ...
> $('body').append(frag);
> component.triggerDidMount();
>
> You want to allow to do things low level, like instantiating 
> components using new, right? What are use-cases where this is handy? 
> Just for understanding...
>
> It would also be possible like this, when you mount it to an element 
> that is not (yet) in the DOM.
>
> var  comp=  Component.mount($$(MyComponent), frag);
> $('body').append(frag);
> component.triggerDidMount();
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/substance/substance/issues/32#issuecomment-139344565>.
>

-- 
Sent with Postbox <http://www.getpostbox.com>

**Comment by obuchtala** [comment]
If you want to do offscreen rendering using document fragments the didMount mechanism would not work and you would need to trigger didMount manually, when actually adding to DOM.

**Comment by michael** [comment]
Yep, that I understand. So i keep triggerDidMount a public API. Let me try to get rid of the prototype version of render.

I mean to support creating instances using new (which i find quite nice) we could also let the Component.mount method accept either a $$ virtual element or a real component instance. That would not be tooo magic ha? :)

Also, I think we should let mount accept a DOM element too. Currently it expects a jQuery element.

**Comment by obuchtala** [comment]
But keep in mind, that the component ctor is not so nice to use (parent, params)...

**Comment by obuchtala** [comment]
Yes... the jquery API is for cheerio, and of course convenience... but you mean additionally we should do that, right?

**Comment by obuchtala** [comment]
Let's say you do some refactorings and let me take a look :)

**Comment by michael** [comment]
Yep, just check wrap it in a $ and we should be save.

Component ctor for dudes that want the bear metal, i like that we have that and React doesn't. :)

**Comment by michael** [comment]
i think this is nice for a small tutorial also to understand what happens behind the curtain. that there's actually no big magic. just some calls with parent etc.
