### ISSUE TITLE
Test native ContentEditable manipulations.

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#320]
Mostly, we try to suppress native CE features, such as when the user types text. Some of the actions, such as copy n paste, can be triggered using `document.execCommand`.

**Comment by obuchtala** [comment]
Maybe we can use 

```
new KeyboardEvent(typeArg, KeyboardEventInit);
```

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/KeyboardEvent

**Comment by jacwright** [comment]
You suppress when the user types text? Don't you lose tons of localization features provided by the browser by suppressing  typing? Or have I misunderstood.

**Comment by obuchtala** [comment]
Actually we redirect the change and reading it leveraging the native impl. A bit of a dance..
You are right, otherwise it would be crazy.

**Comment by obuchtala** [comment]
In Safari/Chrome it is easier... there you have textInput events.

**Comment by obuchtala** [comment]
Just saw that even for IE and FF the solution isn't that bad anymore, as the regular key events are much better there.
