### ISSUE TITLE
Should we rename 'document:changed' -> 'transaction:applied'?

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#324]
Last night I had the thought, that `document:changed` is simply not accurate.
@michael What do u think about `transaction:applied`, in accordance to `operation:applied`?

**Comment by michael** [comment]
Sounds good to me.. transaction:applied makes better clear the context. would `transaction:applied` be equal to current `document:changed` ?

**Comment by obuchtala** [comment]
Exactly, because that change you receive currently is actually the result of the transaction. Maybe only that undoing/redoing is replaying 'transactions', and exchanging 'transactions' between clients... but maybe that is fine, too?

**Comment by obuchtala** [comment]
Dropping this, as with the new implementation of DocumentSessions you also get a DocumentChange event for primitive changes such as doc.create().

**Comment by obuchtala** [comment]
DocumentSessions are part of PR #337
