### ISSUE TITLE
Better browserify errors

### ISSUE THREAD

**Issue by michael** [substance/substance#325]
We currently use this code for our ad-hoc browserify bundling:

``` js
app.get('/app.js', function (req, res, next) {
  // var startTime = Date.now();
  browserify({ debug: true, cache: false })
    .add(path.join(__dirname, "app", "app.js"))
    .bundle()
    .on('error', function(err){
      console.error(err.message);
      res.send('console.log("'+err.message+'");');
    })
    .pipe(res);
});
```

However, this gives us crappy errors e.g. when a require path is wrong:

```
Cannot find module 'substance/ui/ScrollPane' from '/Users/michael/projects/substance/lens'
```

It only tells us the folder where the problem happened but not the actual file.

@Integral maybe there is a way to find out what the actual file was that did the bad require. Maybe you have some time to investigate this.

**Comment by Integral** [comment]
@michael i think it is not possible without source maps...

**Comment by Integral** [comment]
and i'm not sure that we want to introduce source maps...

**Comment by obuchtala** [comment]
I think we already have source maps (`debug: true`).
Just the browserify error is unspecific. Maybe there is a solution out there?

**Comment by obuchtala** [comment]
Not solving this issue, but just as a reference what others do about errors.

http://latviancoder.com/story/error-handling-browserify-gulp
https://gist.github.com/apfelbox/b2d5ee9fe32e5b42adb2

**Comment by Integral** [comment]
i saw this, but it's about gulp...

**Comment by obuchtala** [comment]
I fear, that is not browserify's fault:

https://github.com/substack/node-resolve/blob/5cae82fb22cb64d5b72f703c787dc0fd418ed412/lib/sync.js#L17-L33

The implementation uses dirname for the error :(

**Comment by Integral** [comment]
To confirm your fears I could say that in other cases we have normal error trace...

**Comment by obuchtala** [comment]
There is a PR: https://github.com/substack/node-resolve/pull/64

**Comment by obuchtala** [comment]
Maybe it gets fixed soon.

**Comment by Integral** [comment]
Khm... It's there from beginning of year

**Comment by obuchtala** [comment]
For now we could fork browserify and patch together a version with this https://github.com/jmm/node-resolve/commit/4eb424ba952af0c651fcaf14e05395b146c541dc included

**Comment by obuchtala** [comment]
Hmmm.. yes, true :(

**Comment by Integral** [comment]
Do we really need this if it's related only to `Cannot find module` errors?

**Comment by obuchtala** [comment]
That this would be helpful is out of question, because with our 'flat' directories we don't have a clue in which file the failing require is actually. But the question is if we really want to fix it on our own.
And you still can go into the directory and do a `find all` using the failed required path. But needless to say that this is inconvenient, and introducing a bareer for less experienced people.

**Comment by Integral** [comment]
If we don't expect any new things from browserify then we could do it... I see no cons

**Comment by Integral** [comment]
Should I do it?

**Comment by obuchtala** [comment]
If you want, that would be great! :)

Just as a motivation why we brought this up: during migration of Stencila's integration to beta2, we had a lot of require issues, due to file renaming. And we had to look up every error manually.

**Comment by Integral** [comment]
ach, it's not relevant already, grrr... will look into

**Comment by obuchtala** [comment]
hehe ;)

**Comment by Integral** [comment]
Done! Cheers!

**Comment by Integral** [comment]
Before closing this issue... Pls delegate me something outside of docs...
@oliver---- pls take a look at incremental issue, i will then provide test for it, maybe you need another tests?
