### ISSUE TITLE
Notepad application thinks heading is todo item.

### ISSUE THREAD

**Issue by rywall** [substance/substance#332]
To replicate:
1. Go to http://substance.io/
2. Type a word directly after the last todo item.
3. Switch the text from a paragraph to a heading, codeblock, or blockquote.
4. The todo button shows as selected even though the text is not a todo item.

![image](https://cloud.githubusercontent.com/assets/7904/11726131/fe618198-9f31-11e5-9799-ace4217b1776.png)

**Comment by michael** [comment]
Thanks. You are right.. Mistake is in the TodoCommand implementation.

https://github.com/substance/examples/blob/master/notepad/TodoCommand.js#L23-L26

**Comment by michael** [comment]
Fixed. Will be rolled out with the beta 3 release next week.
