### ISSUE TITLE
Update scrollbar on DOM reflow/repaint

### ISSUE THREAD

**Issue by michael** [substance/substance#333]
Currently we update the scrollbar on every document change, however we should aim to make this more generic. The scrollbar should update if any of the DOM inside the scrollPane content has changed.

I' not sure what the best way is to detect this. I thought of making use of the `DOMMutationObserver`. Can it be configured that it also fires when a grand child has been updated?

Any other ideas here?

**Comment by netsgnut** [comment]
I haven't tried that myself, but it seems there is a `subtree` option for the [DOMMutationObserver](https://developer.mozilla.org/en/docs/Web/API/MutationObserver). Could it be something you are looking for?

**Comment by michael** [comment]
Oh that sounds promising. Will try!

**Comment by obuchtala** [comment]
@michael what is the state of this?

**Comment by michael** [comment]
Not done yet, and still not critical. Let's push to Beta 5.
