### ISSUE TITLE
Some refs are lost on subsequent rerenders.

### ISSUE THREAD

**Issue by michael** [substance/substance#335]
Ran into a bug where I want to access this.refs.contentPanel in LensController but it disappears after the first incremental rerender.

Reproduce:
- Check out lens#content-panel-refactor
- Click through several toc items.

Relavant usage code: https://github.com/substance/lens/blob/content-panel-refactor/LensController.js#L47-L50

I suppose we should fix this via #313. @oliver---- can we get this into beta 3 next week? Would fit good into the bugfix scope of beta3.

**Comment by obuchtala** [comment]
This should be fixed in PR #313 now

**Comment by michael** [comment]
Yeh works now!
