### ISSUE TITLE
Styles are broken on substance.io/docs

### ISSUE THREAD

**Issue by michael** [substance/substance#339]
@Integral can you check why this is... when I run docs locally on master everything is fine.

**Comment by Integral** [comment]
khm... looks like it's not a style issue, markup is different...

**Comment by Integral** [comment]
@michael i think the reason is here https://github.com/substance/substance/blob/master/browser.js#L1
there is no index.js, so it fails during gulp building

**Comment by Integral** [comment]
sorry, that was a wrong trace, however I'm not understand what is build task for gulp

**Comment by Integral** [comment]
wooo, fixed by 7b0d773fffea201bba22afa521a46db27439e16e

**Comment by michael** [comment]
Daamnit. This is really annoying. Node+Browserify under OSX just does not complain when you require('ui/PaNeL') or whatever... also git does not recognize a file name change when you just turn a letter upper or lowercase.

**Comment by Integral** [comment]
;)
