### ISSUE TITLE
DOMImporter.annotatedText

### ISSUE THREAD

**Issue by michael** [substance/substance#342]
Provide options as a 3rd argument. E.g. for trimming whitespace. Also add proper documentation.

``` js
node.content = converter.annotatedText(el, [node.id, 'content'], {trimWhitespace: true});
```

**Comment by obuchtala** [comment]
Maybe we should go one step further and make trimWhitespaces:true the default behavior and instead introduce an option to disable trimming in certain situations, such as preformatted text?

**Comment by obuchtala** [comment]
Done.
