### ISSUE TITLE
TOC still shows the wrong element as active

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#347]
This happens under all browser on my PC.

**Comment by michael** [comment]
You mean it's one item off? Or generally broken?

**Comment by obuchtala** [comment]
One off. Some pixels too high on the left side...

**Comment by michael** [comment]
It goes off for me when I zoom in into the page. But with 1:1 ratio it works predictable.

**Comment by obuchtala** [comment]
No zoom configuration works for me.

**Comment by obuchtala** [comment]
Ah you are right 100% works in chrome.

**Comment by obuchtala** [comment]
But not in Edge.

**Comment by obuchtala** [comment]
Works for me with

```
  this.getScrollPosition = function() {
    var scrollableEl = this.getScrollableElement();
    return $(scrollableEl).scrollTop() + 1;
  }
```

**Comment by obuchtala** [comment]
Maybe you should add this 1px where you evaluate this for the active element.

**Comment by michael** [comment]
That would fix it for 99.9% I think... let's try it for a while... I think the problems arise from some float rounding, when we don't have even pixels. Which may happen on zoom or in some browser's offset calculations.

**Comment by obuchtala** [comment]
Even 0.1 works for me... with all zoom factors. I have the feeling that it is really just a numerical residuum... not a big error. Which would be classical in numerical computing...i.e. sometimes the exact discrete value is not a good choice when you are dealing with fractions and limited registers.

**Comment by obuchtala** [comment]
It might even be that 1px is an upper bound for the numerical error (considering a truncate of 0.x).
