### ISSUE TITLE
Hide native scrollbar in FF

### ISSUE THREAD

**Issue by michael** [substance/substance#348]
![image](https://cloud.githubusercontent.com/assets/2931/11880411/da014840-a500-11e5-886c-07da825c90b3.png)

Hopefully there's a better way than overlaying it with a white div (as we solved this for Lens back in the days)

**Comment by obuchtala** [comment]
Is there something helpful? https://support.mozilla.org/en-US/questions/957337

**Comment by obuchtala** [comment]
Found this incredibly hacky solution: http://stackoverflow.com/questions/20997183/how-to-hide-scrollbar-in-mozilla-firefox

**Comment by obuchtala** [comment]
Fixed via 3c72363e4ff72a46153616b4615118ab6118cf5e
