### ISSUE TITLE
key vs. ref and component recycling

### ISSUE THREAD

**Issue by michael** [substance/substance#35]
I found an argument why we should probably support both key and ref. 

A key must only be unique only within the direct parent context, while a ref must be unique within the whole owner component. Thus this is perfectly valid:

``` js
  render: function() {
    return $$('div').append([
      $$('div').key('a').append([
        $$('div').key('a'),
        $$('div').key('b')
      ]),
      $$('div').key('b').append([
        ..
      ])
    ]);
  }
```

But this is not:

``` js
  render: function() {
    return $$('div').append([
      $$('div').ref('a').append([
        $$('div').ref('a'),
        $$('div').ref('b')
      ]),
      $$('div').ref('b').append([

      ])
    ]);
  }
```

Usually we would use a ref for static components, that we know they will be there (e.g. contentPanel, scrollbar, etc.) and keys for comps that are dynamically generated (e.g. for list of content nodes).

I'd like to activate reusing of components whenever there's a key present. So we don't have to add another persistent() marker. That said, I was wondering if the default implementation of shouldRerender should just return true... then we don't have any edge cases where something does not get updated and no costly deep checking by default. whenever you want to stop the hard rerendering (which should in many many cases also be very fast) you implement shouldRerender (which is usually very simple and then we have things totally explicit).

In our case for components that are updated using events we could just do `return false` in the customer shouldRerender, so this component would just say.. 'I manage myself'. In our case ContentPanel would be such an example.

**Comment by michael** [comment]
What's you feeling about these things?

I changed the default shouldRerender to return true always. And implemented a test case that covers various cases of preserving/rerendering.

https://github.com/substance/substance/blob/improve-trigger-did-mount/test/unit/ui/component.test.js#L270

**Comment by obuchtala** [comment]
I think you are right. Let's see how the eager update influences performance. We can optimize later.

**Comment by michael** [comment]
We use `ref` now instead of `key`. Proving a ref automatically turns on incremental rendering.
