### ISSUE TITLE
Model selection does not get updated, after clicking on an existing selection.

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#355]
![issue-355](https://cloud.githubusercontent.com/assets/284099/11889483/eb36f7c4-a549-11e5-866a-7c3659539733.gif)

**Comment by obuchtala** [comment]
Probably a regression.

**Comment by michael** [comment]
I don't see this. Which browser?

**Comment by obuchtala** [comment]
You need to click on the node which you triple-clicked.

**Comment by obuchtala** [comment]
It's actually with every selection, not only tripple clicks..
