### ISSUE TITLE
How to unmount a root component?

### ISSUE THREAD

**Issue by michael** [substance/substance#36]
Once mounted injected, we have no way unmount a root component, or am I missing something?

**Comment by obuchtala** [comment]
Does component.unmount() not work?

**Comment by michael** [comment]
Just found it. I want to test deregistration of event handlers.

**Comment by michael** [comment]
Which seems not to be done in that case. In _updateElement there's the only place:

``` js
    if (!_.isEqual(oldData.handlers, data.handlers)) {
      _.each(oldData.handlers, function(handler, event) {
        $el.off(event);
      });
      _.each(data.handlers, function(handler, event) {
        $el.on(event, handler.bind(scope.owner));
      }, this);
    }
```

**Comment by obuchtala** [comment]
Well, this seems to be a bug.

**Comment by obuchtala** [comment]
On a second thought: I don't think it is necessary to unbind the event handlers. They are part of the rendered element. It should not matter if they are still there after unmount. I would leave them.

**Comment by michael** [comment]
But wouldn't this prevent the component from being garbage collected if there's a handler from that component bound to the element that could potentially survive... I'm not sure i understand this completely. I mean why it does not matter to not call .off().

**Comment by obuchtala** [comment]
No. Why would it. Both, the component and the element are having the same life-time.

**Comment by obuchtala** [comment]
Why should the element survive?

**Comment by michael** [comment]
Mhh.. probably true yes.. and if i keep a reference to the unmounted component or el, it's the user's fault.

**Comment by obuchtala** [comment]
I think so.
