### ISSUE TITLE
markActiveEntry logic makes scrolling in large documents significantly slower

### ISSUE THREAD

**Issue by michael** [substance/substance#367]
Let's see what can be done here to optimise.

One source could be the lookup for each TOC element in the content pane. Also the topOffset calculation could be costly as it now sums up the parents offsets too (in case we use position relative somewhere).

Maybe for now we just want to throttle that markActiveEntry call a bit.

**Comment by michael** [comment]
Tried a few things.. turns out performance is not so bad.. and only feels a bit less responsive on my retina display. However we should optimize the actual implementation. Let's schedule this for beta 4. Now is not the right time.

**Comment by obuchtala** [comment]
Don't know if that is still relevant.
We might face these problems in the Scientist context again.

**Comment by michael** [comment]
Think we are much faster now. Closing this and opening fresh issues if we see performance problems.
