### ISSUE TITLE
Possibility to render a surface with selection /wo an explicit setSelection

### ISSUE THREAD

**Issue by michael** [substance/substance#368]
Just to document that I had a case where this would be nice to have.

In ContainerEditor I create a text node and show it. Then I do a rerender of the Surface. Afterwards I can set a new selection.

``` js
  this.onCreateText = function() {
    var newSel;
    this.transaction(function(tx) {
      var container = tx.get(this.props.containerId);
      var textType = tx.getSchema().getDefaultTextType();
      var node = tx.create({
        id: uuid(textType),
        type: textType,
        content: ''
      });
      container.show(node.id);

      newSel = tx.createSelection({
        type: 'property',
        path: [ node.id, 'content'],
        startOffset: 0,
        endOffset: 0
      });
    }.bind(this));
    this.rerender();
    this.setSelection(newSel);
  };
```

Would it make sense to make the Surface transaction return a new selection and have that show up on rerender? 

``` js
  this.onCreateText = function() {
    var newSel;
    this.transaction(function(tx) {
      ....
      args.selection = tx.createSelection({
        type: 'property',
        path: [ node.id, 'content'],
        startOffset: 0,
        endOffset: 0
      });
    }.bind(this));
    this.rerender();
  };
```

While it's fine to implement it like this here, I'm thinking of cases where you want to render a ContainerEditor but with an initial selection (e.g. cursor at beginning of first paragraph).

Not a priority.. just to have it tracked.

**Comment by obuchtala** [comment]
The transform executed in the tranaction can return an obj that may contain a field 'selection' being a new selection. Following the 'flow' the selection is rendered in a last phase.

Don't think we need this.
