### ISSUE TITLE
Allow returning VirtualComponent in render

### ISSUE THREAD

**Issue by michael** [substance/substance#37]
``` js
render: function() {
  return $$(ChildComponent);
}
```

Does not work currently. We expect the element returned by render always to be an HTML Element. This would an important feature so we can save some markup. It's like delegating the output to the child component.

**Comment by obuchtala** [comment]
But why would it be another component in first place then, and not just extended?

**Comment by obuchtala** [comment]
I think this is not a use-case.

**Comment by michael** [comment]
``` js
render: function() {
  if (this.state.contextId == "writer") {
    return $$(Writer);
  } else if (this.state.contextId === 'dashboard') {
    return $$(Dashboard);
  } else {
    return $$('div').append('Context not handled');
  } 
}
```

It's quite nice to have such delegator components that don't produce extra markup. I used this often in React.

**Comment by obuchtala** [comment]
Not yet totally convinced. It looks like a render helper function to me, not like a component.

**Comment by obuchtala** [comment]
Can you collect your React use-cases, and then I would take a look at them?

**Comment by obuchtala** [comment]
Why I am hesitating to support this, is that now the ownership of the element is not clear anymore. I fear that this will cause troubles (e.g., with incremental rendering).
As a feature, I still think it is too weak.

**Comment by michael** [comment]
I will collect use-cases and fill in here. Maybe we can live without it.

**Comment by michael** [comment]
Let's forget about it. Clear ownership of el is a good thing!
