### ISSUE TITLE
Deleting a container selection that wraps a structured node should wipe it

### ISSUE THREAD

**Issue by michael** [substance/substance#370]
Currently only the surrounding text gets removed. Regression of #365.

**Comment by michael** [comment]
This seems to be a view update problem only. The structured node is gone after the delete in the model but it's not removed from the view.

Here's the test for the model: https://github.com/substance/substance/commit/437d8c3a1c9b11290ec4366ff1578366492e1633

**Comment by obuchtala** [comment]
This seems to work now.
