### ISSUE TITLE
Truncate icon detected while nothing to truncate

### ISSUE THREAD

**Issue by Integral** [substance/substance#374]
![screen shot 2015-12-24 at 17 05 12](https://cloud.githubusercontent.com/assets/182010/11995367/9a77ef48-aa60-11e5-9faa-4e093f55fb5f.png)

**Comment by michael** [comment]
Hm... This makes total sense to me. Truncating the last two chars.

**Comment by Integral** [comment]
ah, ok... it's not very clear actually... let's say it's my brain fault.

**Comment by michael** [comment]
It allows you to toggle expansion/truncation.. if you click several times you will always have just this one strong node.. That's what we want i would say.
