### ISSUE TITLE
Unstrong after inserting mixed content produced unexpected results

### ISSUE THREAD

**Issue by Integral** [substance/substance#375]
![](http://g.recordit.co/nM1LdD6ydb.gif)
Steps to reproduce:
1) Copy mixed content (e.g. strong text with plain text)
2) paste it inside strong
3) press strong tool

**Comment by michael** [comment]
Confirmed. We get some nested strong annotations here which we should avoid. Doing this paste as you demonstrated here should lead to just one continuous  strong annotation.

@oliver---- what do you think?

@Integral want to try to write a failing test case for this case?

**Comment by Integral** [comment]
@michael maybe... I will try

**Comment by michael** [comment]
Not sure what's the best way..  maybe this needs some guidance from Oli.. but read here if you can derive this case into clipboard test case.

https://github.com/substance/substance/blob/master/test/unit/ui/Clipboard.test.js

But maybe this is rather an issue on the copySelection + paste transformation.

Here's some related tests but not with paste yet.

https://github.com/substance/substance/blob/master/test/unit/model/transformations/copySelection.test.js

**Comment by michael** [comment]
Not critical for beta 3 pushing to beta 3. What happens is that with the paste a strong anno is nested. We somehow need to describe merge behaviors on paste. But that's part of a bigger story.

**Comment by obuchtala** [comment]
Not yet. Maybe related to #403
