### ISSUE TITLE
Selection is mapped incorrectly at end of a paragraph

### ISSUE THREAD

**Issue by Integral** [substance/substance#376]
![](http://g.recordit.co/A5511vKyv3.gif)
Steps to reproduce:
1) Set cursor on the end of the line
2) Hold shift and select next symbol
3) Press backspace

**Comment by michael** [comment]
Mhh seems this gets mapped internally to a collapsed cursor at last position. Definitely a minor issue, but I wonder what the intended behavior should be. It suggests that something is selected but actually there is no character at the end of the line... so the selection itself is weird. maybe this shift+next should select the first char of the next paragraph instead.

**Comment by michael** [comment]
In Google docs doing this means you remove the line-break, so you join the paragraph with the follow-up paragraph (textnode)

![delete-breaking-char-gdocs](https://cloud.githubusercontent.com/assets/2931/12002732/140c342a-ab08-11e5-83ea-b064d98b1cd2.gif)

**Comment by Integral** [comment]
Yes, that's what i expect...

**Comment by obuchtala** [comment]
![screen shot 2016-01-15 at 14 39 51](https://cloud.githubusercontent.com/assets/284099/12354446/4188f822-bb96-11e5-9e20-21b65ff71a49.png)

In this case the selection gets mapped incorrectly.
