### ISSUE TITLE
Use case

### ISSUE THREAD

**Issue by ghost** [substance/substance#379]
Is this library appropriate for developing a digital publishing app (Like book page design app)?

**Comment by michael** [comment]
Sorry missed to answer. Substance would definitely be a good choice for that. However the 'content designer' UI which applies the style to the content must be developed separately. It is not (and will likely never be) part of the Substance framework.

**Comment by michael** [comment]
Closing this as it's not really an issue. But feel free to respond here if more questions.

**Comment by ghost** [comment]
Sorry, what kind of apps exactly is the framework used for? The English confuses me :)
