### ISSUE TITLE
key / ref mechanism does not work on root element

### ISSUE THREAD

**Issue by michael** [substance/substance#38]
This fails

``` js
QUnit.test("Key/ref tests", function(assert) {
  var ClickableComponent = TestComponent.extend({
    render: function() {
      return $$('a').attr('href', '#').key('link').append('hello');
    }
  });

  var comp = Component.mount($$(ClickableComponent), $('#qunit-fixture'));
  assert.ok(comp.refs.link, 'Should have a ref to link');
});
```

Could we do something about it, for consistency? I understand that i could reach the root element using comp.$el, but somehow it's strange i can not use it.

**Comment by obuchtala** [comment]
Will need to take a closer look to understand.
From the first sight, I agree, that this is a bug.

**Comment by obuchtala** [comment]
On a second thought, this is kind of strange: using 'key' does not really make sense here.
The lfe-time of  the component is not controlled by itself. So persistence-wise, this would not make a difference.
Used as a ref, this would have the effect that

```
this.refs.link === this
```

While we can support this for better consistency, it simply doesn't bring anything.

**Comment by michael** [comment]
``` js
this.refs.link ===  this.$el[0]
```

it would be be?

Which brings me to the next question.. when a HTML-Element is referenced, should this.refs.elem return the jQuery wrapped element or the element itself?

**Comment by obuchtala** [comment]
No. Refs are components.
Notice: you want components, so that you can call setProps et al. on it.

**Comment by michael** [comment]
But only if really a user-defined component is referenced. If it's just an ordinary DOM node what can you do with it? Well maybe... calling .html on addClass etc.

Just thought of a common situation where you reference two input fields:

``` js
function login() {
  var username = this.refs.name.$el.val();
  var passwd = this.refs.passwd.$el.val();
}
```

We could spare the .$el if we directly returned the jquery element...  React 0.14 made this change since there was no other use-case for referencing ElementComponents. Before you also had to call .getDOMNode().

It's not soo important for me.. just something in the API that will used often. Just wondering if there's a usecase of doing something with those bare components. Adding a class for instance should only be done if the props have changed appropriately, because the determinism props/state -> dom would be violated.

**Comment by obuchtala** [comment]
Hmmm... but also React does not like you to do incremental updates, like changing the element. The component still makes it possible to set classes etc. incrementally, while still being compatible with the reactive rendering flow.
While I see, that there are cases where 'reading' from the element are necessary, there also might be cases where you 'write'.
You could add more jquery convenience delegators if you want to achieve that.

**Comment by michael** [comment]
Let's see how we will use this stuff in the coming months.

**Comment by michael** [comment]
Let's not allow a ref on the root element. That way the parent can control the ref of the component. A component should not self-manage it's own ref. I think we should implement #40 though.
