### ISSUE TITLE
Substance Hub API

### ISSUE THREAD

**Issue by michael** [substance/substance#380]
As part of the Substance Beta 4 release we are developing a server-side layer
that manages realtime synchronization and data persistence. We want to achieve
a homogenous system where links between versioned data stores can exist.

Consider the following use-case (from Substance Archivist):

Interview: A Substance document with paragraphs that consists of references to
entities that are managed outside of the document (can be referenced) from other
documents as well.

Entities: Entities live in a separate scope 'entities'. An entity could be a
location like Vienna. That entity object contains information such as name,
lat/long, description etc.

Scenarios we want to solve:
- Write documents collaboratively and synchronise changes in realtime to all active clients
- Create an entity from any client
  - All connected clients should see this new entity when they open the tag entity dialog
- Change an entity from any client
  - When an entity is changed all clients that 'use' that entity should receive the update and display the updated information in the UI.
- Delete an entity from any client
  - this is a destructive operation that would remove all entity references from all documents that point to the deleted object. (this is probably hard to generalize and may be realized using app-specific server-side plugins)

We just started designing this system, and the concrete technical details are
yet unclear. However I want to sketch how the usage could look like for the
client app developer.

Let's walk through a possible life cycle of a document + external resources.

``` js
hub.getInterview('interview-10', function(err, interview, entities) {
  // interview is a DocumentSession (which means it's aware of a selection)
  // and transactions. This session is live-connected to the hub endpoint
  // and will automatically receive changes in realtime.

  // 1. Manipulate the document
  interview.transaction(function(tx) {
    tx.create({id: 'p24', type: 'paragraph', content: 'foo'});
    tx.get('body').show('p24');
  });

  // entities is similar but does not maintain a selection. This would be some kind of
  // DataGraphSession

  // 2. manipulate entities
  entities.transaction(function(tx) {
    tx.create({id: 'linz', descr: 'Linz an der Donau'});
  });

  // the app can register on change events to entities to update UI parts e.g.
  // when changes from other users are coming in.

});
```

**Notes**: `getInterview` would be app specific for the Archivist app. I think it's better to allow the development of specialised endpoints that offer exactly what a client needs rather than trying to use a generic API from the client. For comparison, in a generalized form we would have two calls `hub.getBucket('interview-10', cb)` and `hub.getBucket('entities', cb)`;

As a start we could implement a solution that always fetches the whole data from a data bucket (interview or entities). However this solution has limits as the entity database could grow to thousands of entries.. where only a few are actually used in a certain document. If we want to tackle that we would need some kind of query language to fetch only parts of a bucket..  (e.g. get all entity references where target='entity-15', or: fetch all entities where id matches ['entity-1', 'entity-5'] etc.

**Problems**: By storing the doc and the entities in separate buckets we don't have a shared undo history. it's a general problem how we could make an application-wide undo chain that maps to different versioned data buckets. Anyway we need a solution for things like this:
- update paragraph 1 (interview)
- create entity-25 (entities)
- update paragraph 1 again (interview)

Now we should be able to do 3 times undo should also remove entity-25 from the global database. Well, unless it hasn't been used already by some other user or document. It will be a challenge to ensure integrity of the data which is often dertermined domain-specific and can't be solved generically.

**Comment by Integral** [comment]
I think that we definitely need kind of query language. It's not related to your example, because when you ask for all entities in context of some interview you already ask server for entities scoped to this interview. It's rather thoughts related to any interface for entity managing or searching. However it could be just an options object with few parameters:
`hub.getBucket('entities', {limit: 30, page: 2, query: {name: /linz/g}}, cb)`
Maybe it's app-specific, but we only need to reserve this options object which will be used by server.

Regarding undo stuff... It's also app-specific. It depends on interface I think... Somehow I could imagine that undoing of adding new entity could be unexpectable behaviour, especially when you have manager in separate page or modal...

**Comment by obuchtala** [comment]
Keeping this open, for the next iteration.
