### ISSUE TITLE
Allow adjusting size of split pane

### ISSUE THREAD

**Issue by michael** [substance/substance#394]
This means we introduce a separator area that is draggable. Challenge will be to make this least graphically obtrusive. However there needs to be some space reserved for the handle (like 10px). This must not overlap with other content.

New option `draggable` is false by default. Needs to be set specifically.

``` js
$$(SplitPane, {
  sizeA: '30%'
  splitType: 'horizontal',
  draggable: true
})
```

See React SplitPane for a reference implementation: 

https://github.com/tomkp/react-split-pane

**Comment by khlbrg** [comment]
Nice feature!

**Comment by obuchtala** [comment]
There is an incomplete PR which we will try to pick up in beta-5
