### ISSUE TITLE
[Ideas?] Keyboard shortcut support when nothing is highlighted

### ISSUE THREAD

**Issue by netsgnut** [substance/substance#413]
Not sure if that is a good title, but let me elaborate a bit more on what I'd like to achieve with Substance first. I am working on using a wiki system using Substance. One of the key features that we would like to achieve is the ability to control the whole system (navigating, searching, and of course, authoring) using only keyboard where mouse acts more like an assistance tool.

One of the features that can be commonly found in other WYSIWYG editors is that we can "use" a particular tool for the upcoming words, like if I wanted to type the following:

> This is an **important** message

We can type it as follows:

`This is an ^Bimportant^B message`

...where in between the `^B`s toggles the state of the command Bold/Strong.

However, in current implementation of Substance we would first type `This is an important message`, then highlight the word important using Shift-cursors or mouse and press the Strong/Bold button, because it seems the state of annotations are disabled once nothing is highlighted, which means the former editing behaviour does not really exist for Substance.

---

To extend the question further, what if the toggle itself can be anything other than a single keystroke? Currently the keybinding itself is handled within `Surface#onKeyDown` ([Source](https://github.com/substance/substance/blob/3bf02dd123178f538657b163f4f686f722f850be/ui/Surface.js#L363)). For example the toggle of bold/strong is handled by this code fragment:

``` js
    // Toggle strong: cmd+b ctrl+b
    else if (event.keyCode === 66 && (event.metaKey||event.ctrlKey)) {
      this.executeCommand('strong');
      handled = true;
    }
```

However, if let's replace our last example with, let's say, Markdown typing. Is it possible to replace the keystroke Ctrl/Cmd+B with the key sequence of consecutive `**` instead so when two asterisks are entered we will automatically have the strong tool toggled?

(Linking #91 as well as it might be related.)

**Comment by obuchtala** [comment]
I think this is what we call macros, which is possible since beta 4. You can register macros that get called on text input to scan the changed text and infer actions.

We should add the classical macros to the core packages.

**Comment by obuchtala** [comment]
Closing this in favor of #736
