### ISSUE TITLE
Repalce deprecated PathEventProxy.add with PathEventProxy.connect in DocumentNode

### ISSUE THREAD

**Issue by abhaga** [substance/substance#415]

**Comment by obuchtala** [comment]
We have gone further: while you still can use PathEventProxy, the most common use case is to add a listener for a specific node. `model/DocumentNode` exposes a more convenient way to this now:

```
  this.props.node.on('content:changed', this.onContentChanged, this);
  ...
  this.props.node.off(this);
```
