### ISSUE TITLE
Datastructure modelling user selections

### ISSUE THREAD

**Issue by michael** [substance/substance#442]
We need a datastructure to model collaborators (other editors). It should be owned by the DocumentSession object.

``` js
{
   "collaborators": {
      "fc2fef3": {
        "name": "Oliver",
        "index": 0,
        "selection": {"type":"property","path":["fc2fef3091ee430fba9af80745bd179e","content"],"startOffset":171,"endOffset":180,"reverse":false}
      },
      "fc2fef3": {
        "name": "Anonymous",
        "index": 1,
        "selection": {"type":"property","path":["fc2fef3091ee430fba9af80745bd179e","content"],"startOffset":174,"endOffset":174,"reverse":false}
      }
   }
}
```

Based on that information and events (a new collaborator enters, selection of a collaborator changes etc.) we can generate user interface elements such as selection and scrollbar highlights or for instance a collaborators panel to see who is currently editing the document.

**Comment by obuchtala** [comment]
Similar to what you specified.
