### ISSUE TITLE
Selections of changes within the undo/redo histories must be updated on remote change

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#450]
ATM these changes get out of date when applying external changes.

**Comment by dmukhg** [comment]
If I change the selection within a transaction using `args.selection = ...`, **on undo**, the selection doesn't change. Is this issue related to that? Should I open a new one? Please read for a brief explanation.

eg. Inside a transaction that converts heading h-a to paragraph p-b, 
- first create p-b, 
- transfer annotations,
- transfer selection,
- delete h-a

Now, if I undo, 
- h-a is recreated, 
- annotations are transferred, 
- p-b is deleted.

However, selections are not transferred back to h-a. This causes the Tool.getCommandState() methods to go haywire.

Thanks!

**Comment by obuchtala** [comment]
@schatten Basically I think that is related, yes. There is more to it, because we don't have a proper notion of transferring coordinates. I.e. such cases need to be considered OT wise.

I will make an integration test out of your description.

**Comment by obuchtala** [comment]
Thx for reporting!
