### ISSUE TITLE
Lifecycle websocket / CollabSession

### ISSUE THREAD

**Issue by michael** [substance/substance#455]
Currently CollabSession takes a fresh a websocket object and binds to the onopen event to immediately send an `['open']` message. That's too opinionated behavior. 

In our multi-document notepad app we want the websocket connection to be owned by the app and be created only once. So I think we should leave the websocket initialization to the app and require a connected/authenticated websocket connection. Then each time a user 'opens' or 'creates' a document we initialize a new CollabSession. We also need to make sure to dispose (or disconnect) the previous collab session and the new collabsession takes over the message handling. We should use `ws.addEventListener('message', handler)` instead of `onmessage = handler` so the app can bind a custom message handler too.

``` js
this.session = new CollabSession(doc, ws, {
  docId: 'note-1',
  docVersion: 0
});

// sends the open message to the server
this.session.start();
this.session.on('document:opened', this._renderEditor, this);

// to switch to a different session
this.session.stop(); // like dispose deregisters the handlers
this.session = new new CollabSession(otherdoc, ws, {
  docId: 'note-27',
  docVersion: 0
});
this.session.start();
```

Does that sound reasonable?

**Comment by Integral** [comment]
Yes, we defenetely should manage sockets on app side and pop them out in
case of disconnection.

**Comment by michael** [comment]
We could also not pass the ws immediatly, but explicitly with a connect call. That way we could start with a non-collab offline session but then later connect it to the hub.

``` js
this.session.connect(ws);
```

**Comment by michael** [comment]
@oliver---- not quite there but if you look at that code... does that seem to go into the right direction? 

https://github.com/substance/notepad/blob/7899624dca51286bfca787a996615cbf29466680/notepad/app.js

**Comment by obuchtala** [comment]
Looking good.
However I would need try it out to say more.

**Comment by michael** [comment]
thx. i will try to get it working in a branch.

**Comment by michael** [comment]
That's working now. We should just get this into master by adapting examples and testsuite.
