### ISSUE TITLE
Entry.concat is not a function

### ISSUE THREAD

**Issue by Integral** [substance/substance#457]
Steps to reproduce:
1) Install and run example's master branch
2) Try to annotate any selection with link

you'll get:
`PathEventProxy.js:97 Uncaught TypeError: entry.concat is not a function`

**Comment by obuchtala** [comment]
In the notepad example?

probably because package.json references an outdated substance sha.
It seems to work for me, with npm link setup, however. (i.e. uses latest substance)

**Comment by obuchtala** [comment]
I have bumped substance in examples package.json.
Works for me.

**Comment by obuchtala** [comment]
@Integral can u check?

**Comment by Integral** [comment]
yep
