### ISSUE TITLE
Allow useing OO.makeExtensible with OO.inherit

### ISSUE THREAD

**Issue by michael** [substance/substance#46]
I'd like to add an extra entry `command` to `defaultKeyProps` for the Tool class, so I can:

``` js
var StrongTool = AnnotationTool.extend({
  name: 'strong',
  command: 'toggleStrong'
});

module.exports = StrongTool;
```

However it seems that OO.makeExtensible does not work when used in conjunction with OO.inherit. Any ideas how I should approach this?

``` js
OO.makeExtensible(Tool, { "name": true, "displayName": true, "command": true });
OO.inherit(Tool, Component);
```

**Comment by obuchtala** [comment]
Probably you want to provide a hook for it. Can you explain again what you need?

**Comment by michael** [comment]
var StrongTool = AnnotationTool.extend({
  name: 'strong',
  command: 'toggleStrong'
});

I want `command` to go into `StrongTool.static.command`.

**Comment by obuchtala** [comment]
Ok. I think I should rename keyProps to staticProps and copy them over. The afterHook could then do other more stuff.
Will do.

**Comment by michael** [comment]
We have protoProps.static now.
