### ISSUE TITLE
Selections and image node

### ISSUE THREAD

**Issue by michael** [substance/substance#464]
We had some problems there in beta 3. I will bring back images in the notepad example then we can fix if necessary.

**Comment by obuchtala** [comment]
I am just working on a non-editable table... there I have still problems with the selections. However it has gotten better.

**Comment by michael** [comment]
I'll give it a try and report here what I had problems with.

**Comment by michael** [comment]
Images are activated in substance/notepad#master. Selection issues are still there. Also a fully wrapped selection does not work.

**Comment by obuchtala** [comment]
I have something working with table node. If you want you can try out examples@prose-editor together with substance@table-editing.
Otherwise wait until I have finished by table-editing quest.

**Comment by michael** [comment]
I tried the example. I was a able to create a new empty table but couldn't edit cells.

**Comment by obuchtala** [comment]
of course not.. because I posted on this issue which reads: 'Selections and image node'

**Comment by obuchtala** [comment]
The table node is similar to the image as it is not editable atm.

**Comment by michael** [comment]
sorry.. lost the issue title. Checking image selection stuff.

**Comment by michael** [comment]
Looks good from the selection mapping point of view.

**Comment by obuchtala** [comment]
We need to introduce a NodeSelection and render that by ourselves.

**Comment by obuchtala** [comment]
IsolatedNodes FTW.
