### ISSUE TITLE
Propagate collaborator updates

### ISSUE THREAD

**Issue by michael** [substance/substance#465]
Currently we only cover selection changes. We actually have more events:
- New collaborator connects
- Collaborator updates selection
- Collaborator disconnects (or explicitly closes the document)

Currently we handle it like this with an `updateSelection` message and an applyRemoteSelection method.

For the connect/disconnect cases we could again send a fake change object around that has no ops but also null as a before and after selection. Or we model a more generic `updateCollaborator` message with the following form.

```
{
  sessionId: 'a3c9003',
  type: 'connect', // or 'disconnect' or 'updateSelection',
  data: {} // selectionChange object in case of updateSelection; for connect, disconnect we could transfer some user data like username avatar etc. here
}
```

Thoughts?

**Comment by obuchtala** [comment]
Fine with your suggestion.

**Comment by michael** [comment]
That's done.
