### ISSUE TITLE
Rethinking table model

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#466]
ATM we have a exact representation of HTML tables.
However, this model is not good to work with.

I have done a spike using a native matrix as a property:

```
function TableNode() {
  TableNode.super.apply(this, arguments);
}
DataNode.extend(TableNode);

TableNode.static.name = "table";
TableNode.static.defineSchema({
  cells: { type: ["array", "array", "id"], default: [] }
});
```

Manipulation looks like this:

```
data.create({
  id: "t1",
  type: "table",
  cells: [
    ['A', 'B', 'C', 'D', 'E'],
    [null, null, null, null, null],
  ]
});
var table = data.get('t1');
data.set(['t1', 'cells', 1, 0], 'foo');
```

Beyond this, I came to the conclusion, that we need a special operation type for matrix updates. Otherwise we could not resolve concurrent editing situations -- for example a user inserts a row and another inserts a column at the same time: the inserted row needs to be one cell wider than the first user did know.

**Comment by michael** [comment]
Matrix Model looks fine to me.

**Comment by obuchtala** [comment]
This is being pursued now. Introducing a problem with real-time collab which will be addressed soon.
