### ISSUE TITLE
Prose editor configurations

### ISSUE THREAD

**Issue by Integral** [substance/substance#469]
Hey!
I found really strange thing.
Controller is configurable via static object or props.
ProseEditor extends Controller.
So we can configure ProseEditor. But ProseEditor comes with it's own static config. Due priority of static config it means that the only option to configure ProseEditor is passing your own static config. So if I pass any config as props to ProseEditor it will be rejected.
I think that the natural way here would be to gave ProseEditor it's own getConfig implementation with priority to props config. And this props config must merge with static config of ProseEditor.
This way it'll work like this:
a) If you want to extend ProseEditor with your tool - you'll just provide your tool's command and controller in props config;
b) If you need different set of tools you'll need to extend ProseEditor with your own static config.

What do you think?

**Comment by Integral** [comment]
Here is an example: https://github.com/substance/examples/blob/tags/tags/tagsEditor.js
I do it **only** because of config. We can do the same thing inside prose editor, e.g. merging incoming props.config into static.

**Comment by obuchtala** [comment]
I suppose this has become obsolete.
