### ISSUE TITLE
Illegal token in examples/server.js

### ISSUE THREAD

**Issue by ghost** [substance/substance#477]
.../examples/server.js:19
console.log(`http://${host}:${port}/`);
              ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by michael** [comment]
Can you provide more context?

**Comment by ghost** [comment]
Michael, I'm sorry. I did not notice the illegal tokens were removed when pasting the stack trace. In substance/examples/server.js line 19 a grave accent (U+0060) is used to delimit a literal (url), while probably an apostrophe (U+0027) was meant.

```
console.log(`http://${host}:${port}/`);
```

instead of

```
console.log('http://${host}:${port}/');
```

This causes "npm start" to fail with the above stack trace when following your tutorial to run the example.

Edited: I just realize this is meant to be an ES6 template string, so the grave accent is surely right and only my node runtime is outdated. Feel free to close this issue.

**Comment by michael** [comment]
Oh seems like one PR I merged used ES6 template strings and I overlooked that. Will fix.

**Comment by michael** [comment]
Fixed. Thanks for reporting!
