### ISSUE TITLE
Add Example/API for Real Time Collaboration

### ISSUE THREAD

**Issue by danielschwartz** [substance/substance#48]
Even though collaborative document editing is listed as a possibility with the editor (because of it's OT changes nature), there don't seem to be any examples/tutorials/api docs that describe how to do it. I would expect the DocumentChange class to be serializable (e.g. have toJSON and fromJSON methods) so that changes can be transmitted over the wire and instantiated in another users editor. Those methods would also help with DocumentChange persistence in any db type (RDBMS or Document).

**Comment by michael** [comment]
We will do some work on this in the coming months. It's all prepared for it, but still we need to write the server side pieces and put together some demo setup.

**Comment by obuchtala** [comment]
There is an example now with beta4. This has been the first iteration, which will be continued in beta 5.
