### ISSUE TITLE
Collapsed cursor is not rendered as a fragment

### ISSUE THREAD

**Issue by michael** [substance/substance#480]
We lost that somewhere on the way. Expanded selections work.

**Comment by obuchtala** [comment]
It should be rendered this way now:
- cursor fragment only when blurred (or other user)
- selection fragment always

@michael is this the case?

This is a hybrid of the former approach (render selection when natively blurred) and rendering always.
As we can't hide the native cursor I think it is better not to double render in this case.
With the selections we could do the same, however, personally overall I prefer to always render our selections.

**Comment by michael** [comment]
That approach is fine. However the cursor fragment is not rendered in the blurred case atm. Remote cursors however are rendered.

**Comment by obuchtala** [comment]
Ok. That should work indeed.

**Comment by obuchtala** [comment]
Probably I have some unmerged work here in the table-editing branch.
I will work on the general pieces related to selections and have them in an independent branch.

**Comment by obuchtala** [comment]
Fixed.
