### ISSUE TITLE
Undoing delete of a container selection fails

### ISSUE THREAD

**Issue by michael** [substance/substance#481]
Reproduce:
- Select multiple paragraphs
- hit backspace
- hit ctrl+z

![image](https://cloud.githubusercontent.com/assets/2931/13257131/d551bf32-da4d-11e5-852a-4dbd3d3655bf.png)

**Comment by abhaga** [comment]
I stumbled across the same bug and the reason seems to be that while inverting the changes for pushing on undo stack, the `before` and `after` selections get detached from the document. Once restored, this works fine.

If this fix looks acceptable, I can send a PR.

**Comment by obuchtala** [comment]
This seems to be fixed.
