### ISSUE TITLE
document persistence

### ISSUE THREAD

**Issue by larryhengl** [substance/substance#484]
Hi, 
I'm starting to look at Substance and Lens, thank you for sharing these projects.

Question:  how to save docs?

I see there is a plan for a Persistence API in Beta 5, but generally what have folks been using up to now for saving docs?  RDBMS, NoSQL, XML files, custom?  Any examples or tutorials illustrating current saving approaches?  If I simply want to CRUD a doc without needing OT behavior I suppose I could just serialize the doc and save it to a doc store, like CouchDB.  Or would you advise doing that differently?

thx!

**Comment by michael** [comment]
Hi!

There are many ways to do so. Most Substance users currently use XML/HTML as a serialization for Substance docs. It's easy to write custom converters for your model. Check out the official examples to learn how it's working. https://github.com/substance/examples

For a more complete example check out the LensImporter for instance.

https://github.com/substance/lens/blob/master/model/LensArticleImporter.js

The Lens code is generally a good source to inspect the workings of Substance in a larger context. You can just hook into onSave to connect your store.

https://github.com/substance/lens/blob/master/ReactLensWriter.js#L53-L56

If you want to build on something existing, you can check out PubSweet. It's meant as a framework for implementing your own publishing workflow and plug in your custom Substance-based editor. See:

https://gitlab.coko.foundation/pubsweet/core

However we are now working on collaborative editing and are coming up with a Persistence API for changes. If you want to use it you will have to implement a backend interface. You can checkout our notepad application, that implements a simple backend using SQLite.

https://github.com/substance/notepad/blob/master/hub/Backend.js

The collab features are still under development, but will land in Substance Beta 4 already. We hope to be able to release it around mid March. The nice thing about it, despite realtime support, is that you don't need to implement a converter then.

**Comment by larryhengl** [comment]
thanks for the info @michael , i'll dive deeper into the examples. i now see how you're using sqlite in the notepad app.  the pubsweet project looks ...uh, sweet!  their tech stack is aligned with my current project interests (React), and i see they are using PouchDB and Redux stores for persistence.  i'll be looking at the collab feature as it advances.  i'll go ahead and close this issue.   cheers!
