### ISSUE TITLE
Question: Is it possible to call setState within willReceiveProps

### ISSUE THREAD

**Issue by michael** [substance/substance#489]
I need to reset the state when new props are arriving. Currently i do this:

``` js
  this.willReceiveProps = function() {
    this.dispose();
    this.state = this.getInitialState();
    this._init();
  };
```

**Comment by obuchtala** [comment]
Sounds terrible, as setProps() and setState() per contract lead to a rerender.
But what you are doing, i.e. overwriting the state manually, looks fine to me.

**Comment by obuchtala** [comment]
Looking at Component.setState(): you won't have router state support this way. But probably you won't need that?

**Comment by obuchtala** [comment]
We should see if this is a general desire and potentially change setState() detecting that it may be within setProps() already.

**Comment by michael** [comment]
React documents that as a good practice... :O  

https://facebook.github.io/react/docs/component-specs.html#updating-componentwillreceiveprops

I have a bunch of uses-cases now related to component, state routing etc. We should soon discuss which direction we take, based on the Notepad app which does a bunch of state handling now due to its async nature.

We could even discuss dropping framework support for state handling completely and work with explicit rerenders instead. 

However we would need some concept for routing then. I'm not sure it's the best approach now, to mix it with the state concept...

**Comment by obuchtala** [comment]
Should not be too difficult to support setState during setProps.

**Comment by michael** [comment]
setState during setProps ? Not sure i follow.. can you give an example?

**Comment by obuchtala** [comment]
when u say 'willReceiveProps' it implies that you are during setProps.

https://github.com/substance/substance/blob/master/ui/Component.js#L495

**Comment by michael** [comment]
Of course.. sorry. Let me finish this iteration and we will discuss based on the results. Trying to cover the complete life cycle. And then we can see how we can shape the API to support that task in a transparent way.

**Comment by Integral** [comment]
Pls, don't drop framework support. I vote down.

**Comment by obuchtala** [comment]
@Integral sorry didn't get you. Can you explain in more words? ;)

**Comment by Integral** [comment]
Michael wrote:
We could even discuss dropping framework support for state handling
completely and work with explicit rerenders instead.

**Comment by obuchtala** [comment]
I think allowing setState() during setProps/willReceiveProps() without triggering an instant rerender should be simple. So no need to drop general support.

**Comment by obuchtala** [comment]
This is possible now.
