### ISSUE TITLE
Introduce keybindings

### ISSUE THREAD

**Issue by michael** [substance/substance#49]
Currently we define all keybindings hard-coded within Surface. We should come to some keyMap approach where we assign shortcuts with the commandName that should be triggered.

**Comment by michael** [comment]
This may also involve bringing back some Substance Keyboard stuff. Not super urgent, but definitely something we want to have in Beta 2.

**Comment by obuchtala** [comment]
We have two open PRs related to this #91 and #666 which we will pickup in beta5.

**Comment by obuchtala** [comment]
This is supported now: https://github.com/substance/substance/blob/ad6454a6ac103815e510740706f3aa5913abe84c/util/Configurator.js#L369
