### ISSUE TITLE
Container annos are not rendering

### ISSUE THREAD

**Issue by Integral** [substance/substance#492]
We haven't got here this issue, but it looks like it coming from Substance.
So, currently container anno tool/command works perfectly, but it's not rendered at all.

**Comment by obuchtala** [comment]
I need to use the notepad app for it?

**Comment by obuchtala** [comment]
Or is there a more light-weight example? lalala @smoofles.

**Comment by Integral** [comment]
yep, look here: https://github.com/substance/notepad/issues/18
you can use examples tags branch, but don't forget to connect
ConatinerAnnotation

**Comment by michael** [comment]
What Daniel wants to say is that it seems like container annotations don't get fragments in the rendering. You could try it out by working with the examples and turning for instance the highlight node into a ContainerAnnotation instead of a PropertyAnnotation.

**Comment by michael** [comment]
It seems that tools etc. respond correctly so it's only a rendering issue.

**Comment by obuchtala** [comment]
Yep. That's for sure.

**Comment by obuchtala** [comment]
We'll introduce 'flow' next in beta5 which is key for this implementation.

**Comment by michael** [comment]
Dup of #789
