### ISSUE TITLE
Package: Forms Generator

### ISSUE THREAD

**Issue by Integral** [substance/substance#494]
Hey!
I thought a few days ago about forms framework based on Components.
Like you can describe your entity with a substance schema and this thing will generate a form for you.
Where do we need this? For example in the metadata editor or archivist entity manager.
I could try to implement this thing somewhere outside.
@michael, @oliver---- what do you think?

**Comment by michael** [comment]
Feel free to experiment in a new example setup. It's could be an interesting use-case for the future. I think it will be hard though to find a good balance. basic text-only forms will be simple to implement based on schema inspection. However if you want more (like dropdowns with preconfigured values) it needs more configuration than what our schema provides. It may also be already too much.. as good UI  so often requires custom components. I would suggest you that you evaluate use-cases, when would you use it.. e.g. for archivist (which of the current forms could you implement like that.. and which would still need to be custom (e.g. longitude latitude selection). is there enough benefit from having a form generator. 

I can't assist you here atm, as i don't want to loose the focus on collab features and beta 4 release.

**Comment by Integral** [comment]
Well, there is always the same basics with these things. There are a lot of
similar projects. The difference is that we want to build it within our own
system.
But even these basics requires additional configurations. Like html5 inputs
which have different types (text, number, email, phone etc). So we need to
pass additional config somehow... However we shouldn't do anything complex,
we rather need to left some kind of api for more complex forms.
My idea to play around with it and see what is possible. I don't expect any
help, just general aprovement and maybe a bit of advising.

**Comment by Integral** [comment]
I've decided to begin with metadata editor as we have no example for that.
And now... We have it. All basic types. You have to specify schema a bit and connect forms within a tool.
Here it is:
![](http://g.recordit.co/SUrhPf5AkY.gif)

**Comment by obuchtala** [comment]
Future :)
