### ISSUE TITLE
Booting with an Empty Editor Content 

### ISSUE THREAD

**Issue by netsgnut** [substance/substance#50]
Tested on 1.0.0-beta. If we are to [replicate the Notepad demo but with an empty content state, i.e. empty `<div id="editor_content"></div>`](https://github.com/substance/demos/blob/bcfcd6919a769ed4a1d46e3e28d1960849bc2c57/notepad/index.html#L16-L21), we would result in an cryptic `TypeError: node1 is undefined` bubbling from [here](https://github.com/substance/substance/blob/fed41a88a6ffb051bbf27a3e8afa8d1deab5bafe/surface/surface_selection.js#L31) once the editor is getting focus.

The obvious workaround is, of course, make sure there is at least _something_ at the editor holder, but in some cases starting from scratch sounds reasonable. Any ideas, or am I simply misusing it? Thanks.

**Comment by michael** [comment]
Editor should be robust regarding empty content. Will be fixed for Beta 2! Thanks for reporting.

**Comment by netsgnut** [comment]
Thanks for the assurance! :)

**Comment by michael** [comment]
So things changed a bit here.. the Notepad example requires a doc instance as a prop, so conversion is now a task of the component user. However we should check how the editor deals with an empty container. Will come up with a solution for that.

**Comment by obuchtala** [comment]
I think ContainerEditor should always make sure that there is at least one node to interact with.

**Comment by obuchtala** [comment]
We discussed that this should be done UX wise. I.e. the ContainerEditor should a message and provide a button or such that would create a first node.

**Comment by michael** [comment]
Fixed via #361.
