### ISSUE TITLE
API Docs are currently broken in the collab-improvements branch

### ISSUE THREAD

**Issue by michael** [substance/substance#503]
@Integral Maybe you have time to take a look. However if you don't find it fast.. don't waste time on it.. could also be something in the parsing step.

**Comment by Integral** [comment]
Not sure. Don't know much about docs app.

**Comment by Integral** [comment]
Looks like problem with one of nodes

**Comment by michael** [comment]
Leave it then. not so urgent. Just wanted to see what options we have to document our method signatures that now only have an `args` object. It's not so clear now what the actual arguments are. We should add a comment block describing them like: 

``` js
/*
    Gets changes for a given document

    @param {String} args.documentId doc id
    @param {Number} args.sinceVersion since which change
  */
```

not sure though this will look pretty in the docs. Anyways this has time.

**Comment by Integral** [comment]
I already did it SQL backend.
