### ISSUE TITLE
Rename `ControllerTool.performAction`

### ISSUE THREAD

**Issue by nokome** [substance/substance#504]
A minor aesthetic suggestion: depreciate `ControllerTool.performAction` and provide `ControllerTool.executeCommand`. More consistent with existing nomenclature e.g. `SaveTool.static.command = 'save';` The name `performAction` feels a bit out of place, or perhaps I'm missing something :smile: .

**Comment by michael** [comment]
Thanks! Jeah that could need a bit of polish from naming. Also name and command are redundant. Will take care of this until Beta 4 is out.

**Comment by michael** [comment]
It's called executeCommand now.
