### ISSUE TITLE
Support for general keyboard shortcuts like Home, End, Page Up, Page Down etc for better accessibility

### ISSUE THREAD

**Issue by sunu** [substance/substance#506]
Hi,
Currently the native cursor moves as expected with End, Home, Page Up and Page Down keys but the underlying selection is not updated.
I was wondering if improving accessibility is on the road map you guys have in mind?

**Comment by michael** [comment]
We will check. That should definitely be supported and work as expected.

**Comment by nokome** [comment]
+1 I just discovered this too. When you press home or end, the cursor moves as expected but the insertion point doesn't - i.e when you start typing again characters get inserted where you were when you pressed home. Tested under Chrome in stencils and the editor at http://substance.io/ . Thanks for  adding this to Beta 4!

**Comment by obuchtala** [comment]
Fixed via 5020469736358ec51e1d9ff3fc7ee66145648a6b
