### ISSUE TITLE
padding between container nodes should be generalized

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#509]
At the moment, there are styles such as in https://github.com/substance/substance/blob/dcb4db4ff799689a61b4bf50d3bbd10517880a24/packages/paragraph/_paragraph.scss#L2

Instead this should be done with a child selector for the surface/container element.

**Comment by michael** [comment]
Yep. I think there shouldn't be any styles for the core types as we don't know how they'll be used/nested. I still didn't get to my css modularisation iteration. I think what would be nice is to have some defaults that we can wrap inside a parent selector. Not sure what's the best way here. Needs some more SCSS studies.

**Comment by obuchtala** [comment]
Ok. I just wanted to emphasize, that theoretically vertical-spacing between nodes seems to me not a node responsibility but one of the container layout.

**Comment by obuchtala** [comment]
In examples I added a default padding this way:

```
.sc-editor .sc-surface.body {
  padding: 40px;

  > * + * {
    padding-top: 20px
  }
}
```

I think it is up to the app to do so, or up to a certain package like ProseEditorPackage?

**Comment by michael** [comment]
Looks good.

**Comment by obuchtala** [comment]
Done
