### ISSUE TITLE
Sometimes Undo/Redo buttons aren't clickable after consecutive clicks

### ISSUE THREAD

**Issue by netsgnut** [substance/substance#51]
It seems at times toolbar buttons become non-clickable over time - this can happen when undo/redo is made (especially a series of them are clicked over time). One will have to manually set active cursor on the editor itself before the button starts to be responsive again.

**Comment by obuchtala** [comment]
I think that is because at first we implemented undo/redo tools as selection dependent (like annotation tools for instance). And this of course doesn't make sense.
I think @michael has been working on refactoring the tools implementation, so this is gonna be fixed in beta2.

Thx for reporting.

**Comment by obuchtala** [comment]
I can confirm that @michael's refactor has fixed this issue.

**Comment by netsgnut** [comment]
Cool, looking forward to it. Thanks!

**Comment by michael** [comment]
That's fixed. Closing.
