### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by michael** [substance/substance#510]
I spent today evaluating options for error reporting. I came up with a custom SubstancError class.

``` js
var Err = require('substance/util/Error');

throw new Error('DocumentStore.CreateError', {
  message: 'Could not create document. '+ documentId +' already exists',
  info: 'some additional context info can go here'
});
```

message and info are optional. So in many cases we will just `throw new Error('MyClass.WhatHappened')`.

Now we will use `DocumentStore.CreateError` will be used as the error name. So we will see messages like "Uncaught DocumentStore.CreateError: Could not create document. 'foo' already exists.". We can use the custom error name to map it via i18n. However we should on each layer introduce custom errors, so implementation details are not exposed to the client.

Let's look at the next layer, and an example where we take an error triggered by a low-level API and wrap it in a new custom error object.

``` js
  this.deleteDocument = function(documentId, cb) {
    this.documentStore.deleteDocument(documentId, function(err, doc) {
      if (err) {
        return cb(new Err('DocumentEngine.DeleteDocumentError', {
          cause: err
        }));
        cb(null, doc);
      }
    });
  };
```

The SubstanceError constructor takes a `cause` option, which can hold the error that caused the error thrown/emitted. That's a nice thing as we still have access to the original stacktrace and SubstanceError.toString will print both error messages for a better context.

Here are some files that use the new API already:

Callback API's: https://github.com/substance/substance/blob/master/collab/DocumentStore.js
Promise API's: https://github.com/substance/notes/blob/master/server/UserStore.js#L70-L77

We can use those more specific errors for testing known error scenarios.

https://github.com/substance/notes/blob/master/test/server/UserStore.test.js#L57-L64

Let me know what you think.

**Comment by Integral** [comment]
Let's try!

**Comment by michael** [comment]
That's done.
