### ISSUE TITLE
CollabWriter bug - stops updating when cutting and pasting links

### ISSUE THREAD

**Issue by jure** [substance/substance#519]
To reproduce: 
Using the CollabWriter example
Pasting some text with links, e.g. the first paragraph of http://elifesciences.org/content/5/e12499v2
Cut some text with a link in one pane, and paste it in the other pane, the original pane is now not updated until the cursor is moved

**Comment by michael** [comment]
Could reproduce this in Notes app, getting the following stack trace:

![image](https://cloud.githubusercontent.com/assets/2931/14527976/78c67226-024d-11e6-9884-031c523e12b0.png)

**Comment by jure** [comment]
Glad you could reproduce it, seems like a common enough action. Any idea why it's occurring?

**Comment by obuchtala** [comment]
That's OT business.
Obviously we try to 'rebase' a create of a node across its deletion - which sounds weird.
Need to take a closer look when this occurs exactly.
