### ISSUE TITLE
Missing TableSelection module

### ISSUE THREAD

**Issue by jmatsushita** [substance/substance#520]
Hi there,

I'm giving a kick in the tires of Substance and when trying to fiddle with adding converters and components to the Notepad example app I'm running into a missing dependency for the table package.

In `substance/packages/table/TableComponent.js

```
var TableSelection = require('../../model/TableSelection');
```

From the code it seems like this probably exists somewhere but I can't seem to find it (the `table-editing` branch seems older than this work).

Thanks for the really interesting work!

Jun

**Comment by michael** [comment]
Tables are currently reworked and not working on master. They will be based on some new API's that are developed here.https://github.com/substance/substance/pull/508.

Tables will be part of beta 5, just give us some time. :)

**Comment by jmatsushita** [comment]
Ok great! Thanks for the update. Keep up with the good work :)

**Comment by obuchtala** [comment]
Closing this. Tables are there in an initial version.
