### ISSUE TITLE
Strange line wrap at the cursor for a long long single word when the edit area loses focus

### ISSUE THREAD

**Issue by fengye87** [substance/substance#521]
A really awesome JS lib, but I've found a subtle bug when playing with the demo. Here's some steps to replay the problem:
1. Go to http://substance.io/
2. Enter a really really long word (no whitespaces). I entered dozens of consecutive 'a's.
   ![normal](https://cloud.githubusercontent.com/assets/7160387/13867911/ca04e992-ecfe-11e5-9def-c18ef067ea16.png)
3. Put the cursor somewhere in between letters.
4. Click somewhere else than the edit area to make it lose focus.
5. Oops, the word gets a strange line wrap at the cursor position.
   ![wrap](https://cloud.githubusercontent.com/assets/7160387/13867912/ca059dc4-ecfe-11e5-82c9-cfc8f2254ca2.png)

**Comment by michael** [comment]
I think this is resolved now. We will release beta5 today (hopefully) and then please verify and if you see still a problem somewhere reopen this issue.

Thank you for reporting it! And sorry for taking so long to respond to it.
