### ISSUE TITLE
Question: Building a component that wants to handle rendering & events itself?

### ISSUE THREAD

**Issue by rileylark** [substance/substance#526]
I'd like to make a substance component to wrap mathquill for math typing ( http://mathquill.com/ ). Unfortunately, mathquill uses jQuery to manage its own state - it won't play nicely with a virtualdom approach, and it may not respect other contracts that substance assumes.

I have so far tried using `didMount` to find the actual DOM node that mathquill needs to take over, like this:

```
this.didMount = function() {
    var actualNode = jQuery('[data-id=' + this.props.node.id + ']');
    doOldStyleJqueryInitializationForMathquill(actualNode[0]);
};
```

But I'm getting all sorts of errors on the console (as I would expect). Is there a better way to make a component that reserves its own rendering space within the substance editor?  Maybe I can somehow mark the component within the substance UI to let it know 

Thanks for any help!

Riley

**Comment by michael** [comment]
Hi Riley!

I don't know the inner workings of Mathquill, but it should be possible to integrate any classic self-controlled javascript widget. You can use refs to refer to component elements, so you don't need a global data-id selector to find the wrapper DOM element. Something like that:

``` js
  this.didMount = function() {
    var mathQuillEl = jQuery(this.refs.mathQuill.el);
    doOldStyleJqueryInitializationForMathquill(mathQuillEl);
  };

  this.dispose = function() {
    // make sure all event listeners are disconnected, so you don't leak memory
  };

  this.render = function() {
    return $$('div').addClass('sc-math').attr({contenteditable: false}).append(
      $$('div').ref('mathQuill')
    )
  };
```

By setting contenteditable to false you make sure your self-controlled element does not get into the way of editing.

**Comment by rileylark** [comment]
Thanks @michael , that seems to be working much better than my force-selected element technique. Unfortunately now I think events that should be going to my old-style jQuery component are getting eaten by substance. For example, I can focus inside my component, but as soon as I type the focus jumps out to past the component and the letters appear in the normal editor space. Maybe substance is `preventDefault`ing on events to my component? Is there an api for "hey seriously leave all events to this space alone?"

**Comment by rileylark** [comment]
In case you happen to have time to help more with this, I cloned the examples repo and pushed my work so far, stripping out the MathQuill dependency altogether so you don't need to know anything about that.

Basically, I made a fictional jQuery plugin that works like this:

```
function externalJquerySetup(el) {
    jQuery(el).append('<input value="should be able to type here!"></input>');
}
```

It's doing its jQuery thang, messing with the dom and expecting users to be able to interact with it. But when I connect it to a substance component (I think I am following your advice), the user cannot type in the input!

Here's my whole component:

https://github.com/rileylark/examples/blob/master/notepad/MathQuillComponent.js

And the command I'm using to insert it (copied from the TodoComponent):

https://github.com/rileylark/examples/blob/master/notepad/MathQuillCommand.js

And my schema (maybe I'm messing everything up by calling this a TextBlock?):

https://github.com/rileylark/examples/blob/master/note/noteSchema.js#L34

I know this is a lot to ask. Feel free to close & ignore, and thanks for your help so far already!

**Comment by michael** [comment]
Thanks for providing an isolated example! Your assumptions are right I think. We definitely want to solve this for Beta 4. Will follow up here once I have updates.

**Comment by rileylark** [comment]
Sure, my pleasure @michael . It sounds like you think this can't work yet, but would like to add it to an upcoming release. If I have that right, I'd love to help by contributing a PR. Would that be helpful? Do you have any advice for a starting point?

**Comment by michael** [comment]
We simply haven't had that usecase yet. But it's definitely an important one. I'd like to solve this along with some other work that's currently going on. https://github.com/substance/substance/pull/508 I'd be glad to see your proposed fix, however we will need to see if it will still apply after our internal reworking.

**Comment by obuchtala** [comment]
With IsolatedNodes we can do this now.

Edit: shipped with beta4, examples will include an external code editor, as well a custom component with native input element.
