### ISSUE TITLE
Cursor is hidden when positioned at the beginning of non empty paragraph

### ISSUE THREAD

**Issue by dannelundqvist** [substance/substance#528]
The cursor is hidden when positioning it at the very beginning of a non empty paragraph in branch _substance/substance#dragndrop_. It does not matter if the cursor is moved to the first position using arrow keys or a mouse click.

However, when clicking a second time, or clicking after navigating there, the cursor is shown again.

**Comment by michael** [comment]
I think I finally fixed this.

https://github.com/substance/substance/commit/d444ee15a069cd8d7fa668b7b85dba1d9a2667bc

This will go into beta4. It affects not only the CSS, also the rendering so it would take a bit of time to backport to beta3. @dotvoid is it ok for you to get this via beta4?
