### ISSUE TITLE
Bind to input sequence

### ISSUE THREAD

**Issue by Integral** [substance/substance#534]
For notes app we need some kind of API which will trigger action on matching input sequence.
E.g. when user type // on paragraph beginning this paragraph must turn to comment or if user type [] paragraph must turn to issue.
@oliver----, could you help us with that?

**Comment by netsgnut** [comment]
Linking #413 as well, as this idea sounds similar to what we would like to do in another application.

**Comment by Integral** [comment]
Yes, it's the almost the same api I would say.

**Comment by obuchtala** [comment]
We have keyboard macro support now. Being part of beta4, coming with an example,too.
