### ISSUE TITLE
want to send pull request, but don't know which files to pick

### ISSUE THREAD

**Issue by dannyxx001** [substance/substance#535]
@michael 
Hello, I'm an intern of cdnjs. (https://github.com/cdnjs/cdnjs)
I want to send pull request to merge your lib, but I don't know which files to pick.
Would you please tell me the files I should pick to join the library?
Thank you.

**Comment by michael** [comment]
Hi! Thank you for the offer. However, Substance supports requires only on a file basis (or in other words, we don't provide any bundles), so it's not exactly suited for a CDN.

**Comment by PeterDaveHello** [comment]
@michael if you changed your mind, please let us know, thanks.
