### ISSUE TITLE
We should communicate a roadmap for Substance

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#54]

**Comment by Integral** [comment]
Should we do it together?

**Comment by obuchtala** [comment]
I think this needs a lot of discussion. We should do that next week, when @michael has time for a call.

**Comment by Integral** [comment]
Isn't Michael comes back at 22th?

**Comment by obuchtala** [comment]
Yes, we can do it then, too.

**Comment by michael** [comment]
Jeh let's do that together next week. I thought of making a feature-table for the README. We could put the status of each feature there.

Custom document models: STABLE
2-column writing interface: EXPERIMENTAL
Realtime collaboration: BETA 2

Is there something between STABLE and EXPERIMENTAL? :)

**Comment by obuchtala** [comment]
What is the difference between STABLE and EXPERIMENTAL ;)

**Comment by michael** [comment]
We must talk! ;)

**Comment by michael** [comment]
Done.
