### ISSUE TITLE
Component Refactor: willReceiveProps is called initially.

### ISSUE THREAD

**Issue by michael** [substance/substance#542]
I was expecting this to be called only when new props are arriving, not if a new component is instantiated. 

@oliver---- Was this change on purpose?

**Comment by oliver----** [comment]
https://plus.google.com/hangouts/_/calendar/anVyZXRyaWdsYXZAZ21haWwuY29t.ms2p7pjmfu3gujjs2bk4kgg8no?authuser=0

Michael Aufreiter schrieb:
>
> I was expecting this to be called only when new props are arriving, 
> not if a new component is instantiated.
>
> @oliver---- <https://github.com/oliver----> Was this change on purpose?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/substance/substance/issues/542>
>

-- 
Sent with Postbox <http://www.getpostbox.com>

**Comment by obuchtala** [comment]
Nope. Will be removed.

**Comment by obuchtala** [comment]
Fixed
