### ISSUE TITLE
Ran into exception: Component is rendering already

### ISSUE THREAD

**Issue by michael** [substance/substance#551]
Happens for Note app, if not logged in and when navigating to the main page.

http://localhost:5000

![image](https://cloud.githubusercontent.com/assets/2931/14523744/92f52cae-0235-11e6-9972-da04e64814b3.png)

**Comment by michael** [comment]
It's triggered by didUpdate of Notes.js and seems like the **isRendering** flag is still on at that time.

**Comment by obuchtala** [comment]
Are you on latest substance#master?

**Comment by obuchtala** [comment]
Ah, I see. You are setting state in didUpdate(), which itself is called during the last phase of a rerendering.
So, in other words: is it valid to call rerender() in didUpdate()?

**Comment by obuchtala** [comment]
It sounds to me that this is sick (possible infinite rendering loops).
Looking at the code, I think the state handling in Notes.js is still messy, and this is the result of it.

**Comment by obuchtala** [comment]
Until Notes's state handling is mastered, you can use

```
  this.didUpdate = function() {
    if (!this.state.initialized) {
      // HACK: delaying this as a workaround
      // calling this.setState() while in a rerender cycle (e.g. after setState())
      // is not allowed ATM
      console.log('initializing..');
      setTimeout(function() {
        this._init();
      }.bind(this));
    }
  };
```

**Comment by michael** [comment]
Yea, need to go to draw state machine on paper.

**Comment by michael** [comment]
Regarding semantics: Why is didUpdate the last phase of a rerendering and not called after all rererendering has finished? I mean I suppose in didUpdate you can not influence the rendering in any way anymore, so it could be safe to terminate the rendering (**isRendering** = false) before calling didUpdate? Not sure...

**Comment by obuchtala** [comment]
I know that it can be solved somehow...but actually I am really against it, as it opens the door for infinite rerendering loops, which I prefer to keep closed.
And allowing it does not solve anything. On the other side, cool that it is not possible, discovering bad state handling.

**Comment by obuchtala** [comment]
I have introduced the `__isRendering__` flag to prevent infinite loops. Even if this one is not an infinite one it could be one.

**Comment by obuchtala** [comment]
> Regarding semantics: Why is didUpdate the last phase of a rerendering and not called after all rererendering has finished?

Depends on what you are calling a rerender cycle. For me, triggering hooks belongs to the cycle:

```
Render = 
1. capture diffs
2. apply changes
3. trigger hooks
```

**Comment by obuchtala** [comment]
Or if you want, you can call it an 'update' cycle.

**Comment by michael** [comment]
Got it. That sounds reasonable.
