### ISSUE TITLE
ProseEditor containereditor.selectFirst function missing

### ISSUE THREAD

**Issue by michael** [substance/substance#553]
This errors:
https://github.com/substance/substance/blob/master/packages/prose-editor/ProseEditor.js#L26

Maybe this function got lost somewhere in a branch?

**Comment by obuchtala** [comment]
Seems so.
Just deactivate this call for now.

**Comment by michael** [comment]
Will add a stub printing a TODO message. Should this go into Surface or ContainerEditor?

**Comment by obuchtala** [comment]
ContainerEditor
