### ISSUE TITLE
Issues with invalid collaborator selections

### ISSUE THREAD

**Issue by michael** [substance/substance#554]
Just to start tracking issues so we can reproduce and fix those edge cases:
- Use CollabWriter example
- Make container selection for user A (e.g. 8901)
- Make same selection for user B
- hit backspace to delete the selection

Leads to an error because collaborator selection still references p2 which just disappeared because of the deletion.

![image](https://cloud.githubusercontent.com/assets/2931/14529644/cba9d12e-0255-11e6-9ec4-14ba31c8b1f3.png)

**Comment by obuchtala** [comment]
Real-time collab stuff is continued in beta 5.
