### ISSUE TITLE
How to access files property of file input element via DefaultDOMElement

### ISSUE THREAD

**Issue by michael** [substance/substance#556]
Removed jQuery for ImageCommand, but wondering how I could avoid navigating to the native element to access the files property of a file input element.

https://github.com/substance/substance/blob/master/packages/image/ImageCommand.js#L54

**Comment by obuchtala** [comment]
This way:
https://github.com/substance/substance/blob/master/ui/BrowserDOMElement.js#L78

**Comment by michael** [comment]
Thanks!
