### ISSUE TITLE
Idea: Implement router as a component

### ISSUE THREAD

**Issue by michael** [substance/substance#557]
I tried many different things today to get the top level state handling right for the notes app. One of the main problems I identified is mixing router stuff with internal component state stuff.  If we could separate that somehow, things would become easier to grasp. Also getting the order right is difficult. E.g. when the loginKey is in the route we must trigger reauthentication(=reinit) while in other cases we could init before consuming the router route.

So here's an idea: Let's say the router is just a regular top level component that controls the whole app navigation flow. If you want to change the global app state the router is the place to handle the action. The router's component state is equivalent to the url and always must be in sync. Each state change leads to a 'render' of the router, which we can use to pass the app state as props to the top level component. Given the notes example we now have it easier, as we can react on willMount and willReceiveProps to trigger internal state transitions (such as authentication). We also don't have the problem of calling setState from within didUpdate anymore, as within willMount and willReceive props it's allowed to 'derive' state. I think that's what we want. I think not much changes for the implementation except that we 'abuse' the component API for the routing implementation. Nice thing is that Notes.js no longer knows anything about the router (writeURL, readUrl etc.) thus can be used without a router too.

Wrote some pseudo code.. if I get your ok, I will try to implement that tomorrow.

``` js
'use strict';

var Router = require('substance/ui/Router');

function NotesRouter(){
  Router.call(this);
  this.handleActions({
    'openNote': this._openNote
  });
}

NotesRouter.Prototype = function() {

  // Can go into Router
  this._setStateAndRoute = function(state) {
    this.setState(state);
    this.router.writeURL();
  };

  // Can go into Router
  this.didMount = function() {
    // triggers the initial state change based on the route
    this.readURL();
  };

  this._openNote = function() {
    this._setStateAndRoute({
      mode: 'note',
      documentId: 
    });
  };

  this.stateFromRoute = function(route) {
    if (!route) {
      return this.getInitialState();
    } else {
      return Router.routeStringToObject(route);
    }
  };

  this.routeFromState = function() {
    var state = {};
    var appState = this.app.state;
    ["mode", "docId"].forEach(function(key) {
      if (appState.hasOwnProperty(key)) {
        state[key] = appState[key];
      }
    });
    return Router.objectToRouteString(state);
  };

  this.render = function() {
    var el = $$('sc-notes-router');

    if (this.state.mode) {
      // State is tranformed to 
      el.append(Notes, this.state);
    }
  };
};
Router.extend(NotesRouter);
```

**Comment by michael** [comment]
I also made some sort of diagram for Notes app to better understand the component hierarchy for different scenarios (route + authentication state + mobile or not)

https://docs.google.com/spreadsheets/d/1ZJQ_7E874iV81gbcfCDy5zxfAoxJpwMZc_X6IaiVmwY/edit#gid=0

**Comment by obuchtala** [comment]
The core problem is modelling the app state correctly, and implement app state transitions consistently.
The router is just the piece triggering those transitions.
So, I don't see the point putting the Router in the middle of everything.
First you should give your app an API which can deal with all the transitions that you identify.

**Comment by michael** [comment]
We have a solution now.
