### ISSUE TITLE
.table nodes should be namespaced

### ISSUE THREAD

**Issue by jure** [substance/substance#558]
Table nodes have a very generic class name and styling applied: https://github.com/substance/substance/blob/918878959ef88c20b2750963e20fb5750df60f13/packages/table/_table.scss#L4

Is there any specific reason why this is not namespaced like the other nodes are, e.g. `.sc-figure` or `.sc-image`?

**Comment by michael** [comment]
New table implementation is coming soon. Current table is considered legacy.
