### ISSUE TITLE
React.js versus custom component.js?

### ISSUE THREAD

**Issue by jasonphillips** [substance/substance#56]
In the interest of incorporating this library into some of my projects that are implement within react-driven interfaces, I'm looking for more documentation or help understanding the decision to drop react from your code in favor of what appears to be a close re-engineering of react components (in component.js). I'm also looking for any clear documentation on the relationship between the "legacy" (react based) version of the library and this one, as well as an idea as to whether the legacy code will now be officially left dead or will continue to see work in parallel. 

For applications that are already built within react, the legacy library seems more appealing and supports the excellent example of Lens Writer which accomplishes much of what I'm looking for. It's a very hard sell, at least at first glance, to commit to the limitations of a pared-down custom implementation of react-like components (using all the same lifecycle hooks and concepts, from what I can tell) that will then need constant work to match pace with react's updates over time and that won't integrate with everything react offers above and below in an app (ie., existing (child)context already passed down the tree that I'd like to make available to the editor, incorporation of other mature UI element libraries in react for building custom widgets, etc). 

The code does imply that you dropped react in favor of synchronous rendering... I wondered if the recent split (in 0.14) between react (as a component library) and react-dom (as merely one rendering implementation that is now swappable for others) could alleviate some of that overhead if you merely wished to replace the rendering of react-dom but keep react's components as your base. But obviously I haven't dug deep enough into the code here to see how this all shakes out.

Mainly just seeking information on dropping react and an idea of whether the legacy project will soon be effectively dead -- I might have merely overlooked where I can find that.

**Comment by obuchtala** [comment]
We were having serious problems with React in the context of our editing surface.
One of it was the async nature of render. Looking at this: https://github.com/facebook/react/blob/a05691f0ad9d20fc9ffb1fc04d531e257e37d55b/src/renderers/dom/client/ReactMount.js#L711
it is still the same.
The reason: imagine that at some place in our lib we apply an operation which changes say a text property. As we do everything in the model first and update the UI accordingly, we need to make sure the DOM selection is set properly afterwards, as a rerender might destroy the DOM selection. Async rendering makes it pretty difficult to control that. The second issue when you have async rendering is, that on some newer computers event sequences got out of sync with rendering. I.e., typing very fast did not look good, particularly the DOM selection updates were not accurate sometimes.

Another thing with react's rendering was performance. In the Archivist, we were having documents with >10k paragraphs, which we rendered using a component with a child component for each paragraph. react needed like ~1s just for DOM diffing. Without hacking 'shouldUpdate' and managing these updates ourselves, this could not be solved. 

We found our code getting more and more ugly, with more and more hackz, making it less maintainable. And this was the moment were we ditched react.

Last but not least, we were not happy to couple Substance as a library to react.

With Substance.Component we created a much less smart solution, which fits our needs. At the same time, we don't think it is a good idea to replace react in greater applications. Instead, you should make a Substance based editor component as a library, and integrate it into your react application as you would do with other third party libs.

HTH

**Comment by obuchtala** [comment]
With beta2 we will ship examples showing how to achieve a smooth integration into a react app.

**Comment by michael** [comment]
What Oliver said. Another reason was that React did not let us operate on text-node level, so we had to wrap all our text fragments in spans. For a text editor at that scale we need to have complete control over the rendering.

I plan to write up documentation for Substance Component, and how it differs from React and what backed our decisions. 

Regarding integration: We are actually in some collaboration where the host app will be React, and the editor Substance (Lens Writer).

**Comment by jasonphillips** [comment]
Thanks for the detail, that makes sense and helps a great deal in getting a picture of where things are going and the reasoning behind it. It sounds like I'll need to just aim for smoothly integrating substance within a component in my use cases as you suggest. I'll be particularly interested in figuring out how best to pass down an existing context to make available to custom editor components within Substance, so that the user could, for instance, insert a reference to something that ultimately pulls its content from a parent's getChildContext somewhere upstream in my app. But it looks like something similar is what already goes on with Lens Writer and managing citations, etc., so I'll watch that development. Thanks again.

**Comment by michael** [comment]
Closing this. @jasonphillips we will provide basic API docs for our Component API with the Substance Beta 2 relase.

**Comment by siuying** [comment]
@oliver---- @michael Sorry to bring up old issue, but is the example to integration with React app included in beta3? I'm looking exactly this.

**Comment by michael** [comment]
@siuying See here: https://github.com/substance/lens/blob/master/ReactLensWriter.js. That's how you can wrap things into a React class.

**Comment by siuying** [comment]
Awesome, thanks!!
