### ISSUE TITLE
willReceiveProps is called initially

### ISSUE THREAD

**Issue by michael** [substance/substance#561]
There's a danger of triggering some action twice, though didMount and willReceiveProps if not guarded. I would expect that willReceiveProps is only called if the component already exists, otherwise didMount can be used.

``` js
  this.didMount = function() {
    // load the document after mounting
    this._loadDocument(this.getDocumentId());
  };

  this.willReceiveProps = function(newProps) {
    if (newProps.documentId !== this.props.documentId) {
      this.dispose();
      // TODO: Use setState instead?
      this.state = this.getInitialState();
      this._loadDocument(this.getDocumentId());
    }
  };
```

**Comment by michael** [comment]
Actually now that I look closer, what we probably need is a `willMount` hook to complement `didMount`, so we have a chance to compute derive state before the initial render is performed.

**Comment by michael** [comment]
We could also decide to use the existing semantics but then we should call loadDocument only on willReceiveProps.

Related: https://facebook.github.io/react/tips/componentWillReceiveProps-not-triggered-after-mounting.html

**Comment by obuchtala** [comment]
This is not done anymore.
