### ISSUE TITLE
Predefined and managed node component props

### ISSUE THREAD

**Issue by michael** [substance/substance#564]
We need some predefined props that are managed and set by the Surface for our editor components. The contract is that those are set appropriately whenever a component is used inside a surface.

Here's a the use-cases I identified so far:

`active`: e.g. when a cursor is inside an annotation we could propagate an active property. This could be used to display a small info box while editing a link.

![image](https://cloud.githubusercontent.com/assets/2931/14655968/339ce612-0685-11e6-8029-763702aa4786.png)

`highlighted`: this must be se explicitly by the app. E.g. highlighting all citations of a figure. If a component supports the highlighted prop it will typically attach a modifier class that 'highlights' the node.

![image](https://cloud.githubusercontent.com/assets/2931/14656180/4ab82892-0686-11e6-876f-36b4380f1185.png)

**Comment by obuchtala** [comment]
Dunno if that is the way to approach it. Will be discussed in beta 5.
