### ISSUE TITLE
[Feature Idea] Text Substitutions

### ISSUE THREAD

**Issue by jacwright** [substance/substance#567]
When the user types text that matches pre-defined expressions it will automatically get replaced. Some examples would be:
- Typing `*` + space at the beginning of a paragraph will change it into a bullet list
- `1.` + space converts into a numeric list
- Two dashes will convert into an `emdash`
- `#` + space converts into an `h1`
- other markdown shortcuts such as `>` + space at the start of a paragraph for a block quote
- auto-linking URLs

**Comment by Integral** [comment]
Hey,
sounds like #534 and #413...
We have commander branch with that feature, but not at the best shape.

**Comment by jacwright** [comment]
Yes. I _did_ search for existing stories that might cover this but couldn't find any. In my defense they are not named very well. 😄  I would say #413 is about a different issue with text substitutions only being mentioned. But this is a duplicate of #534 for sure.

**Comment by obuchtala** [comment]
Agree that our issues are not named well ;)

We named this feature set keyboard macros, being part of beta4.
