### ISSUE TITLE
Problem with refs

### ISSUE THREAD

**Issue by michael** [substance/substance#57]
There seems to be some bug with the ref mechanism that hit me when bringing highlights back for the Scrollbar.

From scrollbar.js render:

``` js
      var highlightEls = this.props.highlights.map(function(h) {
        return $$('div').ref(h)
          .addClass('highlight');
      });
```

E.g. when in the first run ref is set to `topic_annotation_1` and in a next run `topic_annotaton_2` is in the highlights the `this.refs['topic_annotatoin_2']` is not available.

You can reproduce using the substance/demos#topic-writer branch. Then:
- Put cursor in the first topicref (highlight is correct)
- Put cursor in second topicref (the ref is not available, see warning on the console)

@oliver---- could you investigate?

**Comment by obuchtala** [comment]
Could you make it a failing test case?

**Comment by michael** [comment]
Working fine now! Thanks a lot.
