### ISSUE TITLE
Cmd/ctrl+k should trigger link command

### ISSUE THREAD

**Issue by dannelundqvist** [substance/substance#572]
Currently the link command/tool is triggered by **cmd/ctrl+l**. This is normally used to focus the address bar in the browser.

More common is to use **cmd/ctrl+k** to trigger link insertion.

**Comment by michael** [comment]
Fixed via https://github.com/substance/substance/pull/582/files#diff-16ce8392834e7de5bcf8302dbfde48dcR514

Btw, we have also generalized the overlay feature and made it a core API. #586 

Will all land in beta 4.
