### ISSUE TITLE
Non-deletable content

### ISSUE THREAD

**Issue by michael** [substance/substance#573]
We should think of a concept to make individual nodes immortal. E.g. When a selection wraps an immortal node, reject the delete transformation.

**Comment by obuchtala** [comment]
Ok, your suggestion seems to be at least feasible, i.e. vetoing the whole transformation. Challenge is how to communicate that to the user.

Needs more discussion, thus shifting to beta 5.

**Comment by obuchtala** [comment]
I don't believe in that.
Undeletable content should go into a separated surface.
