### ISSUE TITLE
embed code hilighting

### ISSUE THREAD

**Issue by benoitc** [substance/substance#574]
Is there a way to insert hi-lighted code content in a container?

**Comment by michael** [comment]
There are many ways. You'd need to implement your custom code node and component and use your own highlighter. It's also possible to integrate an existing code editor (such as CodeMirror). However, there are some issues where keyboard events bubble through to the Substance editing surface. We are working a feature called 'isolated-nodes' to solve that. It will come with beta 4 this month.

**Comment by benoitc** [comment]
Thanks for the answer. Sorry I have been traveling today. 

"implement your custom code node and component " do you have any link about it? Integrating codemirror would indeed do the trick somehow... If I can test some preview code that would be fine for now I  guess :)

**Comment by michael** [comment]
We have an example for this now.

https://github.com/substance/examples/pull/18
