### ISSUE TITLE
Clone props in $$ to avoid accidental changes to original data

### ISSUE THREAD

**Issue by michael** [substance/substance#576]
Will follow up with a failing test.

**Comment by michael** [comment]
See #577 for a failing test.

**Comment by michael** [comment]
Once this is done I can remove a bunch of hacks. Please don't let me forget.

**Comment by obuchtala** [comment]
Could u document some of those hacks? makes this more important than it sounds initially.

**Comment by michael** [comment]
Phew, now that you ask... I had the problem with tools where i had to clone the props.. but since tools are no longer a wrapper component we don't have the problem there.. There was a different place but need to find now.

**Comment by michael** [comment]
Ah look at ProseEditorTools And ScientistWriterTools.

E.g. here:
https://github.com/substance/substance/blob/devel/packages/prose-editor/ProseEditorTools.js#L22

**Comment by obuchtala** [comment]
Ok.

The desired change is to clone props in `$$` so that we don't accidentally change external data.

**Comment by obuchtala** [comment]
Fixed.
