### ISSUE TITLE
tab key handling

### ISSUE THREAD

**Issue by benoitc** [substance/substance#578]
It seems that the tab key is not handle in substance editor (at least the examples). Is there a way to catch the key? and then indent appropriately?

**Comment by benoitc** [comment]
(edited to be more clear)

**Comment by michael** [comment]
That's correct. we would rather have the tab key for accessing other editable areas rather than using it for indentation. This may only make sense within lists (including shift+TAB for dedent).

**Comment by obuchtala** [comment]
We will add better keybinding customizations in the next cycle #49

**Comment by obuchtala** [comment]
This is working now, i.e. that the DOM selection is mapped after pressing TAB. 

> Note: still there is no consistent usage of `tabindex` which would be necessary for better accessibility.
