### ISSUE TITLE
Introduce getDefaultProps

### ISSUE THREAD

**Issue by michael** [substance/substance#579]
It would be nice to be able to specify default props for our components, so we can merge the defaults with the actual props provided by the parent. This would be useful for the new Toolbar implementation for instance.

**Comment by michael** [comment]
for setProps: extend({}, defaultProps, props);
for extendProps: extend({}, oldProps, props);

**Comment by obuchtala** [comment]
Shifting to beta 5.
We also should discuss the optiont that `willReceiveProps()` could return an object allowing to override the props.
