### ISSUE TITLE
Mistake in DocumentEngine tests

### ISSUE THREAD

**Issue by Integral** [substance/substance#583]
@michael,  [here](https://github.com/substance/substance/blob/master/test/collab/testDocumentEngine.js#L42) we call getDocument with string argument, while [it should be args object](https://github.com/substance/substance/blob/master/collab/DocumentEngine.js#L90)

**Comment by michael** [comment]
True! Can you fix and open PR (based on devel branch). I'm currently in overlay business.

**Comment by Integral** [comment]
yes, but let's collect more issues

**Comment by michael** [comment]
@Integral can you take care of the Collab tests and smooth things so we are good for beta 4 here.

**Comment by michael** [comment]
??!

**Comment by Integral** [comment]
almost done

**Comment by Integral** [comment]
https://github.com/substance/substance/pull/677

**Comment by obuchtala** [comment]
This is done
