### ISSUE TITLE
Implement getBoundingClientRect(els, relativeEl)

### ISSUE THREAD

**Issue by michael** [substance/substance#584]
Working on overlay positioning I realise offset calculations etc. have not yet been implemented in a generic robust way. I propose the introduction of a utility method `getBoundingClientRect` that works very similar to native `Element.getBoundingClientRect` but:
- allows multiple elements being passed (we need this for selections that consist of multiple selection fragments)
- takes a `relativeElement` (a parent of els) that is used as a reference point, so we get coordinates relative to that parent, instead of relative to browser's viewport.

The following sketch illustrates a situation where we have a scrollpane (a container with overflow: auto) that consists of a `.content` element. Given an arbitrary scroll position and a selection (expressed as one or more spans) and we want to determine the bounding rectangle relative to the `.content` element. The blue lines shows the result of the native implementation, the yellow lines are the expected result.

![image](https://cloud.githubusercontent.com/assets/2931/15425415/85464858-1e88-11e6-8a94-89834904db96.png)

Example usage within Surface:

``` js
var panelContentEl = this.context.scrollPane.refs.content.el;
var selFragments = nativeEl.querySelectorAll('.se-selection-fragment');
var rect = getBoundingClientRect(selFragments, panelContentEl);
```

Result should look like that:

``` js
{
  top: 700,
  left: 50,
  bottom: 500,
  right: 30,
  width: 320,
  height: 150
}
```

**Comment by michael** [comment]
Additional notes:
- I think we should use `Element.getBoundingClientRect` as a baseline in the implementation and compute the relative pos by summing up the offsets of the offsetParents. The nice thing about that approach is that it's robust against border, margin etc. stuff.
- possibly we should have an internal function that just takes one element and the exposed function will just compute the enclosing rect based on union of the individual rects.

Resources:

http://stackoverflow.com/questions/442404/retrieve-the-position-x-y-of-an-html-element
http://javascript.info/tutorial/coordinates

@joe-loco will take over this.

**Comment by michael** [comment]
Maybe helpful to test against different example layouts (toolbar on top, border margin, scrolling container vs scrolling body etc.). While this sounds like a simple task the challenge is to cover edge cases and to ensure that when the code is changed nothing breaks. These visual things are so terrible to reproduce. I'm not sure what the best approach would be, but having a way to automatically test different scenarios would be great. Not sure if we can fit this into a qUnit test easily...  but maybe a page can be setup that covers different situations then programatically change scroll positions and log errors if the results are different from the expected ones.

**Comment by michael** [comment]
Ok the blue lines are actually not correct. getBoundingClientRect describes the rectangle using the distance from top-left. However, for positioning it would be better to have right represent the offset to the right bound of the container (much like css absolute positioning). That way the overlay can decide how much space is available to the right of the bounding rect.

I guess we will rename the custom function so it does not get confused with the semantics of getBoundingClientRect. How about `getRelativeOffsets(els, relativeEl)`?

**Comment by philippamarkovics** [comment]
+1 for `getRelativeOffsets(els, relativeEl)`

**Comment by philippamarkovics** [comment]
I left some thoughts on the function name in #596.

Also, I changed the default position for overlays to be aligned to the center/top of it’s corresponding selection. I’d argue that this is better because the default writing direction direction is ⬇️ and that, by default, leaves more space above the cursor. This, of course, is absolutely untrue in many situations and I guess, in the end, it just felt nicer to me 😸. If there’s no way around it, I can move it back to center/bottom, of course.

**Comment by michael** [comment]
Closing this in favor of #596
