### ISSUE TITLE
Improve setHighlights API

### ISSUE THREAD

**Issue by michael** [substance/substance#60]
We should improve this.

I was adding the Highlights API to Document for the following reasons:
- in initial call of handleStateUpdate I don't have access to the focussedSurface
- if you had two surfaces displaying different containers we would have to distribute the highlights accordingly on the two surfaces.
- volatile highlighted are also in doc scope

I'm aware this is not exactly correct. We could solve this by adding this API to the SurfaceManager, then we could distribute the changes to the right Surfaces. Scrollbars would listen to the surfaces they are attached to and only get node highlights that are actually present in the container. Other ideas?

**Comment by michael** [comment]
Can you explain how we could make use of the new TextProperty change dispatcher you mentioned?

**Comment by obuchtala** [comment]
Actually, I am not sure yet. But the basic idea is to have one place where we can push things to text property components, making them less self-organized.

I have this currently here:
https://github.com/substance/substance/blob/numerical-addressing/document/text_property_manager.js
https://github.com/substance/substance/blob/numerical-addressing/surface/surface.js#L34

Let me extract this from the numerical-addressing PR. Then you can play around with it and improve.

**Comment by michael** [comment]
The highlights API is currently implemented on Document. I think I could move this into the UI scope to Controller. Is this good enough for a beta 2 iteration? It's a bit hard for me to see all the use-cases we need. It could also make sense to have this on the surface level for more control. What do you think?

Currently we use this API in handleStateUpdate but it could be used in other places as well.

**Comment by michael** [comment]
I think the implementation should be integrated into TextPropertyManager but I don't want to burn my fingers with that given we want to get the beta out soon. I would take care of the interface part first and get this out of document, into either Surface or Controller.

**Comment by michael** [comment]
Actually we first need to define what a **Highlight** is:

Currently `doc.setHighlights()` sets a list of node.ids (globally, means document-wide) and then the component of that node renders a highlighted class. We only have this implemented on AnnotationComponents so far. This is not a really general concept yet. It just does the job for the Lens highlighting.

We should also think of how we do other kind of 'highlights' namely rendering a cursor or selection in a multiuser scenario. In that case no node exists that could be 'highlighted'. So in addition to node highlighting we may want to highlight something based on a given selection.

My feeling is we should together iterate on this as part of beta3.

Maybe even I leave everything as is for now.. thoughts?

**Comment by michael** [comment]
@oliver---- we shift this to Beta 3? And do it proper.

**Comment by obuchtala** [comment]
:+1:

**Comment by michael** [comment]
Mostly done now. We should just get rid of the event mechanism on DocumentNode to propagate highlight changes.

``` js
  this.setHighlighted = function(highlighted, scope) {
    if (this.highlighted !== highlighted) {
      this.highlightedScope = scope;
      this.highlighted = highlighted;
      this.emit('highlighted', highlighted);
    }
  };
```

The `.sm-highlighted` class should be set by the system automatically (e.g. within TextPropertyManager).

**Comment by michael** [comment]
Merged some more changes. Highlights are now managed in a separate class that gets passed to a ScrollPane on construction.

@oliver---- you want to have the highlights-aware TextPropertyManager be part of the beta?

**Comment by obuchtala** [comment]
Not critical, shifted to Beta 4.

**Comment by michael** [comment]
Close in favor of #785
