### ISSUE TITLE
Source Code Documentation? Composer in the Browser?

### ISSUE THREAD

**Issue by ghost** [substance/substance#600]
I'm interested in using Substance as the single source of truth for my all of project documentation including source code comment documentation. I plan to create a tool to walk the JavaScript source AST and use the Substance API to create the stubs. But I wanted to ask, has anyone previously used Substance for source code documentation?

Also, is it possible to run Composer directly in a browser? Because sometimes I'm working on a Chromebook. :-)

**Comment by michael** [comment]
We use Substance for generating Substance API Docs. Did you see: http://substance.io/docs?
