### ISSUE TITLE
Bring list of annotations upward in the document schema

### ISSUE THREAD

**Issue by zampino** [substance/substance#607]
Hallo substance team,
I have the following issue with annotations
while attempting to write an Elixir Renderer (HtmlExporter) for substance document.

Let's say I have the following document produced by a substance editor:

``` json
{
  "schema": [
    "myDocumentSchema",
    "0.1.0"
  ],
  "nodes": {
    "body": {
      "type": "container",
      "id": "body",
      "nodes": [
       "id_1",
       "id_2",
       "id_3"
      ]
    },
    "id_1": {...},
    "id_2": {...},
    "id_3": {...},

    "annotation_id_1": {...},
    "annotation_id_2": {...}
  },
}
```

At present, when I want to _apply_ annotations to the nodes listed in the _manifest_ at `/nodes/body/nodes`,
I have to **scan all nodes** at `/nodes` and for each `(id, nodeObject)`, _if_ `nodeObject` is an annotation,
then apply it to the target node specified by the `nodeObject.path` property.

Now, when having a lot of nodes this approach might become unpractical.

Is there a way to have my document schema
**explicitely listing annotation ids**
in a way that I can pick exactly those nodes upfront and let them act on the others, e.g. as per

``` json
{
  "schema": [
    "myDocumentSchema",
    "0.1.0"
  ],
  "nodes": {
    "body": { ... },

    "annotations": {
      "type": "annotation_list",
      "id": "annotations",
      "nodes": [
        "annotation_id_1",
        "annotation_id_2"
      ]
    },
    "id_1": {...},
    "id_2": {...},
    "id_3": {...},

    "annotation_id_1": {...},
    "annotation_id_2": {...}
  },

}

```

Is there a way to tell substance to include such list in the schema?
I might well have overseen some detail, maybe in the documentation?
Would it be worth considering it a feature?

Cheers,
Andrea

**Comment by mk** [comment]
We're discussing persisting an XML-file format like in http://substance.io/lens/data/example-doc.xml for articles.

**Comment by mk** [comment]
@zampino we're using the internal representation of substance documents at the moment. In javascript you'd have such helper functions available.

**Comment by michael** [comment]
Let's discuss this stuff in person on next meeting.
