### ISSUE TITLE
Container.hide should delete all occurences of nodeId

### ISSUE THREAD

**Issue by michael** [substance/substance#610]
Currently we only remove the first occurence.

**Comment by michael** [comment]
This would have weird semantics, in an editor where the same paragraph is present multiple times.. E.g. your selection wraps the first occurence of it. Then the second occurence would magically disappear. What we could discuss instead is not allowing to show the same node twice in a container.

**Comment by michael** [comment]
@oliver---- Have a feeling we should not be restrictive here, and app devs must ensure consistence. However what is weird is that when you have multiple occurences a .hide(nodeId) just deletes the first occurence even if a later occurence was affected by a selection.

**Comment by obuchtala** [comment]
I agree.
Don't like magic, but then is something missing as you said.
Let's discuss in the next cycle. ATM it is not relevant, as we never have the same id twice.

**Comment by obuchtala** [comment]
We don't like having the same node more than once. So this is kind of undesired.
