### ISSUE TITLE
Improvements for getBoundingClientRect

### ISSUE THREAD

**Issue by michael** [substance/substance#612]
Follow up of https://github.com/substance/substance/pull/596

Comments:

span in the middle: maybe you can use span.getBoundingClientRect() there too, instead of el.offsetLeft? And then subtract the parent rectangles from it until relativeEl is reached? (but likely overlooking something here)
toArray seems useful. just wonder it's necessary here as lodash/forEach should be able to iterate over NodeList ClientRectList etc. Haven't tested but is lodash/toArray able to do the same trick?
top-center positioning of overlay: Fine with that. My only concern would be the edge case when you are selecting on the very top of a container and the overlay would not fit above the selection. I guess we would need to detect that case and position the overlay below.
👍 for getRelativeBoundingRect!

Let me know when this is ready to merge (we can push the test suite into a separate task) want to do naive click testing first. ;)

**Comment by michael** [comment]
@joe-loco we are planning to release beta 4 today. What's missing to finish this positioning stuff? Should I push this issue to beta5 or are we already good and can consider this done. 

Btw, today is a good day to help us find bugs and have them fixed.. just checkout examples#devel and report :)

**Comment by philippamarkovics** [comment]
Apart from missing tests, this should be good to go for beta 4. 

> Btw, today is a good day to help us find bugs and have them fixed

I hope I can find some time later today but can’t guarantee. I do plan to upgrade our own codebase to the latest devel version later this week, though.

**Comment by michael** [comment]
OK I will have another look and then close this issue. Btw, we adapted the dark style for overlays. Actually the overlay no longer has any style but the position. Instead there's a new Prompt component that sits inside the overlay.

OK. Just let us know if you find bugs.

**Comment by michael** [comment]
Will do a final iteration on this now.

**Comment by michael** [comment]
Fixed via https://github.com/substance/substance/commit/8a30140ed433ed2daf12df78dce3f2baf11e788b
