### ISSUE TITLE
stage.transaction does not pass Info object

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#613]
Not critical but inconstent.

**Comment by obuchtala** [comment]
change.info is wrong

**Comment by Integral** [comment]
what do you mean by wrong?

**Comment by obuchtala** [comment]
It's just that during the transaction the `info` object is not provided.
Not really critical, because the info object is designated for use in the handlers after document change. Still it should be there, for sake of consistency... no use case though, just was confused during debugging...

**Comment by obuchtala** [comment]
BTW, we are introducing `info.action` which helps to see what a change means semantically. I.e., when you type, `change.info` should contain the action `type`, so it gets easier to activate macros for instance only in that situations.

**Comment by obuchtala** [comment]
... as opposed to paste or remote changes.

**Comment by Integral** [comment]
Ok... what are the names of other actions?

**Comment by obuchtala** [comment]
Whenever you call surface.transaction you can provide such an Info for disambiguation... E g. break or paste...

**Comment by obuchtala** [comment]
We already had Info.replay for undo/redo

**Comment by obuchtala** [comment]
So, it is pretty open, as it is optional

**Comment by Integral** [comment]
Yep, we have smth like that with collab stuff. But my question what other
contracts we have for action names... it's optional but macro manager
already use concrete name for typing. Maybe you have another names already
for deletion etc...

**Comment by michael** [comment]
Status of this?

**Comment by obuchtala** [comment]
not critical.. internal.
