### ISSUE TITLE
Should we flatten substance/model?

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#620]
While we had the feeling it would be good not to clutter the root folder, I start disliking to write `substance/model/transform`.

We could either pull `model/data` and `model/transform` out or flatten it into substance/model.
Personally I would prefer `substance/data` and `substance/transform`

@michael what is ur opinion?

**Comment by michael** [comment]
We can do substance/data and substance/transform. I have no objections.

**Comment by obuchtala** [comment]
Maybe that's one step too far: `substance/model` -> `substance/document` ?

**Comment by michael** [comment]
Probably. I mean nothing holds us back from bringing the node-modules we had previously into the root folder but not particularly sure about this one. What would remain in model then?

**Comment by obuchtala** [comment]
Looking at `substance/model` it contains mainly Document related stuff. Some others such as `Fragmenter` could go into util.

**Comment by michael** [comment]
Mhh i guess i would just miss this model vs ui thing..  mhh but that's gone anyway now we have transform on top level.

**Comment by obuchtala** [comment]
We should at least sleep one night over it ;)

**Comment by obuchtala** [comment]
Or we do it later on...

**Comment by michael** [comment]
I'm also not sure regarding the collab folder. We have a server vs. client dimension now also. And the structure in test is not consistent anymore. Maybe we should dedicate a day next week for restructuring.

**Comment by obuchtala** [comment]
I am flattening tests right now, because there we have a lot of `../../../../../` which is b***t.
For tests I want that `../..` is root, so it is only one level deeper than the regular source files.

**Comment by michael** [comment]
+1

**Comment by obuchtala** [comment]
For the top-level folders we can wait.

**Comment by obuchtala** [comment]
BTW, collab is not only about server, as you could do p2p and make a client a master.

**Comment by Integral** [comment]
btw don't you want to get rid of qunit?
it's really boring. i can't see any reason to use it except already written
tests...

**Comment by obuchtala** [comment]
I agree. Let me finish this iteration. Then we start planning how to migrate.

@Integral have u time to figure out how to do it with mocha? Just a clean-room example somewhere.
We need to have that UI driven test suite, plus nodejs (which is obvious with mocha).
Also we need to know how to run the mocha driven UI suite from within karma.
That's unfortunately a bunch of requirements...

**Comment by obuchtala** [comment]
@michael another thing to think about: should tests for a package not live in the package, too?

Edit: as I read it, I don't think that is necessary. Tests for other folders/modules are also not there...

**Comment by Integral** [comment]
well... first of all, as I understand, QUnit is just an outdated thing. not
sure, but I have a feeling that there is no features in QUnit which you
cant find on other modern frameworks.
There is no problem to execute mocha within karma. Don't know nothing about
mocha driven UI test suites, but pretty sure that it is possible.
if you want i could prepare some small package, like with 2 tests for basic
and UI things.
regarding dependencies... you already drown inside dependencies ;) but
that's a dev stuff, isn't it?)

**Comment by obuchtala** [comment]
That would be great!
Yep, devDependency -- we can have as many we need ;)

**Comment by michael** [comment]
Please also evaluate tape. It's from the browserify maker.

https://github.com/substack/tape

https://medium.com/javascript-scene/why-i-use-tape-instead-of-mocha-so-should-you-6aa105d8eaf4#.kjrsjvt50

**Comment by obuchtala** [comment]
`tape` looks interesting. Very simple.
Also found this: https://ci.testling.com/guide/tape
It seems that it comes without UI, though. Just using browser's console.

https://github.com/substack/testling

**Comment by Integral** [comment]
will play with both in a branch

**Comment by obuchtala** [comment]
Cool! Thx!

**Comment by Integral** [comment]
But before, let's just summarise what we need (pls, add something or
correct me):
1) test code with linter
2) test code with node
3) test code in different browsers
4) test code in different devices (desktop, tablets, phones etc)
5) run tests directly in browser and receive report
6) test coverage report
7) run tests on CI servers

is it correct?

**Comment by obuchtala** [comment]
1. Linter is working already - so no need for that.
2. yes
3. yes (we were using karma for that particularly only testing for FF and Chrome on Travis)
4. future (so no prio)
5. yes, because that's the env where we are actually fixing things
6. yes
7. yes (but ok if only Chrome and FF, Edge is just too big an effort --  would need a different CI

**Comment by obuchtala** [comment]
2 vs 3: there are some ui tests we exclude when running in node.. but this actually done from within the test by guarding with `inBrowser`.

**Comment by obuchtala** [comment]
5: and it should run in like browserified served setup... debugging in karma is not an option.

**Comment by obuchtala** [comment]
finally: would be good to start the automated tests from gulp, while 5) should still be just served by `server.js`.

**Comment by Integral** [comment]
so you want to run tests and debugging inside concrete browser, but still
want to have some tool which will emulate browsers and run all tests inside
them one after another, right?

**Comment by obuchtala** [comment]
correct :)

**Comment by obuchtala** [comment]
plus of course: running the tests in nodejs to make sure the server side stuff (including server side rendering) is working.

**Comment by Integral** [comment]
Well, didn't try anything yet, but looks like tape could be very useful
here as you can bundle test (browserify) and then debug it in browser.
Regarding automated browser tests looks like there is no better way then
karma... There are couple of other tools like zuul (
https://github.com/defunctzombie/zuul) or smokestack (
https://github.com/hughsk/smokestack), but karma works with biggest number
of browsers... Of course there are external tools like browserstack or
sauce labs, but I think we must do it firstly ourselves...

**Comment by obuchtala** [comment]
Ok!
Do u think that tape bundle can be run in karma?
As I understand karma needs kind of an adapter which is starting the test and providing the result to the karma API.. but don't know for sure.

**Comment by Integral** [comment]
There are karma adapters for tape, no worries!
But I mean running test suite and debugging inside individual browser. E.g.
automated tests will tell you that something wrong with chrome and then you
could open special test bundle in chrome and debug! At least I hope so ;)

**Comment by obuchtala** [comment]
Yep. That is essential :)

**Comment by Integral** [comment]
Btw, do you know anything about this thing?
http://seleniumhq.github.io/selenium/docs/api/javascript/

**Comment by obuchtala** [comment]
I am not sure... selenium is a brutal heavy thing. But if u think that is feasible than take a look.

**Comment by obuchtala** [comment]
I don't think we would pull that in as dev dependency, just to run it on CI.

**Comment by obuchtala** [comment]
maybe... https://www.npmjs.com/package/selenium-standalone

**Comment by obuchtala** [comment]
As I understand, karma is there to offer a more lightweight alternative. Still, I would not say karma is light-weight. And I also understand, that karma is not helping us much to produce real browser events, as a user would produce. Maybe selenium is able doing that. (which is one thing I really miss, because right now we can't really test the ui as we can't produce native UI events.)

**Comment by Integral** [comment]
Can't say anything. Never used it. But agreed that it is a brutal thing :)

**Comment by Integral** [comment]
interesting: https://github.com/juliangruber/tape-run

**Comment by Integral** [comment]
also: https://theintern.github.io/intern/#what-is-intern
https://github.com/jquery/testswarm/wiki

**Comment by Integral** [comment]
and finally local testling: https://github.com/substack/testling (but it
looks like abandoned...)

**Comment by obuchtala** [comment]
testlng really seems to be stalled. No option.

**Comment by obuchtala** [comment]
what about a mocha based solution? do u think that is ok as well?
or do u think tape-run is it?

**Comment by Integral** [comment]
Yep. This would be ok, there is karma adapter for mocha of course.
But tape seems to be much lightweight. I would say that the challenge is to
replace karma with somewhat easier...
Btw, do need installed browsers for karma?

**Comment by obuchtala** [comment]
karma needs the browsers installed yes.
Actually, I don't have much hope to get rid of karma.
Do you think we can achieve all we said with karma and tape?
I would then opt for this combi

**Comment by Integral** [comment]
There is https://github.com/tmcw-up-for-adoption/karma-tap
but this project isn't maintained anymore and it's not clear whatever or
not it will work

Regarding karma... if everything we want from karma is ability to run tests
in browsers than it might help us: https://github.com/juliangruber/tape-run

**Comment by obuchtala** [comment]
Alright, let's try tape-run :)

**Comment by obuchtala** [comment]
And if that not working we can go back to karma - i understance adapters are not difficult: https://developers.soundcloud.com/blog/writing-your-own-karma-adapter

**Comment by Integral** [comment]
Yep, and there is already adapter for tape here:
https://github.com/tmcw-up-for-adoption/karma-tap/tree/master/src
but look, they do it with tap parser which is soooo big:
https://github.com/tmcw-up-for-adoption/karma-tap/blob/master/src/tap-parser.js

**Comment by obuchtala** [comment]
The size is actually not a problem, I think.

**Comment by Integral** [comment]
Mmmm, it is a problem actually! Just imagine that you need to find a bug
inside parser which consists of 16k of lines! Ahhh. It would be just a
black hole in terms of understanding what's going there.

**Comment by Integral** [comment]
But... less talk, more work... I mean, let's try!

**Comment by Integral** [comment]
Hey!
Looks like I ported whole test suite to tape.
Checkout `test-env`, do `npm install` and then `gulp test:tape`.
Of course there is a room for some improvements... But will describe later, now i need to switch for other things. Woooo! ;)

**Comment by obuchtala** [comment]
Whoot!

**Comment by Integral** [comment]
let's continue in separated issue (#625)
sorry for such a big off topic :)

**Comment by obuchtala** [comment]
I think we are not motivated anymore.
