### ISSUE TITLE
Improve tests

### ISSUE THREAD

**Issue by Integral** [substance/substance#625]
We want to:
- [x] Test code with linter (eslint, first step of automated tests, before running real tests)
- [x] Test code with node (automated tests)
- [x] Test code in different browsers (automated tests)
- [ ] Test code in different devices: desktop, tablets, phones etc (low priority, automated tests)
- [x] Run tests directly in browser and receive report (needed for debugging, should be served by server.js)
- [x] Test coverage report
- [x] Run tests on CI servers (Chrome and FF are ok)

We have (had) most of these features, but want to improve it.

**Comment by Integral** [comment]
@oliver---- 
So, short report of what we have now in `test-env`.
Basically it's just a port without any significant improvements except that fact that now we are using tape. All taped tests and stuff placed inside tests dir.
Oh, yes! No more fucking QUnit with it's globals and whatever else.
We are still with karma. I did try tape-run, but it looks like they have some issues with opening/closing browsers on OS X and maybe not only there. In fact I didn't have a chance to find that browser closing issues as I didn't succeed with opening them ;) Probably it's related to browser-launcher package, anyway we don't need these platform/browser related problems. And karma works well with tape.

Good news that we have now less chaos inside tests dir. There is only UItest and spy. While UItest must be improved we have a lot redundant things in tests. Like isNullOrUndefined implemented in each module where it used and beforeEach/afterEach turns to setup and teardown functions along with other function which runs that setup then test and then teardown. I think we could generalise all that stuff and place in one module, which contains like our own taper helpers. 
UItest currently skips tests if you are not in [specific] browser. Yeah, you can skip tests in tape!

Downside is that we don't have modules names now. Because there are no modules... While you can nest tests with tape, I don't think we need it: it's dangerous (i saw some issues) and you will not get nesting in console. So we could use console.log() either or own tap reporter... But do we need it? Maybe it's better to prettify a bit test names...

I didn't tackle opening of tests in browsers directly (for debugging)... Could you please describe shortly how are you doing it now?

Also I didn't see coverage reports in gulp now and I think that I saw it before... I could reintroduce it and we could try https://github.com/substack/coverify instead of istambul.

Let's try to define further directions!

**Comment by obuchtala** [comment]
Thx! I will need to take a closer look. Then I can say more :)

**Comment by Integral** [comment]
Take a look then ;) and I will continue!

**Comment by obuchtala** [comment]
Hey @Integral,

in QUnit we use nesting to filter tests / run tests for a certain module, which is useful when u are working on tests for a specific module. But it does not necessarily mean that we need nested tests, maybe just a means to filter tests. To have a prefix in the test description would be nice, right now it is hard to tell in which module a test is implemented.

The UI is really the most important thing for us. Here more details about it:

![image](https://cloud.githubusercontent.com/assets/284099/15886723/da0fb902-2d5e-11e6-912a-44d95b79a18d.png)

A summary is of course just nice. More important, the possibility to select a group of tests or filter tests:

![image](https://cloud.githubusercontent.com/assets/284099/15887288/bad5c48e-2d61-11e6-9fda-98082a53f291.png)

On the one hand this is good to focus, but on the other it is very important, so you can set a breakpoint for the debugger and not get called by other tests you are not interested in.

![image](https://cloud.githubusercontent.com/assets/284099/15887427/85343116-2d62-11e6-970c-6ae38ae07b8a.png)

Totally important is running a single test. E.g. you see the failing test in the summary and can click on its run button to run it solely.

![image](https://cloud.githubusercontent.com/assets/284099/15887509/ee248644-2d62-11e6-8821-c8acfda9766d.png)

![image](https://cloud.githubusercontent.com/assets/284099/15887524/094cfea6-2d63-11e6-9493-c5e81023050f.png)

Essntial for debugging is, that the test runner does not wrap everything into a `try-catch` block, or at least like QUnit provides a way to disable. Otherwise it is not possible to stop on uncaught exceptions - which is one of the most useful things for debugging.

![image](https://cloud.githubusercontent.com/assets/284099/15887622/7f6140c0-2d63-11e6-8e90-7b19d7577b6f.png)

**Comment by obuchtala** [comment]
The current port is looking good. I will leave some comments in the commits.

**Comment by obuchtala** [comment]
I looked into the tape implementation, and think that getting such a UI needs a bit of crafting on our side.
I understand that tap-reporters are not enough for us, as we want to control the life-cycle of the test-harness.
The way it need to be done is to create a custom harness, not using the default harness which is triggered automatically on process exit (which is simulated in the browser).
Then we could have a custom UI and start whatever tests whenever we want.

@Integral I will patch this idea together, and then u could take-over again :)

**Comment by obuchtala** [comment]
@Integral I have prepared the basics for a custom Test UI: 61653fd

Look at https://github.com/substance/substance/blob/61653fd08092093f793f44a95ea0c26ffc925cd2/tests/test.js:

We now have something which wraps `tape` when running in the TestSuite app in the browser.
You could now go on and try to build a simple UI:
https://github.com/substance/substance/blob/61653fd08092093f793f44a95ea0c26ffc925cd2/tests/TestSuite.js

Try to achieve the following:
- run all tests, displaying results
- run a single test i.e. run only
- maybe add a means to filter the set of tests

Happy coding :)
Thx!

**Comment by oliver----** [comment]
@Integral and feel free to ask when u have problems ;)

**Comment by Integral** [comment]
Oh, my God, I didn't even fast enough to answer you

**Comment by obuchtala** [comment]
I have some more ideas:
We could add some more helpers on top of `test` which is returned by `tests/test.js`.
- `test.UI(name, fn)` replacing UITest
- `test.FF(...)`, etc.
- `test.module()` returning something which has the same interface has `test` but adding the module name as prefix and maybe add the information to the Test instance. E.g.

```
var test = require('../test').module('ui/Component');

test.UI('Setting the model selection should update the DOM selection', function(t) {
  ...
});
```

I.e. we would wrap tape, mimicking the same interface and adding some more helpers.

**Comment by obuchtala** [comment]
@Integral are u working on this right now? I saw that your commits are based on a commit which is not in the devel branch anymore (because I had to rebase eslint branch before merging). I would like to fix this.
Let me know, will take just a second

**Comment by obuchtala** [comment]
Just for the records, we will need to port some newer changes in the QUnit tests.

```
> git diff --name-only devel -- test/ test-env | grep .test.js
test/ui/AnnotationCommand.test.js
test/ui/DOMSelection.test.js
```

**Comment by Integral** [comment]
Oli, I have connection troubles, i need to fix them first

**Comment by oliver----** [comment]
No worries. I am now AFK for a bit.. Will be online in the evening again...

**Comment by Integral** [comment]
Hey, I do like what you proposed. I thought about the same.
I think we should also attach generalised method for doing beforeEach and afterEach.
Btw, do we really need afterEach after tearing down all globals..?

**Comment by Integral** [comment]
@oliver---- did you fix a branch?

**Comment by oliver----** [comment]
Did not dare, not knowing if you have an uncommitted changes.

**Comment by Integral** [comment]
Do it please!
Are you available somewhere else?

**Comment by oliver----** [comment]
https://gitter.im/substance/substance ?

**Comment by Integral** [comment]
let's try

**Comment by Integral** [comment]
@oliver---- need help

**Comment by obuchtala** [comment]
This is WIP. The test-suite is already usable, very minimal but debugging can be done.
Continueing this in beta 5.

**Comment by michael** [comment]
So the stuff in test-old is not run atm? Sorry I'm not up to date anymore when it comes to your test suite work ;)

**Comment by obuchtala** [comment]
It's only there so that Daniel can take a look how to rebuild.

**Comment by obuchtala** [comment]
@Integral Let us drop the old one. u might want to checkout an old version just to be able to look at the QUnit based UI.

**Comment by Integral** [comment]
Ok! Do you need PR?

**Comment by obuchtala** [comment]
Always PR :)

**Comment by Integral** [comment]
And may I remove all dependencies? Like QUnit, Sinon etc?

**Comment by obuchtala** [comment]
Great!

**Comment by obuchtala** [comment]
I think the only thing remaining is to improve the TestSuite UI itself.
We don't need to run tests for different devices, as we don't have implemented such yet.
And we might not even need it as we can simulate some things, such as creating mock events (like I do in Clipboard.test.js).

Closing this for now.
