### ISSUE TITLE
Incorrect type of iterator

### ISSUE THREAD

**Issue by Iuriy-Budnikov** [substance/substance#627]
Hey Guys. 
I noticed that if I tring to render one node element I'm getting object instead of array in

```
function ArrayIterator(arr) {
  this.arr = arr;
  this.pos = -1;
}
```

For ex: try to render one item
`<p data-id="paragraph-016ffcd6469ddeac3f93374acd6a2404">fdddf</p>`

```
function ArrayIterator(arr) {
  if (typeof arr.length === 'undefined') {
    this.arr = [arr];
  } else {
    this.arr = arr;
  }
  this.pos = -1;
}
```

**Comment by obuchtala** [comment]
@Iuriy-Budnikov Thx for reporting. I need more to understand fully.

What exactly are you trying to do?

**Comment by michael** [comment]
Closing. Please reopen if you can provide a failing example that we can reproduce.
