### ISSUE TITLE
Incorrect data attribute in export function in example

### ISSUE THREAD

**Issue by Iuriy-Budnikov** [substance/substance#628]
[https://github.com/substance/examples/blob/master/converter/TodoHTMLConverter.js](url)

it should be data-done instead of done in

```
export: function(node, el, converter) {
    el.append(converter.annotatedText([node.id, 'content']))
      .addClass('todo')
      .attr('done', node.done ? '1': '0');
  }
```

**Comment by michael** [comment]
Thanks we will fix this in the Notes app, as we removed the notepad from the examples repo.

**Comment by michael** [comment]
Well actually we don't have HTML serialization there. ;) But thanks anyway for reporting.
