### ISSUE TITLE
Select multiple isolated nodes at once

### ISSUE THREAD

**Issue by michael** [substance/substance#631]
It would be nice to be able to select multiple isolated nodes at once. E.g. with shift+down or shift+click. Then cut and paste them somewhere else. :)

**Comment by obuchtala** [comment]
Should be possible already. Maybe a bug?

**Comment by obuchtala** [comment]
This is working already.

![substance-select-multiple-isolated-nodes](https://cloud.githubusercontent.com/assets/284099/16007772/b0be16ba-3174-11e6-8ff7-5acec1bac2e7.gif)
![substance-select-multiple-isolated-nodes-2](https://cloud.githubusercontent.com/assets/284099/16007814/da45c438-3174-11e6-82ab-cbd56fb9b958.gif)
