### ISSUE TITLE
Inline node selection bugs

### ISSUE THREAD

**Issue by michael** [substance/substance#632]
The latest updates work great. However if I expand my selection from left to right... an isolated node blocks the expansion. From right to left it works.

Also, if two inline nodes follow without any character in between, you can across the first.

**Comment by obuchtala** [comment]
Will pursue this in a dedicated iteration in beta 5.

**Comment by obuchtala** [comment]
Shift-right is not working before inline-nodes.

**Comment by obuchtala** [comment]
This has changed a bit. But still there are glitches.
