### ISSUE TITLE
Feature: Extend expanded selections like in Sublime

### ISSUE THREAD

**Issue by michael** [substance/substance#643]
When double clicking on a word then dragging to the left the selected (doubled clicked word) does not get considered in the selection.

**Comment by obuchtala** [comment]
On Windows this seems to be correct. A double click selects from left to right, i.e., anchor is on the left. It makes sense then that dragging to left does not consider the right boundary.

@michael what do u think?

**Comment by obuchtala** [comment]
I suppose the anchor should be new on the next mousedown. I.e. the previous selection should be irrelevant.

Edit: and that's the way it is done right now. I.e. dbl-click with holding down has the behavior explained above. A new click sets a new anchor wich is correct.

**Comment by michael** [comment]
Yep I just observed how Sublime behaves... as soon as the drag gets recognized it switches the anchor.

![doubleclickanddrag](https://cloud.githubusercontent.com/assets/2931/15993827/8d47f25a-30f2-11e6-8054-a76c053125ac.gif)

**Comment by obuchtala** [comment]
That won't happen soon ;)

**Comment by obuchtala** [comment]
Nothing you could achieve with ContentEditable.

**Comment by michael** [comment]
I use that move a lot. ;)

An untouched contenteditable works as I would expect it.. I wonder what it is what differs in our case, we handle tripple clicks but not double clicks right?

**Comment by obuchtala** [comment]
This would need a different way of handling mouse events, which I think we can try someday, but not now. Currently we map the selection on mousedown. When we start to do a more sophisticated handling, we can try.

**Comment by michael** [comment]
Ah understand. Fine to wait with this.

**Comment by obuchtala** [comment]
Double click and dragging with the second click works, though. Dragging with the third click does not work in Sublime neither.

Seemed to be fixed.
