### ISSUE TITLE
Typing when cursor is on left side of isolated node leads to exception

### ISSUE THREAD

**Issue by michael** [substance/substance#644]
Typing in this situation
![image](https://cloud.githubusercontent.com/assets/2931/15993327/836e81c8-30e2-11e6-8f13-7e378039b800.png)

leads to:

![image](https://cloud.githubusercontent.com/assets/2931/15993332/957e6e3c-30e2-11e6-830f-4e5e83f32952.png)

**Comment by obuchtala** [comment]
True. Not implemented yet.

**Comment by obuchtala** [comment]
We need to specify what we actually want here.

**Comment by obuchtala** [comment]
I don't thing breaking automatically is the right choice. Maybe we just don't allow inserting things here?

**Comment by michael** [comment]
Not sure either. I guess people would expect to be able to type when there is a cursor somewhere. However our cursor is not blinking ;)

**Comment by obuchtala** [comment]
What would u suggest for now?

**Comment by michael** [comment]
I think the breaking would be the better solution. But really fine with blocking too, if it's the easier fix.

**Comment by obuchtala** [comment]
I made transforms more picky regarding type of selections, fixing this bug.
Until we are sure about it, we stick to nop'ing the trafo.
