### ISSUE TITLE
Selection fragment not cleared in some cases

### ISSUE THREAD

**Issue by michael** [substance/substance#646]
In Scientist:

![selectionnotcleared](https://cloud.githubusercontent.com/assets/2931/15994200/a44610de-30fe-11e6-9386-686a62e45385.gif)

maybe a fragmenter or update bug?

**Comment by obuchtala** [comment]
As this is not critical I am shifiting it to beta 5.

**Comment by obuchtala** [comment]
We don't have this anymore.
