### ISSUE TITLE
Error on deletion when multiple paragraphs are selected and last one is fully selected

### ISSUE THREAD

**Issue by michael** [substance/substance#647]
Like this:

![image](https://cloud.githubusercontent.com/assets/2931/15994259/b9b03124-30ff-11e6-9880-7b6805ad237f.png)

Something in fragmenter:

![image](https://cloud.githubusercontent.com/assets/2931/15994263/d01be5ca-30ff-11e6-956b-0a4a353e9f31.png)

**Comment by obuchtala** [comment]
Seems to happen only in the nested editor scenarion, i.e. in examples I don't see it, but can confirm this happending in scientist within a section.

**Comment by obuchtala** [comment]
Fixed via 464586a267c446ab285afe506d9ac7da61c3ce81.
