### ISSUE TITLE
When cursor is at the right of an isolated node pressing backspace fails

### ISSUE THREAD

**Issue by michael** [substance/substance#650]
![image](https://cloud.githubusercontent.com/assets/2931/15995227/cc5c0eac-3117-11e6-9cdd-76a8b1f5dfd0.png)

**Comment by obuchtala** [comment]
Similar as before... I did not know what to do, so the impl is missing

Let's define.

**Comment by michael** [comment]
Hmm. In this case I guess deleting the isolated node is ok behavior?

**Comment by obuchtala** [comment]
deleting or selecting are the two options, i think

**Comment by obuchtala** [comment]
With the trafo's not reacting on such selections we have a NOP behavior right now which fixes this bug.
How to proceed, i.e. implementing a different strategy explicitly, needs to be discussed further.
