### ISSUE TITLE
Firefox: cursor navigation with inline nodes is broken

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#652]
When traversing inline nodes using left/right the DOM selection disappears.

**Comment by obuchtala** [comment]
@michael interestingly this is caused by the overlay positioning too, which injects a span temporarily, destroying the DOM selection. We need to rethink this.

**Comment by michael** [comment]
Argh, too bad. As this would also be the solution for scrollIntoView stuff.

**Comment by obuchtala** [comment]
Pushed a workaround. Rerendering the DOM selection after span insertion. We should optimize that though, as doing the full model->DOM mapping is a bit overkill.
