### ISSUE TITLE
Improve examples

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#654]
From PR substance/examples#21
- [x] Form Example: entity-tool needs an icon then the toolbar will not be offset.
- [x] Input Example: Maybe this should not set the cursor immediately. You will loose the ability to click and select the whole node and delete.
- [x] Focused: alien does not change color
- [x] Table Example: Not possible to insert content into empty cells. Maybe not have them sparse but with empty cells for now

**Comment by obuchtala** [comment]
Focused example works for me:
![substance-focusedexample](https://cloud.githubusercontent.com/assets/284099/16005427/82de2ddc-3167-11e6-8421-8b577f274f47.gif)

**Comment by michael** [comment]
Now Alien also changes color for me.
