### ISSUE TITLE
CSS concatenation through package addStyle definitions

### ISSUE THREAD

**Issue by michael** [substance/substance#658]
Maybe too ambitious for beta4 but should address this soon.

**Comment by obuchtala** [comment]
@michael can u explain again?

**Comment by michael** [comment]
Just this generated main.scss that we talked about (that we pass to node-sass) . But it's not a quick task to do that I'm afraid.

**Comment by obuchtala** [comment]
Ah, I see. Yep. Next round.

**Comment by obuchtala** [comment]
This is done.
Together with #724 we should be fine.
