### ISSUE TITLE
Make bundle of examples

### ISSUE THREAD

**Issue by michael** [substance/substance#668]
Just needs a bit of tweaking I think.

**Comment by michael** [comment]
@Integral could you take this next?

**Comment by Integral** [comment]
Yes, i could. No problems.

**Comment by michael** [comment]
Thanks. We need that for the release. To have all examples at substance.io/examples

**Comment by Integral** [comment]
We could close this issue. Last question, do we need to expose this example? https://github.com/substance/examples/tree/devel/isolated-nodes

**Comment by obuchtala** [comment]
Nope. I was just having this to extract the smaller examples.
Let's drop it tomorrow.

**Comment by obuchtala** [comment]
I think this issue can be closed, as it is working.
We need to adapt it to latest changes but that's ok.
