### ISSUE TITLE
Expose logger via Substance Controller?

### ISSUE THREAD

**Issue by michael** [substance/substance#67]
We currently use dependency injection to connect to a notifications service. We should maybe move this into Substance Controller where users can call a getLogger() method to get a shared logger instance. This would be stuff that is logged into the status bar. So we should not use it as a debugging logger. Rather use console.log for that.

Maybe we should keep the name notifications to make it more explicit an app messaging system. However, the interface logger.log, logger.error, logger.warn etc. seems like something more straight-forward instead of introducing our own user notifications API.

Currently we do:

``` js
notifications.addMessage({
  type: "info",
  message: "Saving ..."
});
```

With the new logger interface:

``` js
var logger = this.controller.getLogger();
logger.log('Saving ...');
```

Thoughts?

**Comment by obuchtala** [comment]
Sounds good.

**Comment by michael** [comment]
I'm in the middle of it. I'm dropping the different occurrences of this.context.componentRegistry, this.context.surfaceManager with the controller interface. I expose it via dependency injection, however I implemented getController() methods whereever possible, to abstract this away.

In practice this means that:

``` js
var ComponentClass = this.context.componentRegistry.get(node.type);
```

turns into:

``` js
var ctrl = this.getController();
var ComponentClass = ctrl.getComponent(node.type);
```

Just a thought: Why not making this.getController a default getter in Substance.Component? Like just indicating it's a known concept. Your component can be controlled by something higher up the component tree.

**Comment by obuchtala** [comment]
Hmmm... so it would be a built-in depency injection? Don't know.
It should always be defined then, and fail as early as possible.
Or do you want to provide a default implementation?

**Comment by michael** [comment]
Sort of, I'm also not sure... but this could make sense in many apps, to separate some data-logic from component logic. Of course if you ever call this.getController() in one of your components and you have not defined one as a child context, it will fail immediately.

Our TextPropertyComponent for instance would rely on a Substance Controller to be in place, so we can do:

``` js
var ctrl = this.getController();
ctrl.getSurface();
```

``` js
var ctrl = this.getController();
ctrl.getController().getComponent('paragraph');
```

**Comment by michael** [comment]
We could also decide to access controller always via `this.context.controller` to indicate this is a dependency injection thing. Not sure..

**Comment by obuchtala** [comment]
I would rather prefer this for now. Then it is really obvious how it works.
At some time we could declare required context properties, and fail automatically if they are not present.

**Comment by michael** [comment]
Sounds good.

**Comment by michael** [comment]
Done via #65.
