### ISSUE TITLE
Don't insert empty paragraphs in insertNode

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#681]
`insertNode` itself uses `breakNode` which is adding a new paragraph, e.g. when at the end of a line.
- we could either check in `inserNode` if really inside a textish (not at first or last) and only then call breakNode
- alternatively, we could add a option to breakNode only breaking inside of text

**Comment by rquast** [comment]
Is this anything to do with htmlexporter exporting ```<p></p>``` rather than ```<br>``` for newlines?

**Comment by obuchtala** [comment]
Done.
