### ISSUE TITLE
Input Example: Annotation tools should be disabled when input field has focus

### ISSUE THREAD

**Issue by michael** [substance/substance#682]

**Comment by obuchtala** [comment]
It should have a NodeSelection in that case. So u should go into the command and disable that case.

**Comment by michael** [comment]
Will do. Thanks!

**Comment by michael** [comment]
Fixed via https://github.com/substance/substance/commit/b0918a4f804517d5b2a81db068b850d1e3c1de8a

**Comment by obuchtala** [comment]
@michael you have broken the build

Either use PRs or do it properly.
When devel is broken, all other PRs will be red as well.
I know it is difficult to open the console and run `gulp lint` ;) but please
