### ISSUE TITLE
TestSuite: try to get rid of t.end()

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#687]
Don't know what the best way is, but it happens to me everytime that I forget to add `t.end()` at the end of a test.
For synchronous tests which are 99% of our tests this could be done automatically.

My suggestion is to add an `test.async()` declaring asynchronous tests explicitly which require that `t.end()` call, and in the other cases doing it automatically.

@Integral what do u think?

**Comment by Integral** [comment]
Let's try!

**Comment by obuchtala** [comment]
Do u like the idea? or any concerns?

**Comment by Integral** [comment]
I also thought that writing t.end() everywhere is a bit boring... We should try to handle it.
