### ISSUE TITLE
Better concept for having different im-/exporters at the same time.

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#70]
In LensWriter, we want to be able to use both toHtml and toXML. 
Both use the basic HtmlExporter implementation.
IMO it is good to have the implementation within the node model class.
However, there should be a better way to have multiple versions.

**Comment by michael** [comment]
Yeah that we need definitely. Since we don't need to make a difference between HTML and XML we could give the methods more generic names. How about `fromSource` and `toSource` and optional for the clipboard `fromClipboard` and `toClipboard`?

**Comment by obuchtala** [comment]
Or making it independent of the class,

```
Converter.extend({
  converter: 'html',
  nodeType: 'heading',
  import: function($el, converter) {
    ...
  },
  export: function(node, converter) {
    ...
  },
})
```

And register them in a converter registry. A converter would then pick all registered for its name.

**Comment by obuchtala** [comment]
While I was voting for having the converters in the same file as the node, I feel now that it would be more flexible to have them in separated files, and making the registration less implicit.
OTOH, this would of course increase the complexity.
@michael what do u think?

**Comment by michael** [comment]
Hard to say really. I like the current minimalism, because defining a new node and specifying from/to converters feels very natural. I'd want to not have things spread over too many files. However, maybe we could come up with a single file for each converter, with multiple extends like these:

``` js
Converter.extend({
  converter: 'html',
  nodeType: 'heading',
  import: function($el, converter) {
    ...
  },
  export: function(node, converter) {
    ...
  },
})
```

**Comment by obuchtala** [comment]
Ok.

Basically, we need a more explicit way to configure a converter, i.e. using a registry for those converters.
We could still have them within the node files by default. And if something needs to be customized then it is done by registration.
I will give it a try and then we can discuss...

**Comment by obuchtala** [comment]
@michael  What do u think about that?

```
Blockquote.static.addConverter(NodeConverter.extend({
  name: 'xml',
  matchElement: function($el) {
    ....
  },
  import: function($el, converter) {
     ...
  },
  export: function(paragraph, converter) {
   ...
  },
})
```

I.e., adding a static API to Document.Node.

Edit: and this block of code would be in the same file as the node usually.

**Comment by michael** [comment]
That's the way!

**Comment by michael** [comment]
We have a new strategy on this.
