### ISSUE TITLE
ui/Overlay should be called OverlayContainer and should be used by default

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#713]
ATM every configuration needs to configure the Overlay class.
While it is good to provide an opt-out, we should still use one default implementation.
Furthermore, it should be called OverlayContainer, as it does not render the overlay itself,
but is just used as a container for positioning. An opt-out could override it to achieve a different styling.

**Comment by michael** [comment]
Agree. I want to add this as part of introducing flow-controlled overlay rendering.

**Comment by michael** [comment]
That's fixed.
