### ISSUE TITLE
Putting cursor into isolated node requires three clicks

### ISSUE THREAD

**Issue by michael** [substance/substance#730]
Would be nice if could be done with 2. E.g. see scientist xref editing.

![isolated-node-cursor](https://cloud.githubusercontent.com/assets/2931/16544753/9b32c64a-4111-11e6-91a8-199987ce16dd.gif)

**Comment by obuchtala** [comment]
Looking into this.

**Comment by michael** [comment]
Not sure if related but in publisher mode the fig captions are not reachable at all. Strange as in general isolated textproperty editors work (as seen in section titles).

**Comment by obuchtala** [comment]
That was a combination of several problems: 
- InlineWrapper didn't set a ref on the wrapped content - making the content wiped, also on mousedown which changes the isolated node state
- IsolatedNodeComponent does now not render the blocker when co-focused. This is the effect that when clicking into a parent isolated node, it does not select the node, but sets the cursor directly. I think this is acceptable for now.

Fixed via #735
