### ISSUE TITLE
Do we want configuration scopes?

### ISSUE THREAD

**Issue by michael** [substance/substance#734]
We are entering a phase when configuration scopes are needed. E.g. in Scientist where we have 3 modes (Publisher, Author, Reader). We want to be able to run different views (which require different configurations) at the same time.

Let's assume we want to create an example in Scientist that let's you hot-switch between Author and Reader. Reader overrides the `RefListComponent` to show a plain html version instead of an editable reflist.
## Scopes

We could achieve that with a single Configurator by introducing scopes (e.g. the reader/package.js) could look like this:

``` js
module.exports = {
  name: 'author',
  configure: function(config) {
    config.import(require('substance/packages/base/BasePackage'), {scope: 'author');
    config.import(require('../jats/package'), {scope: 'author'});
    // override ref-list component
    config.import(require('./ref-list/package'), {scope: 'author'});
    config.addStyle(__dirname, '_author', {scope: 'author'});
  }
};
```

We would then make sure that in the places where the configurator is used, the right scope is provided. E.g. in the ProseEditor implementation depending on the context we need to `configurator.getComponentRegistry('reader')` or `configurator.getComponentRegistry('author')`.

However, I do see some limits here.. and it may happen that we want to solve too many things with a single configurator. E.g. the config API's may differ.. the author has a config.setToolbar method, the reader does not... that's just a minor difference but I don't think it's a good idea to be limited to one configurator api for a whole app.
## Multiple Configurators

Another option would be having multiple configurators for an application.

``` js
$$(Scientist, {
  mode: 'author',
  configurators: {
    author: authorConfigurator,
    reader: readerConfigurator
  }
})
```

That may look a bit more verbose on top level but could be more flexible... E.g. we may want to have app level configuration too (e.g. for setting the backend, or a dashboard component). That's currently also mixed with the ProseEditorConfigurator API. So in order to have everything separate but still convenient we could have a ScientistConfigurator API that has an API to configure configurators ;)
## App Configurator that configures sub configurators

``` js
// myScientist
module.exports = {
  name: 'my-editor',
  configure: function(config) {
     // App level config
    config.setXMLStore(ExampleXMLStore);
    config.addStyle(path.join(__dirname, 'app.scss'));

    // Sub configurations
    config.addConfig('author', MyAuthorConfig);
    config.addConfig('reader', MyReaderConfig);
  }
};
```

Then we would have a single configurator on top level

``` js
$$(Scientist, {
  mode: 'author',
  configurator: myScientistConfigurator
})
```

There's a challenge with multiple configurators. We need to make sure we can combine all different configurations to a single stylesheet. There could be some problems with order, naming clashes and overrides etc. E.g. since both reader and author include the jats package and all sub packages we will get the _ref-list.scss style referenced two times. We would need a way to ensure the reader can replace those styles. Basically it will be tricky if both components used .sc-ref-list. So I guess always using unique names would solve many hassles. E.g. calling it RefListReaderComponent and `sc-ref-list-reader` just registering it as 'ref-list' in the component registry.

Thoughts?

**Comment by obuchtala** [comment]
Ok. Yeah, I was thinking that earlier or later we would need something like this.
In general I see two options: having one component which can be controlled, or registering different components using the 'scope' (which is a hint using current terminology).
Feel free to go ahead, as this is the first time we try to solve that.
After having more experience we will see what approach we like most.

**Comment by michael** [comment]
Having flexible components is an option we always have yep. However when it comes to scopes and using different components, would you tendentially favor the approach with a single configurator, introducing scope bins for registries or rather have multiple configurators (specialized for each use-case)?

**Comment by obuchtala** [comment]
I think I'd prefer one Configurator per application domain, so that it can introduce a DSL of hints.
So would prefer flexibility in packages here... and only one configurator impl.

**Comment by obuchtala** [comment]
What do u think?

**Comment by michael** [comment]
Mhh I think I'd tendentially favour multiple configurators. Main reason being that a single app-domain-specific configurator will get a pretty broad interface. E.g. editor/reader specific packages could call things like setBackend. Also in the top level components (e.g. writer, reader) we would need to call configurator.getComponentRegistry('reader') etc. which makes those components less reusable. I like how far we've got with the ProseEditor interface and it's configuration, which is pretty much the same everywhere.

I'd introduce configurators for the following packages:

author/AuthorConfigurator
publisher/PublisherConfigurator
reader/ReaderConfigurator
scientist/ScientistConfigurator (app-stuff like setXMLBackend etc.)

**Comment by michael** [comment]
for the examples it would suffice to provide a config for the ScientistConfigurator. And only if needed override config for reader, publisher, author, etc. Need to try it out... a stubbed Stencila package+example that affects author+reader would be a good use-case i think.

**Comment by obuchtala** [comment]
I think all those configurators would still need to provide the same API used by the packages - that's what I am calling a DSL defined by the configurator.

You could achieve the same as you want, by using a different package, which would set the XML backend for example.

But, as I said, before.. these are subtle differences - quasi equivalent. I think we should do an iteration and then discuss more.

**Comment by michael** [comment]
hmm... yeah not sure. Author, Publisher, Reader would all use the same API, Scientist would be a different API, no addNode, defineSchema etc, addCommand, etc. on that level.

**Comment by obuchtala** [comment]
Just want to emphasize, that if one package is using a specific method of one configurator, all other configurators will need to provide the same method, otherwise it will not work.

**Comment by michael** [comment]
Understand. I realize that we have editor-ish packages (all our examples) and app-ish packages. Talked with Daniel about NotesApp. There we would want to have packages on app level (a dashboard package, a Noteloader package, a UserSettings package, etc.) those would look fundamentally different (no commands, tools etc.), which was a signal for me we may not want to have a one-size-fits-them-all configurator.

**Comment by obuchtala** [comment]
I think we will not have a configurator that works in notes-app and scientist. But I think all packages in one repo should be compatible regarding configurator API.

**Comment by michael** [comment]
completely agree.

**Comment by Integral** [comment]
I would say that probably we can't use the same configurator for both
projects, but it's better to keep it as much close to each other as it is
possible. The reason is that scientist and other apps which will use
scientist will have the very same problems.

**Comment by obuchtala** [comment]
True. So we should try to use the default configurator/ProseEditorConfigurator from the core package in the notes app.
For the scientist I have not much hope that the default configurator will be enough.
And we should be careful with stretching the default implementation too much.

**Comment by michael** [comment]
My suggestion: Let's do an iteration cleaning up AbstractConfigurator, which only has the core apis. Then let's introduce ProseEditorConfigurator for the prose-ish stuff (e.g. setToolbarClass, setSaveHandler, etc.)

```
AbstractConfigurator
   ProseEditorConfigurator
      scientist.AuthorConfigurator
      scientist.PublisherConfigurator
  scientist.ReaderConfigurator
ScientistConfigurator
```

Rule: Core packages must only use the API by AbstractConfigurator. ProseEditor-ish packages only use that API. Maybe Author and Publisher don't add any extra apis, still we will have two configurator instance to configure author and publisher separately.

**Comment by michael** [comment]
I think using multiple configurators and inheritance is the way to go. See https://github.com/substance/scientist/pull/54. Was able to solve the described issue without any changes to the Substance package API. So we can keep things simple for things like the examples and just introduce a top-level configurator if we need to manage multiple configurations for sub components of a project.

**Comment by michael** [comment]
We are good here. See https://github.com/substance/scientist/pull/54
