### ISSUE TITLE
Fix SplitPane inline examples

### ISSUE THREAD

**Issue by Integral** [substance/substance#746]
https://github.com/substance/substance/blob/develop/ui/SplitPane.js#L18-L24 you missed two commas

**Comment by obuchtala** [comment]
No need to create an issue for typos in documentation.
Just go ahead and fix, or if you want just a PR fixing it. ;)

**Comment by Integral** [comment]
No, I don't want PR for a typo! Could I just fix directly (e.g. without creating a branch etc)?

**Comment by obuchtala** [comment]
Yes please. Just wanted to make clear, that for others the PR way would be the desired one.
For you, just push to develop. That's fine.
But if everybody creates an issue for typos, we would end up with a million issues ;)

**Comment by Integral** [comment]
Blessed day!

**Comment by obuchtala** [comment]
Such things, I often do even just in the github editor.

**Comment by obuchtala** [comment]
Thx :)
