### ISSUE TITLE
ContainerEditor becomes enabled when an IsolatedNodeComponent clicked

### ISSUE THREAD

**Issue by nokome** [substance/substance#760]
I have noticed this behaviour: in a `ContainerEditor` with `disabled: true`, if you click on an `IsolatedNodeComponent` (e.g. an image) then the whole container becomes editable. 

It may just be my setup, but I can try to create an reproducible example, if you like.

**Comment by michael** [comment]
We reworked the isolated node implementation. So this problem shouldn't be there anymore.
