### ISSUE TITLE
HTMLImporter.importDocument unexpected behaviour

### ISSUE THREAD

**Issue by nokome** [substance/substance#765]
I'm instantiating an importer once and using it to import multiple documents i.e.

``` js
// at top of file
var DocumentHTMLImporter = require('../document/DocumentHTMLImporter');
var importer = new DocumentHTMLImporter({ configurator: documentConfigurator });
...
   // somewhere later in a function
    var doc = importer.importDocument(html);
```

But, although `importDocument` resets the `DOMImporter.State` it doesn't actually start with a new empty document. So each time its called, new nodes get added to any existing document. This was unexpected behaviour (too me anyway :smile: ). My fix is to do this:

``` js
    importer.createDocument();
    var doc = importer.importDocument(html);
```

But seems to me, that if it does not break anything else, the `importDocument` method should really start off with a new empty document.

**Comment by obuchtala** [comment]
Fixed via 1052b9bea1aacd3be2d817cbaff272e325ebfd4f
