### ISSUE TITLE
API-Doc iteration

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#798]
From one scan over Texture we should revise the API Docs of these:
- [ ] AbstractEditor
- [x] Annotation
- [x] AnnotationCommand
- [ ] AnnotationComponent
- [ ] annotationHelpers
- [x] AnnotationTool
- [ ] Button
- [x] Component
- [x] Command
- [x] Configurator
- [ ] Container
- [ ] ContainerEditor
- [ ] DefaultDOMElement
- [ ] Document
- [x] DocumentNode
- [ ] DocumentSession
- [ ] DOMElement
- [ ] EditInlineNodeCommand
- [ ] EventEmitter
- [ ] FontAwesomeIcon
- [ ] Highlights
- [ ] InlineNode
- [ ] InsertInlineNodeCommand
- [ ] JSONConverter
- [x] Layout
- [ ] ProseEditor
- [ ] ProseEditorOverlayTools
- [x] ScrollPane
- [x] SplitPane
- [ ] TextBlock
- [ ] TextBlockComponent
- [ ] TextNode
- [ ] TextPropertyComponent
- [ ] TextPropertyEditor
- [ ] TOC
- [ ] TOCProvider
- [x] Tool
- [ ] Toolbar
- [ ] ToolDropdown
- [ ] \* all transformations

**Comment by michael** [comment]
Take these first:
- Component
- Configurator
- DocumentSession
- Annotation
- DocumentNode
- DOMElement
- Document
- ProseEditor
- TextPropertyEditor
- ContainerEditor
- ScrollPane
- SplitPane

Then these:
- InlineNode
- TextBlock
- TextNode
- AnnotationComponent
- AnnotationTool
- AnnotationCommand
- EditInlineNodeCommand
- InsertInlineNodeCommand

**Comment by dmukhg** [comment]
Component done and merged. #814 

Picking up Configurator now.

**Comment by michael** [comment]
Hey! Good you are writing. Was about to take Configurator. ;)

I will work on documentation for all command/tool related stuff now (Command/AnnotationCommand, etc.)

Btw. @oliver---- is working on a much improved doc generator, so we should see some reward of our work soon. :)

**Comment by dmukhg** [comment]
Great. I can take up Configurator, DocumentSession and Node related classes.

About the improved doc generator, that's good news!

**Comment by michael** [comment]
@schatten the new doc generator is working now.. To serve and auto-compile the docs do:

```
npm run docs
```

We no longer need this extra comment HACK ( `/** INCLUDE_IN_API_DOCS */`) to have them displayed. Let me know if there are any problems.

**Comment by michael** [comment]
Don't forget to npm install again.

**Comment by michael** [comment]
We have tagged beta.5.4 yesterday. Docs are far from perfect. But hope we can have them much improved until tagging beta 6 (in 3-4 weeks).

**Comment by Integral** [comment]
what is 5.4?
pls don't forget to upload docs to http://substance.io/docs

**Comment by michael** [comment]
Yes, we are working on all that. 

5.4 because we had some npm publish attempts that were missing files. So we had to bump version numbers as npm doesn't let you overwrite a version once published. Could be we need to patch it again, but so far it looks good.
