### ISSUE TITLE
Call order of event listeners undetermined because of priority sorting

### ISSUE THREAD

**Issue by michael** [substance/substance#812]
Because of sorting bindings by priority after registering an event listener, the registration order gets lost (https://github.com/substance/substance/issues/807#issuecomment-250967990).

See: https://github.com/substance/substance/blob/develop/util/EventEmitter.js#L80

We probably want to: `bindings.sort(byPriorityDescendingAndRegistrationOrderAscending)`

Thoughts?

**Comment by michael** [comment]
Should we remove the priority sorting now that we have flow stages for those situations?

**Comment by obuchtala** [comment]
Agreed.

**Comment by obuchtala** [comment]
We have removed this API.
