### ISSUE TITLE
ContainerAnnotationAnchor is broken

### ISSUE THREAD

**Issue by Integral** [substance/substance#817]
[This thing](https://github.com/substance/substance/blob/develop/model/ContainerAnnotation.js#L157) throws error: `Class constructor EventEmitter cannot be invoked without 'new'` 

Probably you should remove this line as you do mixin belows.

**Comment by michael** [comment]
I have a fix I think in #118. Does this help? The problem with this fix is that we pollute top-level things with EventEmitter. Also, generally, don't expect container annos to work yet.

**Comment by Integral** [comment]
Not sure that i get what you mean with that old issue.
I don't expect them to work, but now it's throwing error. If you switched to mixins (like in component) then you don't need to call it in constructor I think.

**Comment by Integral** [comment]
I must say that this error comes with es6ification of models.

**Comment by michael** [comment]
Sorry wrong link. #818 it is.

**Comment by Integral** [comment]
Ok, it's gone wit merge.
