### ISSUE TITLE
Buble or not buble

### ISSUE THREAD

**Issue by michael** [substance/substance#819]
Saw some issues when running the testsuite headless. E.g. Texture testsuite seems to break because of some Buble transpile issues.

```
# jats/article: Attributes should be converted.
/Users/michael/projects/substance/texture/dist/test/run-tests.js:4591
    XMLImporter$$1.call(this, config)
                   ^
TypeError: Class constructor XMLImporter cannot be invoked without 'new'
```

When I use the library from Node6 (e.g. running the test suite), things are better if we don't have the transpiler on.

I wonder if we should only support Node >6, now that we have an ES6 code-base. Buble for the browser bundle seems reasonable.

**Comment by obuchtala** [comment]
Strange. Because it was working already. Need to check.

**Comment by obuchtala** [comment]
I suppose your build is somehow inconsistent.
I pushed a fix bumping substance-bundler. And also make sure that substance-test is up2date.

**Comment by obuchtala** [comment]
As long it is working, I am for buble, at least for now.
