### ISSUE TITLE
Running browser tests in Substance fails

### ISSUE THREAD

**Issue by michael** [substance/substance#821]
Ad running browser tests: I ran `node make -s build test` with a fresh install but get the error that test is not present. There's some invalid JS syntax there with dot notation. 

![image](https://cloud.githubusercontent.com/assets/2931/19072764/4a738e1e-8a37-11e6-9d1f-7862539d6da1.png)

Should be global['substance-test']. It's generated stuff, so i'm not sure how to fix that...

**Comment by obuchtala** [comment]
Strange. It is working for me.

```
> cd /tmp
> git clone https://github.com/substance/substance
> cd substance
> npm install
> node make build test -s
```

**Comment by obuchtala** [comment]
Serves the test-suite as expected.

**Comment by obuchtala** [comment]
Are you sure you tried on a fresh install?

**Comment by obuchtala** [comment]
The error you get happens with an outdated bundler, which was a regression.
So I am pretty sure that either substance is not up2date or you have not installed the node_modules freshly.

**Comment by michael** [comment]
could be. checking sorry..  my fresh npm install hangs.. bad connection.

**Comment by michael** [comment]
Working now, my bad. I played around a bit with changing tests and have the watch option on. For a browser-test development workflow it would be nice to only build the browser bundle and the browser tests.

Does it make sense to create individual tasks for that, e.g.

``` js
b.task('test:browser', ['test:clean', 'test:assets', 'test:browser'])
b.task('build:browser', ['clean', 'css', 'browser'])
```

And then run

```
node make build:browser test:browser -s -w
```

?

**Comment by obuchtala** [comment]
Sure :)

**Comment by michael** [comment]
I want back the good old.. npm start command, that serves the browser test suite, and the docs and recompiles them as we change things. :)

Also, can we serve some index page? Currently you need to navigate to localhost:5550 directly.

**Comment by obuchtala** [comment]
That all should be possible :)

**Comment by michael** [comment]
I send a PR in a bit. ;)

**Comment by michael** [comment]
@oliver---- pls review and merge #822
