### ISSUE TITLE
Is there any way to obtain contents as a PDF?

### ISSUE THREAD

**Issue by naveenarun** [substance/substance#841]
sorry if this question is redundant, I just started using this after seeing Texture.

(if there isn't a download-pdf project I'm willing to help out...)

**Comment by obuchtala** [comment]
Hey @naveenarun,
we don't have nothing beyond the browsers native printing caps.
In Texture land, there might be options where texture is embedded into OJS for instance.
In early Substance days, we used pandoc on the server side.

So, short answer, there is no pdf download right now.
Contributions are of course very welcome. How would your solution look like?

**Comment by michael** [comment]
I think you just need to look for JATS to PDF solutions. Like this one:

https://www.martineve.com/2016/06/19/cassius-now-supports-full-headless-pdf-creation-from-jats/

I'm sure there are more. The important bit is, printing or any kind of processing JATS is out of scope for Texture and should be provided as separate projects.
