### ISSUE TITLE
Edge case with incremental rendering

### ISSUE THREAD

**Issue by michael** [substance/substance#847]
As discussed:

``` js
    let contentEl = $$('div').ref('content').addClass('se-content')
      .append(overlay)
      .append(gutter)
      .on('contextmenu', this.onContextMenu)

    if (contextMenu) {
      contentEl.append(contextMenu)
    }

    // ERROR: children are not rendered if contextMenu was set in previous rerender
    // and is now undefined
    contentEl.append(this.props.children)
```

I will push a branch where that behavior can be observed.

**Comment by michael** [comment]
Use Texture#develop with substance#issue-847 to reproduce this error. 

Steps:
1. right click to open context menu
2. right click again

-> document contents get wiped.

**Comment by obuchtala** [comment]
Seems to be a problem with RenderingEngine indeed.
As a workaround for now: wrap the children in an extra div.

**Comment by obuchtala** [comment]
Hard for me to reproduce as this branch is not independent, i.e. it changes ScrollPane and a other stuff. Next time better to create a test-case.
