### ISSUE TITLE
intercept key events

### ISSUE THREAD

**Issue by wolpers** [substance/substance#854]
Hi, i am currently looking into the substance library and attempting to find a way to intercept key events and handle them on my own.  Is there any, other than extending the ContainerEditor?

**Comment by michael** [comment]
Will be possible in next release via package configuration.

https://github.com/substance/substance/blob/beta-6/packages/strong/StrongPackage.js#L27

**Comment by obuchtala** [comment]
See https://github.com/substance/substance/blob/ad6454a6ac103815e510740706f3aa5913abe84c/util/Configurator.js#L369
