### ISSUE TITLE
Dist folder not available in release

### ISSUE THREAD

**Issue by khlbrg** [substance/substance#856]
"dist/substance.cjs.js" is declared as "main" in package.json. This file or folder is not available/released.

**Comment by michael** [comment]
Are you using the npm release? This is not working if you just depend on the Git repo, because it does not contain the bundled and transpiled files.

**Comment by michael** [comment]
In package.json if you use:

```
{
  ...
  "substance": "1.0.0-beta.5.8"
}
```

it should work.

**Comment by khlbrg** [comment]
Yeah your'e right.

I required substance in a completely new project and it worked.

Must be some old other issues with the project.. thanks
