### ISSUE TITLE
Editing: Hitting backspace in an empty text node after an isolated node should remove the text

### ISSUE THREAD

**Issue by michael** [substance/substance#872]
![backspace-after-image](https://cloud.githubusercontent.com/assets/2931/20343342/49ca1ad6-abee-11e6-8207-d09adf3c29fa.gif)

Desired behaviour:

- text gets removed
- cursor right of isolated node (think that's a better backspace behaviour than selecting the node)

**Comment by obuchtala** [comment]
Done.
