### ISSUE TITLE
Remove CollabSession in favor of a smarter CollabClient

### ISSUE THREAD

**Issue by michael** [substance/substance#873]
### Desired API

First we create a regular local editorSession.

```js
let editorSession = new EditorSession(doc, {
  configurator: cfg
})
```

Then we connect it to a Collab Endpoint.

```js
let collabClient = new CollabClient({
  connection: myWebsocketConn,
  editorSession: editorSession
})
```

CollabClient will then operate on the editorSession and apply remote changes or add markers that represent remote selections.

**Comment by Integral** [comment]
D u need any help here?
