### ISSUE TITLE
Isolated Node Editing Behavior

### ISSUE THREAD

**Issue by michael** [substance/substance#875]
We want to improve the editing behaviour when isolated nodes are involved. The current approach, using brackets (like cursor before,after an isolated node) is not ideal.

Goals of a better approach:

- Less possible selection states (only as many as needed!)
- Delete/Backspace always deletes something
- typing (or typing over) is always possible
- ability to insert before an isolated node (when on first position)
- ability to insert at the back of the document (when last node is an IN)
- ability to insert between two isolated nodes

The following grid defines interactions for different scenarios which we can treat differently. E.g. when an isolated node is wrapped in text, we don't need before/after brackets, while in scenarios where two isolated nodes are touching each other or when you have an IN at the beginning or very end of a document, we need a way to put the cursor before or after that first or last node.

The following grid describes the expected behaviour (to be discussed) in different situations. The short bars are text elements, the tall bars are isolated nodes. Blue marks a selection or cursor. Isolated nodes offer before after selection points (horizontal blue lines) but only in cases when they are needed. As an example we use a document that has nothing but 2 isolated nodes as content.

![image](https://cloud.githubusercontent.com/assets/2931/20349393/995731a8-ac0a-11e6-91c3-bb48e16082c7.png)

**Comment by obuchtala** [comment]
Things that spring into my mind:
- deleting the isolate node instantly might be questionable. Deleting at the end of a text node does not remove visual content, only merge, i.e. removing the break.
- we probably need a place to put the cursor while in-between two INs, so that the Contenteditable remains focused. Things like getting the bounding box of the selection rectangle need to reflect this.
- maybe we need to apply a similar approach as with drop teaser (but inside container editor), otherwise this might get jumpy.

**Comment by michael** [comment]
- I intended to make the behaviour consistent with inline node, which would mean that when the cursor is right after an inline node
  -  backspace deletes it (like a character)
  - shift-left selects the inline node
  - (no difference between an isolated node 'character' and a regular char)
- yeah definitely we need islands like the brackets. they would 'appear' above and below an isolated node. Can we disable them in the normal case and only enable then if necessary (like two IN are touching each other)
- yeah either we do it that way or we use the brackets markup and color it with an outline. We need to make sure the brackets don't expand visually. not sure if an element with height: 0 and an outline is displayed at all.

**Comment by obuchtala** [comment]
I think we are pretty good here.
Surely we will iterate. But closing this having finished the first (proper) iteration.
