### ISSUE TITLE
Controlled Collaboration

### ISSUE THREAD

**Issue by michael** [substance/substance#889]
In real world collaboration scenarios often iterations are done sequentially. We think a system that supports that makes sense many cases.

Imagine a situation where only one user is authorised to commit at a time:

- A creates doc (A is the active editor)
- A sends doc to B (B is now the active editor)
- B makes changes until he's done and then explicitly 'commits' the changes and sends doc to C
- everybody gets the update

This is particularly interesting for review scenarios. The reviewer wants to control when the changes are seen by others.

**Comment by podviaznikov** [comment]
👍 for this use case. It's the one that I personally need

**Comment by gagarine** [comment]
Perhaps the ability to block only part of the document? So on reviewer can work on a chapter when an other do another one?

This can be useful in other case certainly.
