### ISSUE TITLE
Collab: When inserting text inside an annotation we see an error

### ISSUE THREAD

**Issue by michael** [substance/substance#893]
![image](https://cloud.githubusercontent.com/assets/2931/20652502/d201b552-b4fa-11e6-870c-fe22b8445e4c.png)

Can be reproduced in new SimpleWriter collab setup. https://github.com/substance/simple-writer/pull/1

Checkout collab branch.

**Comment by michael** [comment]
@oliver---- can you have a look at this when you get some time? Use the collab branch of simple-writer and devtool for debugging. Works better than iron-node.

**Comment by obuchtala** [comment]
Will do

**Comment by obuchtala** [comment]
@michael setup is not working ATM. ping me when this is supposed to work.

**Comment by michael** [comment]
@oliver---- should be working now.

**Comment by obuchtala** [comment]
I investigated this one: Beyond a bug in `ObjectOperation.toJSON()`, there is a greater problem. `CoordinateOperations` do not work with plain JSON, only with rich objects (~Annotations and CoordinateAdapters).
Unfortunately this means that this issue won't fix ATM, and I have to refactor the underlying Annotation data model. Which I actually wanted to do a long time already.

**Comment by michael** [comment]
Sounds good. Let's push the Beta 6 release and get this in. Also need some more time with the cleanwrite of the collab protocol stuff.
