### ISSUE TITLE
How to render a document without the editor?

### ISSUE THREAD

**Issue by rquast** [substance/substance#897]
Is there an easy way to render the document without the toolbar or editor? Do you use a html converter or something to convert a fixture to a doc to html?

**Comment by rquast** [comment]
I am able to sort of do it like this (but with it selecting images)..

```

class NotAnEditor extends AbstractEditor {
  render($$) {
      let doc = this.editorSession.getDocument()
      let el = $$('div')
      let body = $$(ContainerEditor, {
        editing: 'readonly',
        disabled: true,
        node: doc.get('body')
      })
      el.append(body)
      return el
    }
}

(snip)

let cfg = new ProseEditorConfigurator()
cfg.import(ProseEditorPackage)
cfg.import(ImagePackage)

window.onload = function() {
  let doc = cfg.createArticle(fixture)
  let editorSession = new EditorSession(doc, {
    configurator: cfg
  })
  NotAnEditor.mount({
    editorSession: editorSession
  }, document.body)
}
```

**Comment by rquast** [comment]
<img width="1273" alt="screen shot 2016-11-30 at 5 59 20 pm" src="https://cloud.githubusercontent.com/assets/1103891/20744280/c81a4d14-b726-11e6-8b0a-951c63888c93.png">

**Comment by michael** [comment]
Using a disabled ContainerEditor is one valid way (especially if you want to use the same component for editing and rendering). However you could also just write custom read-only components, which are much more trivial than employing the whole editor setup.

To learn how to use an HTML/XML converter, check the SimpleWriter example: 

https://github.com/substance/simple-writer

**Comment by rquast** [comment]
Thanks for the advice. 👍

**Comment by MGDSoft** [comment]
Hi @michael, 
I am trying to create "inmortal" nodes (it can't be deleted, moved or updated) but I dont know how. 
In other issue #573, Oliver said that content should go into a separated surface, then I need create a abstract editor for each disabled elements?.

I know how to create a Writer but, How can I make a component readonly? 

Thanks in advance
