### ISSUE TITLE
Using VirtualDOM Object to generate the DOM!

### ISSUE THREAD

**Issue by sadiqevani** [substance/substance#909]
Hello,

I am wondering if i can pass somewhere the exact representation of the DOM in JavaScript objects, and convert that to the realDOM that **substance** is using.

Generally React.DOM.div() simply returns a JS object into the React.render() and generates the DOM.

Was wondering if substance does the same?

Regards
Sadi

**Comment by michael** [comment]
In Substance the render function of a Component takes a $$ argument, which is the element constructor function (like React.createElement).

```js
class MyComp {
  render($$) {
    return $$('div').append('Hello world')
  }
}
```

Look around [here](https://github.com/substance/simple-writer) for more usage examples.

**Comment by sadiqevani** [comment]
Hey @michael i dont think this would solve my issue or clear up how to achieve what i am thinking.

Let me tell it in more general scope.

What i am looking to do is to:

1. Parse HTML from **x** Source
2. Create a AST Object (JSON or JS Object) of the HTML
3. Create a VDOM representation of this HTML
4. Now in step **4** i would like to take this VDOM, hydrate it (basically something what React.createElement() or h() does, which returns a JS Object with attribute name, props and childrens)
5. Render the JS Object / VDOM into Substance
6. Also while rendering i believe i can create custom props in Substance, to create the appropriate  effect i want for that specific Element. Let say substance detects the image, and creates a wrapper where i can use it to upload, modify, that image!

Any ideas if this would be achievable with Substance? 

A more basic idea, is i am trying to build an editor where i can manipulate HTML through substance, generate the specific AST Object through it or technically be able to update it, and then reiterate.

JSON or AST Object -> Substance -> JSON or AST Object or Events detecting this change and doing the appropriate manipulations on the JSON/ASTObject copy somewhere.

Let me know if there's a way to achieve this through Substance. I would love to use Substance.
