### ISSUE TITLE
Example of tool customization

### ISSUE THREAD

**Issue by podviaznikov** [substance/substance#911]
Hello,

I looked through the examples and the `minimal editor` example is the closest to what I need.
However I have trouble understanding how one can display both annotation tools and text transformation tools in the same bar.
E.x. I want `Header 1`, `Header 2`, `Bold`, `Italics` to be in the same popover.
Something like on medium:

<img width="307" alt="editing_asdasd" src="https://cloud.githubusercontent.com/assets/429706/21130957/a1962cd2-c0c0-11e6-971e-adcf7bc3375d.png">

How would I approach this? What classes should I extend etc? How to make text switch control to be not a dropdown but render all the tools with appropriate icons? I'm using https://github.com/substance/examples/tree/develop/minimal as a base.

**Comment by podviaznikov** [comment]
Figured that out.

**Comment by michael** [comment]
Hey! 

Great. Basically you are completely free with the markup for tools. You just need to model a command (getCommandState) and use that to render the tool.

**Comment by podviaznikov** [comment]
Maybe I did it incorrectly but I just overwrote `SwitchTextTypeTool.prototype.render` function. That worked for me.

**Comment by michael** [comment]
That's perfectly valid way. As long as you don't need more customisation.
