### ISSUE TITLE
Bundle only used code

### ISSUE THREAD

**Issue by podviaznikov** [substance/substance#916]
I use SimpleWriter as a base for my editor prototype. 
Using substance bundler using `npm bundle` will produce `dist/app.js` and `dist/substance/substance.js`.
`dist/substance/substance.js` is over 1MB right now and it includes packages and components that I don't need and don't use.
Do you know if it's possible to make a custom build somehow with only pieces that are used in app.js? Or maybe there is a way to bundle everything in app.js (both custom code and used substance code).

**Comment by michael** [comment]
Hi!

You can just import using ES6 (index.es.js ) and treeshaking should exclude parts you don't use. This should work by removing substance from the externals in your build config:

https://github.com/substance/simple-writer/blob/develop/make.js#L23

**Comment by podviaznikov** [comment]
@michael thanks for the comment. I understand change that is required in `make.js`, however I'm not sure how to force importing of ES6 (`index.es.js`).
E.x.
I have such import in my code:
```
import { Configurator, EditorSession } from 'substance'
```
And by running `npm run bundle` I'm getting 
```
/node_modules/substance/dist/substance.cjs.js does not export Configurator
```
So it seems I'm not importing ES6 module. How do I do that?

**Comment by podviaznikov** [comment]
I figured it out. Needed to do imports using full-path like:

```
import Container from 'substance/model/Container'
```

**Comment by michael** [comment]
We need to investigate ES6 importing. You shouldn't use deep requires as the locations of the files may change with new Substance releases. So better always use require {...} from 'substance'


Regarding the error you see:

```js
/node_modules/substance/dist/substance.cjs.js does not export Configurator
```

The cjs (=commonjs) bundle of course does not do ES6 exports. Seems like somehow not the right entry point is picked. Should use index.es.js when used in a pure ES6 setting. See: https://github.com/substance/substance/blob/develop/package.json#L13

Reopening this.

**Comment by michael** [comment]
Maybe you can share the make.js file you are using.

**Comment by podviaznikov** [comment]
Yeah, I figured that it wasn't picking up proper entrypoint but didn't know how to fix it.
I added `"jsnext:main": "app/app.js",` to my package.json but it didn't help.

My current make.js file is this:
```
var b = require('substance-bundler');
b.task('clean', function() {
  b.rm('./dist')
})
// copy assets
b.task('assets', function() {
  b.css('./app/app.css', 'dist/app.css', { variables: true })
})
// this optional task makes it easier to work on Substance core
b.task('substance', function() {
  b.make('substance', 'clean', 'browser')
})
b.task('build', ['clean', 'assets'], function() {
  // Copy Substance
  b.copy('node_modules/substance/dist', './dist/substance')
  // b.copy('node_modules/substance-cheerio/dist', './dist/substance-cheerio')
  b.copy('app/index.html', './dist/index.html')
  b.js('app/app.js', {
    // buble: { include: [ 'lib/**' ] },
    // external: ['substance'],
    // external: [ 'substance-cheerio' ],
    commonjs: { include: [
      'node_modules/lodash/**',
      '/**/node_modules/lodash/**',
      // 'node_modules/substance-cheerio/**',
      // '/**/node_modules/substance-cheerio/**'
    ] },
    // format: 'cjs',
    sourceMap: false,
    targets: [{
      dest: './dist/app.js',
      format: 'umd', moduleName: 'app'
    }]
  })
})
// build all
b.task('default', ['build'])
// starts a server when CLI argument '-s' is set
b.setServerPort(5555)
b.serve({
  static: true, route: '/', folder: 'dist'
})
```

Though it might be different now then it was when I posted the issue.
Also maybe the problem was that I was suing node 4? Does substance requires node6?

**Comment by michael** [comment]
There are definitely some problems when using the jsnext:main entry point. E.g. with lodash which is currently imported as a commonjs module. Working on switching it to the `lodash-es` package instead so all the Substance sources are all pure ES6 modules. Will let you know once fixed.

**Comment by michael** [comment]
You should now be able to create single-file bundles. At least for the browser... I managed to replace the CommonJS lodash dependency with lodash-es. However on the server we still have substance-cheerio which is exposed as a CommonJS module. We'll fix that later.

In order to make your build consider the `jsnext:main` entry points you have to provide `rollup-plugin-node-resolve` as a plugin. E.g. this worked for me to create a single file bundle: https://github.com/substance/simple-writer/blob/develop/make.js#L26

We may want to support this directly via bundler with simple flags (`jsnext, browser, module`) in the future.

**Comment by podviaznikov** [comment]
With recent changes to the bundler I have no more problems. I was able to configure everything I wanted to bundle browser version. Cheerio dependency problem was also solved. Thank you!
