### ISSUE TITLE
Orphaned file nodes in document after saving images

### ISSUE THREAD

**Issue by rquast** [substance/substance#917]
I've been able to use sync to upload/save images, updating the url, but I can't understand why once an image is removed, the file node remains in the document.

Is there a guide to using sync() properly? I think I am doing it right, but I think there must be some step where you have to removed orphaned file nodes before saving the document. Here is a screenshot of what I mean (3 images, many filenodes from previously removed images).

<img width="409" alt="screen shot 2016-12-24 at 8 27 27 am" src="https://cloud.githubusercontent.com/assets/1103891/21463331/684660fe-c9b3-11e6-9fbb-71ad2a573fb1.png">

**Comment by michael** [comment]
We intentionally keep the old file nodes, as they may be needed when undo/redo is performed.

**Comment by rquast** [comment]
I was thinking you might do that. So how do you deal with persisting a document with json converter?

**Comment by michael** [comment]
The new FileProxy API's need some final polish and documentation. Meanwhile for a reference implementation of a file proxy see: https://github.com/substance/substance/blob/develop/packages/file/DefaultFileProxy.js

**Comment by rquast** [comment]
Maybe a simpler question is, can json converter be prevented from serializing the orphaned file nodes (or anything that may be considered transient)?

**Comment by rquast** [comment]
I'd like to close this issue since I found the orphaned file nodes to be helpful when saving on the server. It's one way to get the server to delete old files, by checking for images that are no longer linked.
