### ISSUE TITLE
List Package

### ISSUE THREAD

**Issue by podviaznikov** [substance/substance#927]
I've been using substance for the last couple of weeks and it works great for me.
The only big thing missing is proper ListPackage.

I now it's scheduled for Beta 6. Is there any timeframe for this version? I wasn't able to find it.

P.S. I was thinking implementing ListPackage myself too, but it seems that for now it's hard to do since ListEditing is coupled with other core functionality.

**Comment by michael** [comment]
This is being worked on and hopefully ready by end of month. Lists or list-ish content in general needs some special editing behaviour, so it's good to wait for the reference implementation I think.

**Comment by podviaznikov** [comment]
I just tried newest version and simple list editing seems to work. 
Thanks for this PR https://github.com/substance/substance/pull/935!

And it was indeed done before the end of the month.
