### ISSUE TITLE
document:changed event no longer emitted

### ISSUE THREAD

**Issue by michael** [substance/substance#928]
@oliver---- can you check why this is the case? I see that Document._apply is called but this only emits operation:applied events per op, but not a document:changed event anymore.

**Comment by michael** [comment]
Using `this.editorSession.onUpdate('document', this._onDocumentChanged, this)` now instead. Not sure if the event on the doc instance makes still sense? E.g. when no editor session is used.

**Comment by obuchtala** [comment]
doc._apply is an internal method which intentionally does not emit a document:changed event (and never has been).
The primitive operations still emit: https://github.com/substance/substance/blob/develop/model/Document.js#L424
Also remember to use a transaction, which is now on EditorSession.

**Comment by obuchtala** [comment]
Probably, you suggest to have a more light-weight EditorSession for background manipulation?

**Comment by Integral** [comment]
Hey!
It would be very useful to still document:changed event.
One of the cases which i run to was reader app, e.g. editor with disabled:
true option. In this case I can't even use onUpdate as it trying to get
focusedSurface internally. Still i want to know when document changed for
updating highlights. Of course there are a lot of other ways to do it, but
relying on old document:changed is much easier.

**Comment by michael** [comment]
What I observed is that when changes are made to the document via editorSession.transaction(), document does not emit the `document:changed` event, and if that's intended.

**Comment by michael** [comment]
We could agree on removing those events (document:changed, operation:applied?) stuff from Document completely, and always require a session-like interface for manipulation and events. Currently we have a bit of a mix which could get confusing.

**Comment by obuchtala** [comment]
I brought this back.
We should promote that in UI, the preferred way is to use editor session hooks.
Still, in model implementations it is very useful to receive this event

**Comment by obuchtala** [comment]
See 24d701d01ec5c486c7fe00747772be2b99ae2ba9

**Comment by Integral** [comment]
Thanks!
