### ISSUE TITLE
Footnotes

### ISSUE THREAD

**Issue by podviaznikov** [substance/substance#930]
I'm wondering how would it be possible to implement footnotes tool.
So less say I entered some text and want to add footnote. How would I know footnote number?

Do I implement this piece of state outside of Substance package or somehow inside? Looking for any tips and pointers how to implement such a tool.

**Comment by michael** [comment]
Footnotes are app-specific and won't be implemented in core. However I will be working on footnote support in Texture (the scientific editor we are building).
