### ISSUE TITLE
Editing issues and isolated nodes

### ISSUE THREAD

**Issue by dannelundqvist** [substance/substance#933]
Here are the issues that we have found in the current editing area ordered in matter of importance.

Blockers
- [x] context menu (ie spell checker) should show suggestions if cursor is over mis-spelled word (windows does not select word automatically, works in Mac OS only).
- [x] Drag image from editing area onto an isolated node
- [x] Drag image from file manager onto an isolated node
- [x] It should be possible to use TAB to navigate between fields in an isolated node
- [x] It should be possible to select over multiple nodes/text nodes and delete
- [x] It should be possible to select and cut and paste multiple nodes/text nodes
- [x] Quotation marks inserted in Windows Chrome should be correct (ie ”Correct quotation”, not "inch markers"

Important
- [x] It should be possible to paste text content in an annotated field in an isolated node
- [x] It should be possible to have multiple lines in a TextPropertyEditor
- [x] It should be possible to navigate into a fields of an isolated node from selecting a node and as a suggestion pressing ~~ENTER~~ SPACE, then leave by pressing ESC.
- [x] Keyboard commands are "lost"/not catchable when the cursor is in a field in an isolated node.
- [x] ~~Clicking just below an isolated node, which is last in the document, should automatically insert a new paragraph.~~ Allow to add an empty paragraph after isolated node

Pos stuff
- [x] Inline objects should be draggable
- [x] Keyboard selection to the right should be removed by pressing left arrow
- [x] Content menu marker in gutter should not jump when clicked
- [x] When showing context menu, the annotation menu should not be visible

**Comment by michael** [comment]
> In windows a context click on a word should select the word automatically (ie spell checker). Works in Mac OS only.

In Windows there's a different behaviour on right click. You have to first select the text, then right click. This should work then correctly. Can you confirm?

**Comment by michael** [comment]
> Quotation marks inserted in Windows Chrome should be correct (ie ”Correct quotation”, not "inch markers"

I think this is not really an input problem, I would expect our editor to insert " inch markers, which corresponds to the key being pressed. What we can do here is apply a macro that switches out the inch chars with start and end quotation marks. That would be the same as in Google Docs then.

**Comment by obuchtala** [comment]
@michael is working on the drag and drop stuff

**Comment by oliver----** [comment]
TAB works for me in the example.
Need to check the behaviour in your environment.
Can't get the NPWriter env running right now.

**Comment by obuchtala** [comment]
> It should be possible to paste text content in an annotated field in an isolated node

Works for me in our examples. Still would like to check in your env.

**Comment by obuchtala** [comment]
> It should be possible to have multiple lines in a TextPropertyEditor

Introduced a prop called for TextPropertyEditor:
```
$$(TextPropertyEditor, {
   ...
   multiLine: true
})
```

**Comment by obuchtala** [comment]
Quotation marks in GoogleDocs/Chrome/Windows:
![quotation-marks-gdocs-windows](https://cloud.githubusercontent.com/assets/284099/22547769/945bb252-e943-11e6-96a6-e010590154c8.gif)

GDocs inserts two different chars depending on the previous/next character -- but no 'matching quote mark' thing (what I feared ;) ).

I will add a custom KeyHandler that picks this kind of event and inserts a quote mark.

**Comment by obuchtala** [comment]
Right click behavior in GDocs/Windows:
![right-click-behavior-windows](https://cloud.githubusercontent.com/assets/284099/22548174/83b0e20e-e945-11e6-9ccf-cf03fd138bf9.gif)

As @michael said, on Windows right-click does not select a word (which is actually more consistent than on OSX).

**Comment by dannelundqvist** [comment]
I think you are correct in that the behaviour should be consistent on the current platform. I.e, it is fine that the select behaviour is different on the different platforms. The problem here is that the spelling suggestions require the word to be selected.

So maybe the issue would be better described as "context click should bring up spell check suggestions for the current word regardless of it being selected or or not"?

**Comment by obuchtala** [comment]
Agreed.

**Comment by khlbrg** [comment]
@oliver---- Did you get the env up and running?

**Comment by obuchtala** [comment]
Yep. Just now :) Thanks.

**Comment by obuchtala** [comment]
> It should be possible to use TAB to navigate between fields in an isolated node

This is now working.

**Comment by perljunghall** [comment]
> I would expect our editor to insert " inch markers, which corresponds to the key being pressed.
 
As a matter of fact the character on the key, at least on Apple keyboards, is the "correct quotation". When comparing the characters in VAG Rounded used on the Apple keyboards up until 2015 there is no doubt. (Typographical example from http://www.myfonts.com/fonts/adobe/vag-rounded/)
Also, in our context we never _ever_ use the inch marks, but obviously quite frequently the quotation marks.
![inch-quote](https://cloud.githubusercontent.com/assets/17921981/22585519/7d4c587c-e9f8-11e6-9701-588dc2d58bb0.jpg)

**Comment by obuchtala** [comment]
@perljunghall I agree that in very many / most text-processing contexts quote marks are preferable. Still there should a be way to produce inch marks, too. Thus I suggest to make this configurable.

Another approach I saw somewhere (maybe in word) is applying an automated transformation. I.e. at first an inch mark is inserted, second it is changed to a quote mark (left or right). By undoing the latter, the user can get his inch mark back. What do you think?

**Comment by perljunghall** [comment]
@oliver---- Sounds reasonable enough to me.
I also think it very well could be configurable.

In Mac OS keystroke alt+shift+2 always gives you a correct quote marker. If the default character of shift+2 is configurable, do you think alt+shift+2 should be reversed to inch marker if correct quote was the chosen default character of shift+2?

**Comment by perljunghall** [comment]
However I do have to give @michael that on a HP keyboard I just came across here at the office, the character of the key is actually the inch marker. 8)

**Comment by obuchtala** [comment]
> It should be possible to navigate into a fields of an isolated node from selecting a node and as a suggestion pressing ENTER, then leave by pressing ESC.

We have introduced two modes for IsolatedNodes. One which is the default, using a 'blocker' as introduced with beta-5, and one mode similar to how it was done in beta-3, more open where you navigate inside without any further action.
The gesture to get into the isolated node is 'SPACE' when the node is selected. For that to work, the inner component must expose a `grabFocus()` method. (Maybe we will add a default implementation later, which takes the first text property found.)

**Comment by obuchtala** [comment]
> Clicking just below an isolated node, which is last in the document, should automatically insert a new paragraph.

We have added support to 'break' an isolated node using ENTER, which inserts a new paragraph behind the node, no matter if at the end or in the middle of a document.

**Comment by obuchtala** [comment]
Demo: 

![isolated-nodes-in-beta6](https://cloud.githubusercontent.com/assets/284099/22797251/df86d0a8-eefd-11e6-8579-2c2631fa7c27.gif)

**Comment by obuchtala** [comment]
> Quotation marks inserted in Windows Chrome should be correct (ie ”Correct quotation”, not "inch markers"

Implemented in Substance, need to integrate into NPWriter.

See: https://github.com/substance/substance/pull/960

**Comment by obuchtala** [comment]
> Content menu marker in gutter should not jump when clicked

Not sure, but it seems to work fine now. (But did not do anything special, maybe fixed along with other things.)

**Comment by obuchtala** [comment]
>  When showing context menu, the annotation menu should not be visible

This could be solved by using a Component owning the two overlays and controlling which overlay is to be shown.

**Comment by obuchtala** [comment]
> It should be possible to "start" bold etc by pressing CMD/CTRL+B, then "end" it the same way.

We will start working on this, but won't be able to solve this right now.

**Comment by michael** [comment]
Closing this as we have shipped beta 6 with all the fixes.
