### ISSUE TITLE
InsertListTool and InsertListCommand

### ISSUE THREAD

**Issue by podviaznikov** [substance/substance#941]
It seems that those two classes should be part of core List package (same tool and command for image package). What do you think?

I started working on those and can submit initial PR if there is an interest.

**Comment by michael** [comment]
Hey that would be very helpful actually! :)

**Comment by obuchtala** [comment]
@podviaznikov yep great. You can find API on `tx` (EditingInterface) that will help you doing the manipulation.
```
tx.toggleList()
tx.indent()
tx.dedent()
```

**Comment by podviaznikov** [comment]
PR https://github.com/substance/substance/pull/943
