### ISSUE TITLE
Annotations dissappear when correcting a misspelled word

### ISSUE THREAD

**Issue by khlbrg** [substance/substance#942]
Reproduce: 
1. Type a word that misspelled 
2. Add annotation, bold for example
3. Right click and correct the spelling
4. The bold annotation is gone

[http://quick.as/zxxps8ald](http://quick.as/zxxps8ald)

**Comment by obuchtala** [comment]
This has been fixed together with general Editing fixes. One of them is when you type over an annotated text, it will preserve these annotations.
Formerly, it was implemented as delete + insert which had the described effect.
