### ISSUE TITLE
Access indexes always via getIndex not via convenience property

### ISSUE THREAD

**Issue by michael** [substance/substance#95]
The reason for that is that your function could operate on a transaction document instead of the real one. However for transaction docs the convenience properties are not available. I'm fixing this for the annotation transformations.

`tx.annotationIndex` does ont work while `tx.getIndex('annotations')` does.

@oliver---- thoughts? How can we keep doc and tx interface compatible.. I think users could easily forget that they don't have available stuff they put on their custom document class.

**Comment by obuchtala** [comment]
Hmmm.. I always have been against **not** using API.
Am 30.09.2015 21:24 schrieb "Michael Aufreiter" notifications@github.com:

**Comment by michael** [comment]
Don't understand. How mean?

**Comment by obuchtala** [comment]
I meant, that using the convenience vars was never what I wanted.

**Comment by michael** [comment]
OK. I will take care of that.

**Comment by michael** [comment]
I deleted those shortcuts, so we are not tempted anymore.
