### ISSUE TITLE
Cursor stays in paragraph when focusing on image

### ISSUE THREAD

**Issue by Integral** [substance/substance#978]
If you put focus on image via keyboard navigation or via mouse cursor will stay on the end of paragraph.
- Keyboard:
![](http://g.recordit.co/jwYkK2nG0x.gif)
- Mouse:
![](http://g.recordit.co/3ppikJkCeF.gif)

Also if you press enter you will add new paragraph and if you press anything else (delete or symbol) image will be deleted. I think it's not what users will expect. Usually you delete image also via enter (replace with new paragraph) or continue writing after image.

**Comment by Integral** [comment]
Also if you press left you will jump to second symbol of next paragraph.
P.S.: I discovered these things in beta-6 examples.

**Comment by khlbrg** [comment]
I also think it is a good idea not to replace isolated nodes (image) when user press another key, when the node is selected.
Maybe it's fine to just ignore that action? Or create a new paragraph after the node? That would be the same behavior as when user presses enter.
