### ISSUE TITLE
Tool buttons are not centered

### ISSUE THREAD

**Issue by Integral** [substance/substance#979]
Take a look:
![screen shot 2017-02-17 at 14 48 21](https://cloud.githubusercontent.com/assets/182010/23064285/3ef7eb76-f520-11e6-922b-4f6040a8caa8.png)

**Comment by michael** [comment]
You mean the icons inside the circles?

**Comment by Integral** [comment]
Yes

**Comment by michael** [comment]
Hmm, no idea how to approach this. I don't want to introduce CSS hacks to tweak individual icons, as this would not scale with new icons being used. What would you suggest?

**Comment by Integral** [comment]
Hey!
There are couple of options.
First of all change a bit css like this:
http://codepen.io/anon/pen/NdZZzX (just
change .sc-button.sm-style-outline css)
Another option is to play with fontawesome stacked icons. You can do things
like this: http://codepen.io/anon/pen/apgrwE
But i think that you will not be able to change border width...

**Comment by michael** [comment]
Hey thanks! Can you explain the two solutions? Like what did you change in first example. And how does stacked icons help with centering?

**Comment by Integral** [comment]
Ok! Main thing in a first example... I think you just need to reduce
line-height. You can just set 28px for .sc-button.sm-style-outline, then
icons will be centered.
Stacked icons is just a solution from fontawesome, take a look at
http://fontawesome.io/examples/#stacked
If you will put three icons in stack (round shape, thin circle with border
and tool icon) you will get the same thing. Combination of colors will give
you solution for active button color. But unfortunately you don't have any
control of circle border width, because it's an icon.
