### ISSUE TITLE
Unmount

### ISSUE THREAD

**Issue by podviaznikov** [substance/substance#983]
I integrated substance editor into the react app.
I initialize it in `componentDidMount` lifecycle method.
But what is the proper way to release all resources on `componentWillUnmount`?

**Comment by obuchtala** [comment]
Use `comp.remove()`. This disposes the whole tree and removes the element from parent.
Alternatively, if you only want to have the dispose functions triggered, you can call `comp. triggerDispose()`.

**Comment by podviaznikov** [comment]
thank you!
