### ISSUE TITLE
Question: Are we happy how the EditAnnotationCommand is working?

### ISSUE THREAD

**Issue by obuchtala** [substance/substance#989]
Consider editing a link.

ATM, the link tool (create, delete, etc) is enabled when the selection is not collapsed -- which is fine I guess.

On the other hand, the edit link URL tool is enabled when the selection is collapsed and over a link annotation. It does not show when the selection is not collapsed, and particularly not when the link is fully selected.

![link-editing](https://cloud.githubusercontent.com/assets/284099/23255242/2169a7d0-f9bb-11e6-988d-62a943716fee.gif)

**Comment by obuchtala** [comment]
@michael @andene what is your opinion?

**Comment by obuchtala** [comment]
I personally think, this could be an application decision. If you only have one overlay toolbar, it might get overloaded when showing both when selection is expanded.
Though, in the above example (ProseEditor) the tools are in separate areas, thus it could make sense to actually show the EditLinkTool also when not collapsed -- or at least when the link is fully selected.

**Comment by obuchtala** [comment]
Still, every Application can already register their own Command implementations, and achieve what they think makes most sense.

**Comment by michael** [comment]
Yeah we could make AnnotationCommand configurable. E.g. collapsedOnly: true ?

**Comment by obuchtala** [comment]
Probably.

It could even make sense to not show the tool if collapsed, e.g. to achieve a more calm UX. But then the selection should not be collapsed after insertion.

Let's gather a bit more, and finally come to a decision.

**Comment by khlbrg** [comment]
Yeah I think we can manage to implement our own solution to this.
I personally thinks that the editLinkTool should be displayed when the link is selected.
Think the best way is to implement and try different approaches to get the right implementation

**Comment by khlbrg** [comment]
Another idea regarding this issue would be to implement a grabFocus method also for these tools. 
So when the user has selection on a link, can he/she press TAB to edit the link, and then ESC to go back to the article.

Although I guess this could be problematic if there is multiple tools that request focus.

**Comment by obuchtala** [comment]
I see. Similar to how isolated nodes can be entered (using TAB), it would make sense to enter the edit link mode with just the keyboard.
