### ISSUE TITLE
Unite Surface + Editor interfaces?

### ISSUE THREAD

**Issue by michael** [substance/substance#99]
I documented the controller initialisation: https://github.com/substance/substance/blob/improve-docs/docs/controller.md

However, I have a feeling we should try to slim down the interface a bit. Currently we have to instantiate:
- A Controller (formally surface manager)
- An Editor (ContainerEditor, FormEditor)
- A Surface that takes a controller and an editor via construction.

Maybe we could let ContainerEditor and FormEditor inherit from Surface to make the footprint a bit smaller. I understand that Surface takes care only of selection mapping, and that editors define and handle the rest of the behaviour. But maybe we don't need this separation? I like the name Surface as a general abstraction but somehow i feel it could be more natural do things like:

``` js
var bodyEditor = ctrl.getSurface('bodyEditor');
bodyEditor.setSelection(...)
bodyEditor.getContainerId();
```

I'd also prefer to execute commands like toggleStrong on a concrete surface/editor instance rather than letting the controller delegating to the currently focused one. I mean with keybindings we have to do that of course.. but if someone wanted to trigger one those commands explicitly it feels odd to teach them:
- make sure the bodyEditor is focused
- then do `controller.executeCommand('toggleStrong')`

Better: 

``` js
bodyEditor.executeCommand('toggleStrong');
```

What's your opinion?

**Comment by obuchtala** [comment]
I think after all the refactorings (trafos etc.) the editors are indeed not doing very much anymore,
and it would be ok to merge them into Surface.

**Comment by michael** [comment]
Done.
