### ISSUE TITLE
Bundler: CSS variables are not compiled

### ISSUE THREAD

**Issue by michael** [substance/substance#992]
Just realized that CSS variables are not compiled anymore for some reason. E.g. in Substance make file:

```js
b.css('substance.css', DIST+'substance.css', { variables: true })
```

When looking at dist/substance.css there's still the variable block.

@oliver---- is this a bundler regression? Or some misconfiguration?

We should fix and make another patch release.

**Comment by michael** [comment]
Wait.. I'm totally wrong. Everything is fine. Just got confused that the variable block is still in the CSS and the comments:

```cs
:root {
  /* Layout */

  /* Normalized heights (used by buttons and inputs) */

  /* Colors */

  /* Used by Button component */ /* #f8f8f8; */

  /* Depending on a base-color */

  /* We disable this for now, as accessibility needs more discussion */ /* #1795CD;/* #5BE3FF;

  /* Font colors */

  /* Default padding */

  /* Prose font sizes */
  /* Title font sizes */
  /* Heading font sizes */

  /* code-font */

  /* RGB #A3CDFD = HSB 209,29,80 */

  /* Collaborator colors */
}
```

**Comment by michael** [comment]
While this works as expected in Substance it does not in forms, there I still see the variables. :/ No idea what the difference is. The make file looks ok.

**Comment by michael** [comment]
Mhhh with a fresh clone and npm install now it worked.

**Comment by obuchtala** [comment]
fresh clone does not sound reasonable. Maybe rm -rf of node_modules would have been enough.

**Comment by michael** [comment]
Yeah that's what I actually did. Thx ;)
