### ISSUE TITLE
Prevent annotation from expanding when typing "after" the annotation

### ISSUE THREAD

**Issue by khlbrg** [substance/substance#997]
I'm struggling with my "Link-package". 

I want a behavior that when typing at the last position/after a link annotation, I don't want the link-annotation to expand.

This is a suggestion on how this could be solved. 
I define a property on the annotation node - *_PreventExpandAnnotationWhenWritingAtLastPosition*  that is later used in model/Editing.js.

So if annoEnd and startOffset is the same, and the property is defined in the node we can just skip to extend the annotation.

__model/Editing.js__ (line: 816)
```
} else if (annoEnd === startOffset && anno._PreventExpandAnnotationWhenWritingAtLastPosition) {
        // skip
}
      // VI anno.start before and anno.end after
```

Any thoughts or comments? Or maybe I'm forgetting some important aspects?

**Comment by obuchtala** [comment]
I see. Maybe we could name it 'autoExpandRight'? default true

**Comment by obuchtala** [comment]
I agree, that this could be better for the more 'heavy' annotations such as Links. Basically, all annotations that are kind of semantic, and not visual.

When introducing the 'painting' style mode for Bold etc. we could make the suggested behavior the default.

**Comment by khlbrg** [comment]
Yeah, that name was just me trying to be clear of what it meant :)

**Comment by obuchtala** [comment]
Yeah, got it ;)

**Comment by obuchtala** [comment]
Google docs does it exactly like you suggested: auto-expand visual formatting annos and not expanding semantical ones.

![expanding-annotations-gdocs](https://cloud.githubusercontent.com/assets/284099/23567115/9f010508-00b9-11e7-9731-2d8e366550ff.gif)
